### ISSUE TITLE
小白求助 --conf-file server.conf 使用问题？

### ISSUE THREAD

**Issue by Se7enMuting** [wangyu-/udp2raw-tunnel#108]
server.conf文件的路径应该是什么？
我在和udp2raw_amd64同路径里建了个server.conf文件，按照README配置了，但是执行./udp2raw/udp2raw_amd64 --conf-file server.conf后红字提示
[2017-12-02 07:20:20][FATAL]conf_file server.conf open failed,reason :No such file or directory
直接用指令是没有问题，能正常启动

**Comment by flipphos** [comment]
server.conf应该用绝对路径，假设你的udp2raw在/bin/udp2raw文件夹下：
/bin/udp2raw/udp2raw_amd64 --conf-file /bin/udp2raw/server.conf

**Comment by gordengan** [comment]
感谢，可以了
