### ISSUE TITLE
在systemd中添加udp2raw服务无法启动

### ISSUE THREAD

**Issue by apango** [wangyu-/udp2raw-tunnel#109]
首先感谢udp2raw作者的工作。下面有一个小问题要汇报。

系统采用systemd管理服务，添加udp2raw为systemd服务，在.service文件中内容如下：

[Unit]
Description=udp2raw service
After=syslog.target network.target auditd.service
[Service]
Type=notify
NotifyAccess=all
User=nobody
ExecStart=/usr/local/bin/udp2raw_amd64 -s -l0.0.0.0:***** -r 127.0.0.1:*****  -a -k "******" --raw-mode 
faketcp
ExecReload=/bin/kill -HUP
ExecStop=/bin/kill -s QUIT  PrivateTmp=true
Restart=always
[Install]
WantedBy=multi-user.target

systemd系统重载后，用systemctl start udp2raw启动服务，报错，错误输出如下：

Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -N udp2rawDwrW_4eda80c7_C0 ,pclose returned 768 ,WEXITSTATUS 3,errnor :Invalid argument
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][INFO]run_command iptables -F udp2rawDwrW_4eda80c7_C0
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: iptables v1.4.21: can't initialize iptables table filter: Permission denied (you must be root)
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -F udp2rawDwrW_4eda80c7_C0 ,pclose returned 768 ,WEXITSTATUS 3,errnor :Invalid argument
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][INFO]run_command iptables -I udp2rawDwrW_4eda80c7_C0 -j DROP
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: iptables v1.4.21: can't initialize iptables table filter: Permission denied (you must be root)
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -I udp2rawDwrW_4eda80c7_C0 -j DROP ,pclose returned 768 ,WEXITSTATUS 3,errnor :Invalid argument
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][INFO]run_command iptables -I INPUT -p tcp -m tcp --dport 30001 -j udp2rawDwrW_4eda80c7_C0
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: iptables v1.4.21: can't initialize iptables table filter: Permission denied (you must be root)
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -I INPUT -p tcp -m tcp --dport 30001 -j udp2rawDwrW_4eda80c7_C0 ,pclose returned 768 ,WEXITSTAT
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][FATAL]auto added iptables failed by: iptables -I INPUT -p tcp -m tcp --dport 30001 -j udp2rawDwrW_4eda80c7_C0
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]:
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][INFO]run_command iptables -D INPUT -p tcp -m tcp --dport 30001 -j udp2rawDwrW_4eda80c7_C0
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: iptables v1.4.21: can't initialize iptables table filter: Permission denied (you must be root)
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -D INPUT -p tcp -m tcp --dport 30001 -j udp2rawDwrW_4eda80c7_C0 ,pclose returned 768 ,WEXITSTAT
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][INFO]run_command iptables -F udp2rawDwrW_4eda80c7_C0
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: iptables v1.4.21: can't initialize iptables table filter: Permission denied (you must be root)
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -F udp2rawDwrW_4eda80c7_C0 ,pclose returned 768 ,WEXITSTATUS 3,errnor :Invalid argument
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][INFO]run_command iptables -X udp2rawDwrW_4eda80c7_C0
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: Perhaps iptables or your kernel needs to be upgraded.
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]: [2017-12-03 20:26:31][WARN]commnad iptables -X udp2rawDwrW_4eda80c7_C0 ,pclose returned 768 ,WEXITSTATUS 3,errnor :Invalid argument
Dec 03 20:26:31 vultr.guest udp2raw_amd64[24746]:
Dec 03 20:26:31 vultr.guest systemd[1]: udp2raw-ssr.service: main process exited, code=exited, status=255/n/a
Dec 03 20:26:31 vultr.guest kill[24754]: kill: cannot find process "PrivateTmp=true"
Dec 03 20:26:31 vultr.guest systemd[1]: udp2raw-ssr.service: control process exited, code=exited status=1
Dec 03 20:26:31 vultr.guest systemd[1]: Failed to start udp2raw-ssr service.
-- Subject: Unit udp2raw-ssr.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit udp2raw-ssr.service has failed.
--
-- The result is failed.
Dec 03 20:26:31 vultr.guest systemd[1]: Unit udp2raw-ssr.service entered failed state.
Dec 03 20:26:31 vultr.guest systemd[1]: udp2raw-ssr.service failed.
Dec 03 20:26:31 vultr.guest systemd[1]: udp2raw-ssr.service holdoff time over, scheduling restart.
Dec 03 20:26:31 vultr.guest systemd[1]: start request repeated too quickly for udp2raw-ssr.service
Dec 03 20:26:31 vultr.guest systemd[1]: Failed to start udp2raw-ssr service.

输出看起来是udp2raw进程给出了exit code。
接下来测试直接运行udp2raw
/usr/local/bin/udp2raw_amd64 -s -l0.0.0.0:***** -r 127.0.0.1:*****  -a -k "******" --raw-mode faketcp
运行正常。输出中有iptable的错误，但是没有退出。用户是root。

多说一下，系统里没有iptable，用的是firewalld。systemd运行服务不用root用户，命令行直接运行udp2raw用的root用户。

猜测是自动运行iptable的问题。

建议加上选项关闭iptable自动添加防火墙规则，同时又不退出。-g参数可以生成规则不运行iptable，但是生成后udp2raw就退出了。

**Comment by wangyu-** [comment]
>建议加上选项关闭iptable自动添加防火墙规则，同时又不退出。

去掉`-a`选项就行了

**Comment by apango** [comment]
iptables的问题搞定了，可是出现一个新的问题：

[ERROR]root check failed,make sure you run this program with root,we can try to continue,but it will likely fail
把systemd配置换成User=root即可

谢谢！
