### ISSUE TITLE
PS4 net类型失败

### ISSUE THREAD

**Issue by maozheng92** [wangyu-/udp2raw-tunnel#119]
server：
./speederv2_x86 -s -l0.0.0.0:4096 -r127.0.0.1:8838  -f2:4 -k “pw” --mode 0 -q1
./udp2raw_x86 -s -l0.0.0.0:4097 -r 127.0.0.1:4096  -a -k "pw" --raw-mode faketcp --cipher-mode aes128cbc --auth-mode md5
![2017-12-11 7 04 52](https://user-images.githubusercontent.com/13172714/33828315-983b5df6-dea6-11e7-9828-e8aa37fe2637.png)
![2017-12-11 7 05 08](https://user-images.githubusercontent.com/13172714/33828316-98672c92-dea6-11e7-84d1-9d8d89ffb213.png)
![2017-12-11 7 05 27](https://user-images.githubusercontent.com/13172714/33828317-98e0d70e-dea6-11e7-97b5-127bfd84530b.png)
![2017-12-11 7 05 45](https://user-images.githubusercontent.com/13172714/33828318-99972748-dea6-11e7-8d9a-a641ee1cc095.png)

**Comment by wangyu-** [comment]
一般nat测试失败表示UDP转发失败了。

可能是 配置错误/iptables没清空，或者s的安装脚本不允许来自127.0.0.1的访问。你翻一下以前的issue看看吧。
