### ISSUE TITLE
luci-app-udp2raw: uci: Entry not found

### ISSUE THREAD

**Issue by lixingcong** [wangyu-/udp2raw-tunnel#126]
It that warning normal on commit 31f2015ab758ed8d3a4cc127d9c5b61abb8b4576 ?

	root@MT7620:/tmp# opkg install luci-app-udp2raw_1.0.0-2_all.ipk 
	Installing luci-app-udp2raw (1.0.0-2) to root...
	Configuring luci-app-udp2raw.
	uci: Entry not found

**Comment by flipphos** [comment]
Yes.

**Comment by wangyu-** [comment]
Sorry I cant reproduce the problem with my  `Chaos Calmer 15.05` and ` lede-17.01` environment.

Was the ipk built by yourself?  Does the app work  in spite of the warning?  Could you plz provide the output with opkg's debug info enabled?

**Comment by lixingcong** [comment]
Was the ipk built by yourself? Yes, I built it.

Does the app work in spite of the warning? Sure. Everything woks fine.

Here is the log:

	root@baidu:/tmp# opkg install luci-app-udp2raw_1.0.0-2_all.ipk -V 3
	opkg_conf_parse_file: Loading conf file /etc/opkg.conf.
	opkg_conf_parse_file: Loading conf file /etc/opkg/customfeeds.conf.
	opkg_conf_parse_file: Loading conf file /etc/opkg/distfeeds.conf.
	pkg_hash_load_feeds: 
	pkg_hash_load_feeds: 
	pkg_hash_load_feeds: 
	pkg_hash_load_feeds: 
	pkg_hash_load_status_files: 
	pkg_info_preinstall_check: Updating file owner list.
	Installing luci-app-udp2raw (1.0.0-2) to root...
	pkg_run_script: Running script /tmp/opkg-gioJiP/luci-app-udp2raw-OCchMN/preinst.
	opkg_install_pkg: Installing maintainer scripts.
	opkg_install_pkg: Installing data files for luci-app-udp2raw.
	install_data_files: Extracting data files to /.
	pkg_write_filelist: Creating //usr/lib/opkg/info/luci-app-udp2raw.list file for pkg luci-app-udp2raw.
	opkg_install_pkg: Resolving conf files for luci-app-udp2raw
	Unknown package '3'.
	opkg_configure_packages: Configuring unpacked packages.
	opkg_configure_packages: Reordering packages before configuring them...
	Configuring luci-app-udp2raw.
	pkg_run_script: Running script //usr/lib/opkg/info/luci-app-udp2raw.postinst.
	uci: Entry not found
	write_status_files_if_changed: Writing status file.
	pkg_write_changed_filelists: Saving changed filelists.
	Collected errors:
	 * opkg_install_cmd: Cannot install package 3.
	root@baidu:/tmp#
