### ISSUE TITLE
UDPspeederV2+udp2raw NAT Type的问题

### ISSUE THREAD

**Issue by Se7enMuting** [wangyu-/udp2raw-tunnel#129]
上海电信玩nintendo switch，最近发现无论是直连还是酸酸乳都是直接彻底NAT F了，只有用小宝的koolgame选udp in tcp或者 酸酸乳+ udp2raw可以变成NAT A。
本人小白，不太懂NAT穿透的技术原理。只是发现酸酸乳+UDPspeederV2+udp2raw，nintendo switch依旧是NAT F，只有去掉UDPspeederV2才能NAT A，觉得很奇怪，末端都是udp2raw，为什么NAT就无法穿透了呢？不知是否有解？
UDPspeederV2参数：--mode 0 -f2:2 -q1
udp2raw参数：
--raw-mode faketcp
--cipher-mode xor
--auth-mode simple
-a
连接都是正常的，可以正常上网

**Comment by wangyu-** [comment]
加UDPspeeder不会影响nat类型。

NAT fail说明配置有问题。

贴出两端的完整参数。

**Comment by Se7enMuting** [comment]
配置
Server：
/usr/local/UDPspeederV2/speederv2_amd64 -s -l0.0.0.0:10249 -r 127.0.0.1:8948 -k "*****" --mode 0 -f2:2 -q1

/usr/local/udp2raw/udp2raw_amd64 --conf-file /usr/local/udp2raw/server.conf
server.conf:
-s
-l 0.0.0.0:10149
-r 127.0.0.1:10249
-a
-k *****
--raw-mode faketcp
--cipher-mode xor
--auth-mode simple

Client:
![speedv2](https://user-images.githubusercontent.com/889925/35044411-42173f52-fbcb-11e7-9100-719627535d3c.png)

![udp](https://user-images.githubusercontent.com/889925/35044412-4246742a-fbcb-11e7-9bdb-12b69fb40f96.png)

**Comment by wangyu-** [comment]
从你贴的配置里没看到问题，你图里的udpspeeder开关没开，不过我估计你实际用的时候应该开了吧。图里抹掉的部分我就没办法帮你检查了。

我建议你先检查一下(抹掉的部分)有没有低级错误，然后按照issue guide里面的说明，提供更详细的信息。

>自己没有调整过iptables，也不会调，firewalld装了然后关掉了，貌似现在是裸奔~~

即使没调过，仍然建议执行清空操作。

再问几个问题：

1. 用udp2raw+ $时显示nat A，测试过几次，是否稳定在nat A ? 

2. 其他平台用udp的游戏是否正常工作，比如电脑、ps4上的udp游戏

**Comment by wangyu-** [comment]
>只是发现酸酸乳+UDPspeederV2+udp2raw，nintendo switch依旧是NAT F，只有去掉UDPspeederV2才能NAT A，觉得很奇怪，末端都是udp2raw，为什么NAT就无法穿透了呢？

在网上查了下，NAT type F基本上等于网络不通(具体来说应该是UDP不通)；建议你在追查时候往 udp2raw+UDPspeeder+$为什么不通的方向上想，不要从NAT为什么无法穿透上想。

**Comment by Se7enMuting** [comment]
感谢回复！！！！
udpspeeder开关实际应用中是开的，不然网络不通的
抹掉的部分不会有低级错误，用udp2raw+UDPspeeder+$时，墙外网站但是能打开的~~网络是通的~~
iptables清空我可以试下

 1. 用udp2raw+ $时显示nat A，测试过几次，是否稳定在nat A ?
测试很多次，都是A，如果不是A游戏是会立马断线的。前段时间还是可以用UDPspeeder+$达到nat A的，都是玩一半中途可能变NAT F，然后掉线。F状态时能进游戏商店，看视频，好友，就是无法游戏。
 2.其他平台用udp的游戏是否正常工作，比如电脑、ps4上的udp游戏
没有。

udp2raw+UDPspeeder+$时 打开墙外网页，上网都是正常的没问题的，你意思是可能是单独udp不通喽？请问有什么工具或者指令测试UDP连接是否导通吗？

**Comment by wangyu-** [comment]
>打开墙外网页，上网都是正常的没问题的，你意思是可能是单独udp不通喽

开网页只会用到TCP流量。梅林上的udp2raw+udpspeeder只管udp流量。你这个情况就是udp单独不通。

> 请问有什么工具或者指令测试UDP连接是否导通吗？

nc的udp模式可以收发udp数据包；UDPspeeder加上`--report 10`之后可以看到数据发送/接受报告。

**Comment by reusu** [comment]
Type F是完全UDP丢包 但是TCP正常

**Comment by Se7enMuting** [comment]
发现问题了！！
server端我是在/etc/rc.d/rc.local里添加以下两行来实现开机自启动的：
`/usr/local/UDPspeederV2/speederv2_amd64` -s -l0.0.0.0:10249 -r 127.0.0.1:8948 -k "c4aAy57e2M" --mode 0 -f2:2 -q1
/usr/local/udp2raw/udp2raw_amd64 --conf-file `/usr/local/udp2raw/server.conf`
然后我把udp2raw这行注释掉，reboot后再通过ssh来启动udp2raw，发现upd能通上了，nat A了.....
是不是我这种在rc.local里连续两行的写法导致udp2raw不启动，还是2个程序连续启动有问题？
