### ISSUE TITLE
how to add to linux env?

### ISSUE THREAD

**Issue by jjjan** [wangyu-/udp2raw-tunnel#13]
hello,
how can i add to my linux env ? so all traffic is going through udp.

**Comment by wangyu-** [comment]
>so all traffic is going through udp

Basically,you need to set up an openvpn connection via udp. And then modify default route of your linux by using `ip route`(or just `route`) command or use openvpn's `redirect-gateway` option. You aslo need to set SNAT or MASQUERADE by using `iptables` command.

Its not able to be described clearly in a few sentences.Check this link:
https://openvpn.net/index.php/open-source/documentation/howto.html#redirect

And try to find more infromation on google,by keyword "openvpn redirect traffic"
