### ISSUE TITLE
epoll 方式是否可以替换成 libevent ?

### ISSUE THREAD

**Issue by bao3** [wangyu-/udp2raw-tunnel#130]
我使用的是 Mac 系统，不想用镜像的方式，开销实在太大了。你工具不能在 mac 编译通过是因为 epoll 是 linux 独有的。
其实你分析一下，多数功能可以透过 http://libevent.org libevent 进行，这样的好处就是 libevent 自己支援 windows select, linux poll , macOS /BSD kqueue , 以及标准的 posix 。所以几乎实现全平台的应用。
希望你能考虑一下。

**Comment by wangyu-** [comment]
Contribution Guide 里去年10月就有这个内容了，https://github.com/wangyu-/udp2raw-tunnel/issues/17 ，只是目前没人愿意做。

当初使用epoll timerfd而没有使用libevent/libev/libuv的原因，主要是: 1. 避免引入编译依赖，降低交叉编译(到linux嵌入式设备)的难度。 2. 用libevent/libev/libuv这种二次包装的api更容易踩到坑

>我使用的是 Mac 系统，不想用镜像的方式，开销实在太大了

开销是指什么呢，内存/CPU？有没有具体数据呢，如果有具体的数据能说明这个开销确实大得不可接受，也许能促进一下libevent/libev/libuv的移植。

**Comment by iceonsun** [comment]
@bao3 udp2raw不能在mac上编译通过的主要原因不是epoll(可以切换到跨平台但性能稍低的poll)，而是linux和mac(BSD)的数据链路层访问API不一样。

我来安利一发Mac用户也可用的 [rsock](https://github.com/iceonsun/rsock) 。不需要装虚拟机。

**Comment by bao3** [comment]
@iceonsun 谢谢，目前还没有时间测试你的这个 rsock，节后我抽空试一下。
