### ISSUE TITLE
请问ipv6已经支持了吗

### ISSUE THREAD

**Issue by ljyloo** [wangyu-/udp2raw-tunnel#134]
我尝试bind到[::]但是报错
把项目的文档都看了遍，没发现有描述，倒是在Contribution Guide看到第9点说ipv6的，是不是还没实现
https://github.com/wangyu-/udp2raw-tunnel/issues/17
lower-level没搞懂是什么东西(小白请见谅)

**Comment by wangyu-** [comment]
还没实现

**Comment by feilongfl** [comment]
问下ipv6有什么进展么

**Comment by wangyu-** [comment]
20180728.1版及以后已经支持ipv6
