### ISSUE TITLE
openwrt环境，pppoe未连接时异常中止

### ISSUE THREAD

**Issue by sensec** [wangyu-/udp2raw-tunnel#137]
中午停电，下午来电后发现google上不去。逐一排查。最后发现ps没有udp2raw，路由器相关日志：
```
Tue Jan 30 01:44:09 2018 daemon.info udp2raw: listening on: 127.0.0.1:4899
Tue Jan 30 01:44:09 2018 daemon.info udp2raw: raw-mode: faketcp
Tue Jan 30 01:44:09 2018 daemon.info udp2raw: running from root user
Tue Jan 30 01:44:09 2018 daemon.info udp2raw: listening on: 127.0.0.1:4900
Tue Jan 30 01:44:09 2018 daemon.info udp2raw: raw-mode: faketcp
Tue Jan 30 01:44:09 2018 daemon.info udp2raw: running from root user
Tue Jan 30 01:44:22 2018 daemon.warn pppd[1353]: Timeout waiting for PADO packets
Tue Jan 30 01:44:22 2018 daemon.err pppd[1353]: Unable to complete PPPoE Discovery
Tue Jan 30 01:44:22 2018 daemon.info pppd[1353]: Exit.
Tue Jan 30 01:44:22 2018 daemon.info pppd[3048]: Plugin rp-pppoe.so loaded.
Tue Jan 30 01:44:22 2018 daemon.info pppd[3048]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Tue Jan 30 01:44:23 2018 daemon.notice pppd[3048]: pppd 2.4.7 started by root, uid 0
Tue Jan 30 01:44:34 2018 daemon.info procd: Instance udp2raw::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Tue Jan 30 01:44:34 2018 daemon.info procd: Instance udp2raw::instance2 s in a crash loop 6 crashes, 0 seconds since last crash
Tue Jan 30 01:44:38 2018 daemon.warn pppd[3048]: Timeout waiting for PADO packets
Tue Jan 30 01:44:38 2018 daemon.err pppd[3048]: Unable to complete PPPoE Discovery
Tue Jan 30 01:44:38 2018 daemon.info pppd[3048]: Exit.
Tue Jan 30 01:44:38 2018 daemon.info pppd[3098]: Plugin rp-pppoe.so loaded.
Tue Jan 30 01:44:38 2018 daemon.info pppd[3098]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Tue Jan 30 01:44:38 2018 daemon.notice pppd[3098]: pppd 2.4.7 started by root, uid 0
Tue Jan 30 01:44:48 2018 daemon.info pppd[3098]: PPP session is 31504
```

说明：
1、路由器断电后系统时间错误，仅作执行顺序参考。
2、1-6行启动2个udp2raw进程。
3、7-12行，pppoe拨号失败，服务器无响应。
4、13-14行，udp2raw crash。
5、后面就是pppoe继续重试，一直到01:44:48才拨号成功。

怀疑udp2raw多次尝试连接服务器失败导致crash。
最后 /etc/init.d/udp2raw start，成功。

udp2raw-tunnel
git version:c811dc15a3    build date:Jan 14 2018 19:39:20
repository: https://github.com/wangyu-/udp2raw-tunnel

**Comment by wangyu-** [comment]
根据你的描述，应该是先断了电，然后你在路由器没网的情况下启动了udp2raw。

在没网的情况下启动udp2raw，log里会提示失败，然后退出。目前设计上就是这样的。（如果是在udp2raw运行中途断网则不会退出，会一直重试到网络重新连接上）

如果你想达到在没网的时候一直重试直到连上的效果，可以在脚本里这么调用udp2raw :
```
while true
do
./udp2raw ......
sleep 10
done
```

**Comment by sensec** [comment]
嗯，是因为没网的情况下启动udp2raw。平时正常流程是pppoe一次成功，然后udp2raw就能正常运行，今天因为断电恢复，估计电信那边服务器反应也慢了一拍，所以就出问题了。
那我想想能不能先在启动脚本加个判断，或者直接利用openwrt的hotplug机制down就停止up再运行也可以。

**Comment by wangyu-** [comment]
>或者直接利用openwrt的hotplug机制down就停止up再运行也可以。

如果down就停止，up再运行的话，"udp2raw在重新拨号后保持上层连接不掉线"这个功能就失效了。

我觉得还是while true这种方法最简单有效。

**Comment by wangyu-** [comment]
一个比较简单的办法：

写一个脚本，udp2raw_no_quit.sh，包装一下原来的udp2raw binary。

```
#! /bin/sh
while [ true ]
do
        /usr/bin/udp2raw $*
        sleep 10
done
```

然后，你在原来调用udp2raw的地方调用这个udp2raw_no_quit.sh。

比如 ：

 `/usr/bin/udp2raw_no_quit.sh  -c -l 0.0.0.0:4096 -r 44.55.66.77:9999  --raw-mode faketcp -k 123456`

`/usr/bin/udp2raw_no_quit.sh --conf-file  /1.conf`

**Comment by sensec** [comment]
@wangyu- 作为启动服务必须有返回啊，不能一直循环。。。
启动后连接不上服务端就退出，为什么要这么设计呢？网络环境是无法预测的，客户端暂时无网络、服务器暂时无响应、两者之间的网络临时故障。。。任一因素都会导致客户端退出（不再重试），作为底层协议来说似乎不大好。

**Comment by wangyu-** [comment]
>作为启动服务必须有返回啊

现在udp2raw单独启动的时候就是无返回的，用udp2raw_no_quit.sh之后仍然是无返回的。貌似直接用udp2raw和udp2raw_no_quit.sh是没有区别的。

>启动后连接不上服务端就退出

准确来说不是连不上服务端就退出。 是在启动时候发现路由表里没有到服务端的路由后退出。

>网络环境是无法预测的，客户端暂时无网络、服务器暂时无响应、两者之间的网络临时故障。。。任一因素都会导致客户端退出（不再重试）

这些情况里，只有客户端暂时无网络会退出。服务器暂时无响应、两者之间的网络临时故障都没问题。

>作为底层协议来说似乎不大好。

我可以加一个参数，让udp2raw失败后重试不退出。不过，效果跟udp2raw_no_quit.sh是差不多的。

**Comment by sensec** [comment]
感谢！
