### ISSUE TITLE
-h说明的auth cipher mode写错了吧

### ISSUE THREAD

**Issue by usernamerror** [wangyu-/udp2raw-tunnel#14]
--auth-mode           <string>        avaliable values:aes128cbc(default),xor,none
    --cipher-mode         <string>        avaliable values:md5(default),crc32,simple,none

enum cipher_mode_t {cipher_none=0,cipher_aes128cbc,cipher_xor,cipher_end};
unordered_map<int, const char *> cipher_mode_tostring={{cipher_none,"none"},{cipher_aes128cbc,"aes128cbc"},{cipher_xor,"xor"}};

**Comment by wangyu-** [comment]
确实= =。--auth-mode  和 --cipher-mode的写反了。一会我更新一版，把这个修正过来。

**Comment by wangyu-** [comment]
已修正。
