### ISSUE TITLE
套kcptun加速SS后kcptun提示connection refused

### ISSUE THREAD

**Issue by PengQianheng** [wangyu-/udp2raw-tunnel#141]
套kcptun加速ssh是正常的，套fs加速SS也是正常的，但套kcptun加速SS时出现异常，kcptun提示如下：
2018/02/16 08:53:47 dial tcp 127.0.0.1:433: getsockopt: connection refused

**加速SS的配置**
【服务端配置】
udp2raw配置：{本地端口: 8855  远程端口: 4002}
kcptun配置：   {本地端口: 4002  远程端口:443}

【本地配置】
udp2raw配置：{本地端口: 4002   远程端口: 8855}
kcptun配置：   {本地端口: 12949 远程端口: 4002}

**加速SSH正常的参考配置如下**(我的VPS的SSH端口为26724)
【服务端配置】
udp2raw配置：{本地端口: 8855  远程端口: 4001}
kcptun配置：   {本地端口: 4001  远程端口: 26724}

【本地配置】
udp2raw配置：{本地端口: 4001 远程端口: 8855}
kcptun配置：   {本地端口: 3344 远程端口: 4001}

**Comment by wangyu-** [comment]
> 2018/02/16 08:53:47 dial tcp 127.0.0.1:433: getsockopt: connection refused

是443还是433 ？

**Comment by PengQianheng** [comment]
@wangyu- 确实是配置搞错了，应该是配置443，但是搞成了433，没有事先过滤这种低级错误真是抱歉，再次感谢协助。
