### ISSUE TITLE
请问是怎么编译二进制到这么多平台的

### ISSUE THREAD

**Issue by iceonsun** [wangyu-/udp2raw-tunnel#147]
我现在也在做一个类似的项目，二进制的发布有点烦恼。

请问是udp2raw，是怎么编译二进制到这么多平台的。
如果是自动的话，请问用的是什么工具和平台。请问用的是crosstool-ng吗
如果是手动的话，是不是每次都要切换到对应的平台静态编译，然后再一起打包上传。这岂不是很麻烦。

**Comment by wangyu-** [comment]
>如果是自动的话，请问用的是什么工具和平台。请问用的是crosstool-ng吗

不是crosstool-ng, 用的是从网上找的交叉编译toolchain。crosstool-ng太慢。

可以看编译教程：
https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/build_guide.md

里面有说怎么一次编译所有target。

**Comment by iceonsun** [comment]
非常感谢。抱歉现在才来回复。由于目前的开发平台是mac，没有build-essential. 我还是选择了crosstool-ng
