### ISSUE TITLE
存在多个interface时，服务端无法bind至非默认路由的interface上

### ISSUE THREAD

**Issue by MiniLight** [wangyu-/udp2raw-tunnel#148]
我的主机上有eth0和eth1两个interface，其中eth0是默认路由，使用eth0时一切是正常的。
当我启动一个服务端并从客户端连接到eth1的IP地址时，服务端持续出现提示：
> received syn,sent syn ack back
> received syn,sent syn ack back
> received syn,sent syn ack back
而客户端一侧是持续的：
> (re)sent tcp syn
> (re)sent tcp syn
> (re)sent tcp syn

即使将服务端的-s参数bind至eth1的IP地址时也是如此。

**Comment by wangyu-** [comment]
我自己搭了个双ip的环境测试了一下，不管是bind到0.0.0.0还是第二个ip(非默认)，都可以正常用第二个ip访问。不需要`--lower-level`。  如果是bind到0.0.0.0，两个ip都可以正常访问。

我估计是你自己的iptables有问题，跟udp2raw冲突了，清空iptables重试一下。

**Comment by wangyu-** [comment]
https://github.com/wangyu-/tinyfecVPN/wiki/清空iptables的方法

**Comment by MiniLight** [comment]
抱歉，刚刚测试了一下，似乎是我的VPS存在一些网络配置上的问题。
