### ISSUE TITLE
如何设置指定ip能够访问udp2raw的端口

### ISSUE THREAD

**Issue by chnt7305** [wangyu-/udp2raw-tunnel#149]
我在 iptables 里设置了指定ip访问端口，但是好像不生效 。用 iptables -L 查看，udp2raw的规则是排在第一个的 source 是 anywhere 我自己加的排在后面没有生效。

**Comment by wangyu-** [comment]
你标题和内容里说的是两个问题，两者之间没有必然联系。

如果你的目的只是让udp2raw添加的规则排在后面，你只要去掉`-a`选项，看一下`-g`，自己手动管理iptables。

如果你想达到标题里的目的 `如何设置指定ip能够访问udp2raw的端口`，看一下这个issue：

https://github.com/wangyu-/udp2raw-tunnel/issues/40

**Comment by chnt7305** [comment]
@wangyu- 【在iptables的output链里把到 发送 屏蔽掉 】这句话看不懂。
