### ISSUE TITLE
AES with hardware acceleration on 64-bit platforms

### ISSUE THREAD

**Issue by linusyang** [wangyu-/udp2raw-tunnel#15]
It seems the AES crypto library used in this project (i.e. [tiny-AES-c](https://github.com/kokke/tiny-AES-c)) lacks support of hardware acceleration, while mainstream crypto libraries (e.g. OpenSSL, mbedTLS) support.

I have created a [fork](https://github.com/linusyang/udp2raw-tunnel/tree/aes) with hardware-accelerated AES crypto on x86_64 and arm64. The assembly code is basically taken from PolarSSL/mbedTLS. The code passed the [original test](https://github.com/kokke/tiny-AES-c/blob/master/test.c) in tiny-AES-c. And I have preliminarily tested the udp2raw binary which seems to work. But I didn't do more test or benchmarks.

I also made a [fork](https://github.com/linusyang/udp2raw-tunnel/tree/docker) to automatically build static binaries using Docker. The binaries are linked against Musl Libc which is smaller and more portable than Glibc. The prebuilt binaries are available [here](https://github.com/linusyang/udp2raw-tunnel/releases).

-------------------

懒人版：貌似现在用的AES加密库没有硬件加速，我从mbedTLS抄了点汇编代码，可以在64位Intel和ARM上硬件加速。初步测试是可用的，不知道有没有兴趣合并？

**Comment by wangyu-** [comment]
Hi,linusyang:

Great work.

> It seems the AES crypto library used in this project (i.e. tiny-AES-c) lacks support of hardware acceleration, while mainstream crypto libraries (e.g. OpenSSL, mbedTLS) support.

Yes,for simpler complication,i didnt choose to link to a mainstream crypto libraries.For longer term,this project might support both tiny-AES-c and PolarSSL at same time.

I can merge this after you've  done the benchmark.

I think its better if we leave the tiny-AES-c untouched and create a seperate source and header for hardware-accelerated AES. And make a switch at higher level at cipher_encrypt() & cipher_decrypt() in encrypt.cpp. We can discuss about this later.

By the way, is there a way of hardware-acceleration on 32bit arm?It suffers more from performance issue.

**Comment by linusyang** [comment]
I did some preliminary benchmarks using iperf3.

* Results:
  - Original version:

        Connecting to host 192.168.27.1, port 5201
        [  4] local 192.168.27.2 port 58472 connected to 192.168.27.1 port 5201
        [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
        [  4]   0.00-1.00   sec  3.88 MBytes  32.6 Mbits/sec    6   62.6 KBytes
        [  4]   1.00-2.00   sec  3.67 MBytes  30.8 Mbits/sec    8   37.6 KBytes
        [  4]   2.00-3.00   sec  3.67 MBytes  30.8 Mbits/sec   10   47.6 KBytes
        [  4]   3.00-4.00   sec  3.67 MBytes  30.8 Mbits/sec    2   63.9 KBytes
        [  4]   4.00-5.00   sec  3.73 MBytes  31.3 Mbits/sec    6   41.3 KBytes
        [  4]   5.00-6.00   sec  3.61 MBytes  30.3 Mbits/sec   14   27.6 KBytes
        [  4]   6.00-7.00   sec  3.79 MBytes  31.8 Mbits/sec    8   30.1 KBytes
        [  4]   7.00-8.00   sec  3.85 MBytes  32.3 Mbits/sec    6   47.6 KBytes
        [  4]   8.00-9.00   sec  3.79 MBytes  31.8 Mbits/sec    4   60.1 KBytes
        [  4]   9.00-10.00  sec  3.85 MBytes  32.3 Mbits/sec   12   37.6 KBytes
        - - - - - - - - - - - - - - - - - - - - - - - - -
        [ ID] Interval           Transfer     Bandwidth       Retr
        [  4]   0.00-10.00  sec  37.5 MBytes  31.5 Mbits/sec   76             sender
        [  4]   0.00-10.00  sec  37.3 MBytes  31.3 Mbits/sec                  receiver

  - AES accelerated:

        Connecting to host 192.168.27.1, port 5201
        [  4] local 192.168.27.2 port 58476 connected to 192.168.27.1 port 5201
        [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
        [  4]   0.00-1.00   sec  14.3 MBytes   120 Mbits/sec   22   31.3 KBytes
        [  4]   1.00-2.00   sec  14.5 MBytes   122 Mbits/sec   40   37.6 KBytes
        [  4]   2.00-3.00   sec  14.6 MBytes   122 Mbits/sec   46   28.8 KBytes
        [  4]   3.00-4.00   sec  14.4 MBytes   121 Mbits/sec   40   50.1 KBytes
        [  4]   4.00-5.00   sec  14.7 MBytes   124 Mbits/sec   54   26.3 KBytes
        [  4]   5.00-6.00   sec  14.9 MBytes   125 Mbits/sec   38   38.8 KBytes
        [  4]   6.00-7.00   sec  15.8 MBytes   133 Mbits/sec   54   52.6 KBytes
        [  4]   7.00-8.00   sec  16.2 MBytes   136 Mbits/sec   46   43.9 KBytes
        [  4]   8.00-9.00   sec  16.2 MBytes   136 Mbits/sec   52   57.6 KBytes
        [  4]   9.00-10.00  sec  16.5 MBytes   139 Mbits/sec   50   27.6 KBytes
        - - - - - - - - - - - - - - - - - - - - - - - - -
        [ ID] Interval           Transfer     Bandwidth       Retr
        [  4]   0.00-10.00  sec   152 MBytes   128 Mbits/sec  442             sender
        [  4]   0.00-10.00  sec   152 MBytes   127 Mbits/sec                  receiver

        iperf Done.

* Settings: 
  - Server: Celeron N3150, Atom based low-end x64 CPU with AES-NI
  - Client: Core i5 3570, Hyper-V on Windows 10, locally connected to server
  - udp2raw: prebuilt binaries from current master (`orig`) and my fork (`aes`)

        ./udp2raw -s -l0.0.0.0:10087 -r 127.0.0.1:10086 -k "passwd" --raw-mode faketcp -a
        ./udp2raw -c -r192.168.25.1:10087 -l0.0.0.0:10088 --raw-mode faketcp -a -k"passwd"

  - Upper connection: openvpn p2p mode without encryption, e.g., the server configuration is

        port 10086
        dev tun
        proto udp
        ifconfig 192.168.27.1 192.168.27.2
        persist-key
        persist-tun
        keepalive 10 30
        cipher none
        verb 2

**Comment by linusyang** [comment]
The patch I made could seamlessly integrate with tiny-aes-c. Just like mbedTLS/PolarSSL, the code will automatically detect at **both** compile time and runtime if the platform is supported for AES acceleration, in case that some Atom x64 platform doesn't support AES-NI. We may *need to* modify the original tiny-aes-c code because ARM64 doesn't have AES key expansion instructions in AES-NI and uses the C version.

For 32-bit ARM platforms, there is no general native AES instructions, but some devices may contain specific AES module for acceleration, e.g., iPhone (iOS CommonCrypto API) and [Broadcom devices](https://wiki.openwrt.org/doc/hardware/cryptographic.hardware.accelerators). Thus, there is no general solutions for accelerating 32-bit ARM devices.

**Comment by wangyu-** [comment]
Hi,linusyang:
Looks awesome. This can significantly solve the peformance issue on a BandwagonHost with limited CPU resource rate.

>The patch I made could seamlessly integrate with tiny-aes-c. 

Yes,I read the patch and I know that.Actually I was worrying about stability issue and want to keep an original version of tiny-aes-c.

I will add a dir named aes_hardware_accelate in lib.And add two new target named udp2raw_amd64_aes_ni  udp2raw_arm64_aes_ni.The exisinting targets will link to the original tiny-AES,the new targets will link to your modified version.

Do you think this soultion satisfactory?

**Comment by wangyu-** [comment]
Could the arm64 accelation be enabled on a device with a 64bit cpu but a 32bit system?For example the latest raspberrypi 3b has a armv8 cpu,but there is no official 64bit system.

**Comment by linusyang** [comment]
I agree with that tiny-aes-c should remain untouched which simplifies tracking the upstream code. Let me refactor another version according to your suggestions. Sit tight. :)

**Comment by linusyang** [comment]
I don't have an RPi3.  But I think you need at least a 64-bit kernel to run 64-bit programs. A 32-bit kernel is not compatible.

**Comment by wangyu-** [comment]
>But I think you need at least a 64-bit kernel to run 64-bit programs.
Yes.I was wondering if those AES intruction can be enable on 32bit mode.

**Comment by linusyang** [comment]
It might not be possible to do so. 64-bit mode is required to run AES instructions, which can only be enabled by 64-bit kernel. Someone even said there is [no AES instruction support](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=141566) at all in RPi3.

I have refactored the extra code into `aesacc.h/.c` with original tiny-aes-c unmodified. `aesacc.h` exposes wrapper functions `AESACC_*` which first check if AES acceleration is supported. If not, original tiny-aes-c functions will be called. I also changed `encrypt.cpp` to by default invoke `AESACC_` functions instead of original `AES_` functions.

**Comment by linusyang** [comment]
Since there are many 32-bit platforms lack hardware acceleration, I am wondering if using OpenSSL's optimized assembly version of AES could improve some performance. I have ported the assembly code and now try to do some benchmarks.

**Comment by wangyu-** [comment]
@linusyang  I see.The main purpose of linking to OpenSSL was indeed improving peformance.If its proved that the OpenSSL 's wont be better on those platforms,maybe we dont need to use it at all.

**Comment by linusyang** [comment]
Some results:
Original:
  * x86: 22.2 Mbits/sec
  * x64: 31.3 Mbits/sec

Accelerated:
  * x86 asm: 73.0 Mbits/sec
  * x64 AES-NI: 128 Mbits/sec

**Comment by wangyu-** [comment]
>aesacc.h exposes wrapper functions AESACC_* which first check if AES acceleration is supported. If not, original tiny-aes-c functions will be called

Maybe  its not necessary to have new function names. You can just use the original names in tiny-aes.Because only udp2raw_amd64_aes_ni udp2raw_arm64_aes_ni  will link to the modified version.

====
我觉得接口沿用tiny aes的就可以了。这个修改版作为tiny-aes的替代，如果编译时一个target连接了你这个版本，就不链接原版了。同理，链接了原版的target就不链接这个新版了。刚开始我是想在encrypt层面做开关，后来又想到在makefile层面做，觉得更简单些。

你可以直接提现有的版本，然后我再改一改给你看，你再看看是否满意。

**Comment by linusyang** [comment]
Just pushed the new commit. The assembly code is not enabled by default. One needs to add `-DHAVE_ASM` macro to activate it. See [this file](https://github.com/linusyang/udp2raw-tunnel/blob/docker/makefile.docker) for example. I have tested x86 and arm32 assembly code which works well. The mips code will be later tested using QEMU.

**Comment by linusyang** [comment]
> 链接了原版的target就不链接这个新版了

可以的，我觉得可以按这个顺序选：硬件加速-汇编加速-C版本。感觉代码还要好好测试，毕竟是东拼西凑抄过来的代码，我只测了tiny-aes里面的例子(128,192,256位都测了)。

**Comment by wangyu-** [comment]
@linusyang  我已经merge了。测试了arm32汇编加速版，效果非常好。在树莓派3b上，本来速度只有15 16mb，cpu就占用到100%了。现在跑满20m带宽只要70%cpu。

**Comment by wangyu-** [comment]
@linusyang 我在你原来的代码基础上做了一点重构。现在加速版和原版tiny-aes的接口完全一样，共用一个aes.h。然后把所有新加的文件移动到了lib/aes_acc。你看一看这样满意不？

另外，cmake那个makelist不用改，那个只是为了方便用cmake的人自己编译和兼容用CMAKE的ide,编译release版时不用那个。我给改回去了。

**Comment by wangyu-** [comment]
mips版的我也测试了一下，连接不上。client是mips加速版的，server那边解密之后显示md5验证失败了。
相同传参数的原版client正常。 这个mips版的是big endian的还是little endian的？

**Comment by linusyang** [comment]
@wangyu- 很赞！我也就是搬运下openssl的代码，没什么贡献，主要是编译起来方便。其实加速版现在可以不依赖tiny-aes了，如果平台不支持干脆直接报编译错误，这样就可以把acc文件夹里的tiny-aes依赖去掉。mips的我在qemu里也测过了，但是我之前上传的只有小端(little-endian)的汇编，我等下补一个大端的。

**Comment by wangyu-** [comment]
@linusyang 不要谦虚啦，这个交给我想搬也搬不过来。之前就觉得这个tiny-aes性能不好，但是除了用openssl之外又无计可施，依赖openssl编译起来又很麻烦，很是纠结，现在总算解决了问题。

>其实加速版现在可以不依赖tiny-aes了，如果平台不支持干脆直接报编译错误

这样也不错。

>但是我之前上传的只有小端(little-endian)的汇编

我的路由器是大端的。原来如此。

**Comment by wangyu-** [comment]
@linusyang 

> 我只测了tiny-aes里面的例子(128,192,256位都测了)。

这个说的是amd64版还是全部？x86/arm/mips汇编版的支持192和256吗？

**Comment by baggiogogo** [comment]
树2可以用udp2raw_arm_asm_aes这个吗？还是沿用2708?

**Comment by wangyu-** [comment]
@baggiogogo  应该是可以的。试一下吧，能正常连上就可以用。

**Comment by baggiogogo** [comment]
好的，我试了下是可以运行的，晚点测试效果。

**Comment by baggiogogo** [comment]
过来反馈，正常kcptun，y2b 19000-20000之间，我这环境很稳定，八九不离十。
关闭kcptun加密，参数不变，套以前的udp2raw，性能损失很大，11000-12000之间。刚测raw_arm_asm_aes，算质的飞跃了，这点损失可以忽略不计了，很赞。
![default](https://user-images.githubusercontent.com/21306212/29466846-e76401fc-8470-11e7-8a03-24f9c73c473b.JPG)

**Comment by wangyu-** [comment]
@baggiogogo  确实非常赞。以前我在PI上都不敢开AES，一直用XOR，现在AES无压力了。

**Comment by baggiogogo** [comment]
感谢啦，过会我准备再套上obfs试试。

**Comment by linusyang** [comment]
> 这个说的是amd64版还是全部？x86/arm/mips汇编版的支持192和256吗？

全部，所有支持的平台都测过，加参数`-DAES192`或`-DAES256`即可开启。MIPS我只测试了大端的(mips)， 常见的ar71xx是大端。小端的(mipsel)应该也一样，不方便就没有测试了。

我新开的pr里面把tiny-aes全部去掉了，只有汇编，现在要链接这个库，所有平台都必须添加汇编文件，编译参数可以参考[这里](https://github.com/linusyang/udp2raw-tunnel/blob/a851f1d2372598eeda192f1bf316f25e42ae985e/makefile.docker)。

**Comment by wangyu-** [comment]
@linusyang 

已merge最新的pr，我在PR里发了mips_be版的性能测试，效果 <del>明显</del> 拔群。

**Comment by linusyang** [comment]
看来OpenSSL的性能确实高啊，以后还是少用mbedTLS了😆
我又稍微改了点代码，把加解密分开了，以前用的PolarSSL的代码是合并的，现在没必要了。

**Comment by linusyang** [comment]
话说有没有兴趣用Musl Libc交叉编译其他平台的？貌似是现在LEDE/Openwrt默认的工具链了，[用docker编译](https://github.com/linusyang/udp2raw-tunnel/commit/a851f1d2372598eeda192f1bf316f25e42ae985e)还是很方便的。

**Comment by wangyu-** [comment]
已merge。

>话说有没有兴趣用Musl Libc交叉编译其他平台的？貌似是现在LEDE/Openwrt默认的工具链了，用docker编译还是很方便的。

这个docker的编译环境怎么搭建，能简单说一下吗？我试用一下，如果确实更方便，就换到这个。

**Comment by linusyang** [comment]
其实就是用[musl-gcc交叉编译器](https://github.com/richfelker/musl-cross-make)编译，用docker比较省事，直接`docker pull`网上别人预先编译好的，加一个[dockerfile](https://github.com/linusyang/udp2raw-tunnel/blob/a851f1d2372598eeda192f1bf316f25e42ae985e/Dockerfile)就能用了。

另外我测试了一下md5.c的速度，跟polarssl的c版本比，速度只有67%。polarssl C语言的实现已经很快了，有openssl的汇编优化90%的速度。我还是放在acc文件夹里面，不改动原来的实现，有兴趣的话我可以提交一个pr。

**Comment by wangyu-** [comment]
那个md5因为我没找到好的，才随便用了一个。可以删掉原来的，用新的。

另外有sha1的吗？我当时也没找到sha1就用md5凑合了。如果有的话，你可以把sha1的c push上来，然后我来实现上层(encrypt.cpp)的wrapper。如果你有兴趣你自己做上层的wrapper也可以。

>网上别人预先编译好的

这个docker里面自带了各种交叉编译器是吗？有链接吗。

**Comment by linusyang** [comment]
> 如果sha1的提取出来很麻烦就不用搞了，多加个auth mode其实也没什么用。

不麻烦，还是从PolarSSL里面拉出来就行了，一个[单独的C文件](https://github.com/linusyang/udp2raw-tunnel/blob/hash/lib/sha1.c)，如有需要可以自取，PR只更新了md5。

找的这个docker自带[各种musl的编译器](https://github.com/privatelo/cross-multi)，但是没有openwrt的，这个可以在docker hub上找找，比如[这个](https://hub.docker.com/r/yhnw/openwrt-sdk/)([Github链接](https://github.com/hnw/docker-openwrt-sdk))带ar71xx的，tag是`15.05.1-ar71xx`。

**Comment by wangyu-** [comment]
> 不麻烦，还是从PolarSSL里面拉出来就行了，一个单独的C文件，如有需要可以自取，PR只更新了md5。
多谢，已经拉过来了。

**Comment by wangyu-** [comment]
@linusyang 这两天我一直在想办法实现几个新功能，比如那个--lower-level怎么做成自动化的。docker的还没看(因为这个只影响编译，不影响用户用，所以就先解决别的问题去了= =)。 我这两天试用一下，反馈给你。

**Comment by linusyang** [comment]
@wangyu- 我另开了一个repo，用docker自动化交叉编译：https://github.com/linusyang/udp2raw-docker ，内含[简单的脚本](https://github.com/linusyang/udp2raw-docker/tree/master/openwrt-ar71xx)配置成openwrt服务，方便路由器上自动启动，配置文件放在`/etc/udp2raw.conf`，可以实现 #30 大部分功能，只是密码无法隐藏。

**Comment by wangyu-** [comment]
@linusyang  
我试用了https://github.com/linusyang/udp2raw-docker ，感觉不错，编译多个版本很方便，跟原来的makefile比各有优势吧，可以互相补充。原的makefile在编译一个版本时，只要下载个toolchain就可以了（找toolchain应该比找别人包好的docker要容易），也不用装docker。

你打算以后就在这个repo上开发了，还是merge进来？我觉得都可以。

如果merge进来的话，可以新建个docker文件夹放docker相关的文件。然后把旧的makefile精简一下，只留最基本的功能(make 和make cross)，编译release版以后就用docker。

> 话说有没有兴趣用Musl Libc交叉编译其他平台的？貌似是现在LEDE/Openwrt默认的工具链了，用docker编译还是很方便的。

用这个musl libc替代标准libc是出于什么考虑的？从编译出的文件大小上貌似也没看出什么优势。是因为用musl libc的交叉编译docker好找吗？ 我觉得用它也没问题，只要稳定就行。

>I also made a fork to automatically build static binaries using Docker. The binaries are linked against Musl Libc which is smaller and more portable than Glibc. The prebuilt binaries are available here.

新的repo看起来是这个原来的fork的加强版吧。所以我直接用你的新的repo测试的，旧的repo就没有试了。


我把你加到Collaborators里了，如果想merge进来你可以直接在原分支上提交。

**Comment by linusyang** [comment]
> 原的makefile的优势是，在编译一个版本时，只要下载个toolchain就可以了（找toolchain应该比找别人包好的docker要容易），也不用装docker。
Docker本质也是下载toolchain，也是编译好的，而且[有编译的过程](https://github.com/privatelo/cross-multi/blob/master/Dockerfile)，如果要加新的架构还可以自行编译。

> 你打算以后就在这个repo上开发了，还是merge进来？我觉得都可以。
我觉得可以merge进来，用docker编译是比较独立的，可以放在单独目录里面。我整合一下代码，发一个pr给你看看？

> 我把你加到Collaborators里了，有改动可以直接在原分支上提交。
多谢！我还是继续提交PR，这样审核一下再合并会比较好。

> 用这个musl libc替代标准libc是出于什么考虑的？
Musl Libc比glibc其实更符合标准，更适合静态链接，glibc没办法完全静态，比如dns resolver会依赖libnss，具体的比较可以看[这里](http://www.etalabs.net/compare_libcs.html)。

> #30 实现起来很简单，所以我觉得，就在程序里实现了它吧。这样就不需要用脚本parse conf文件了。
可以的，我写的脚本很简单，本质还是调用命令行参数，不依赖这个补丁。

**Comment by wangyu-** [comment]
> Docker本质也是下载toolchain，也是编译好的，而且有编译的过程，如果要加新的架构还可以自行编译

是的，我学了一下docker，现在能看明白你的代码了。我的意思是说，有的人可能下载代码只是为了编译一个target，他可能不愿意为了编译一个target装个docker（如果用的是老的linux发行版，可能还装不上，内核要求3.10才能装，我之前就是这样= =，新装了个debian9才搞定。），所以原来的makefile最好留着。

>我觉得可以merge进来，用docker编译是比较独立的，可以放在单独目录里面。我整合一下代码，发一个pr给你看看？

好。

> 多谢！我还是继续提交PR，这样审核一下再合并会比较好。
docker文件夹里的直接提交就行。docker文件夹以外的如果你觉得问题不大也直接提交，如果需要讨论一下就发PR。

> Musl Libc比glibc其实更符合标准，更适合静态链接，glibc没办法完全静态，比如dns resolver会依赖libnss，具体的比较可以看这里。

了解了，可以用这个。001-musl-headers.patch可以直接在main.cpp上改，免去打patch这一步。

不过我有点担心，一般别人交叉编译，他默认链接到的是glibc。而我们发布release用了这个musl libc。会不会因为musl和glibc有什么差异，导致我们编译出来的binary没问题，而别人自己编译出来的binary有问题。这样就比较尴尬了，可能会有bug我们一直意识不到。你觉得这个值得担心吗？

**Comment by wangyu-** [comment]
>我把你加到Collaborators里了，有改动可以直接在原分支上提交。

我这边已经加你了，貌似你那边还得点一下这个链接：
https://github.com/wangyu-/udp2raw-tunnel/invitations

**Comment by linusyang** [comment]
> 所以原来的makefile最好留着。

docker编译的部分是独立的，跟原来的不冲突。

> 001-musl-headers.patch可以直接在main.cpp上改，免去打patch这一步。

好的，我等下放到pr里面。

> 而我们发布release用了这个musl libc。会不会因为musl和glibc有什么差异，导致我们编译出来的binary没问题，而别人自己编译出来的binary有问题。

musl兼容性很好，而且openwrt最新用的就是musl。纯静态编译用glibc其实并不好，glibc支持得并不好，还是会依赖其他库，会有版本问题，应该用动态链接。我这个反正编译出来的musl只是方便自用，如果你担心兼容性问题，那还是release glibc的版本好了。

**Comment by wangyu-** [comment]
> docker编译的部分是独立的，跟原来的不冲突。

是的。但是得维护两套makefile，加上cmake有3套了，感觉有点麻烦，又不得不留着。

>纯静态编译用glibc其实并不好，glibc支持得并不好，还是会依赖其他库，会有版本问题，应该用动态链接

好，既然glibc本身就可能有问题，那就换到musl吧。

**Comment by wangyu-** [comment]
@linusyang 

你之前的代码我改了一点，做了点小优化。改动在： https://github.com/wangyu-/udp2raw-tunnel/commit/0de85dd736668cf7a1b930c9e74fed0b45e5b1b4 和https://github.com/wangyu-/udp2raw-tunnel/commit/661b329930bc6deb2df27636fe445b83f9ecfe86。

第一个优化是，md5函数不每次调用md5_init( &ctx );

第二个是，对AES，如果传入的key是NULL，那就不调用aes_setkey_enc(&ctx,key,AES_KEYSIZE);，不做key expansion,而是沿用上次的key。

我测试了大部分平台，都没问题。你能看一下的话最好了。

==其他==
另外，我从polarSSL里面扒出来了一个aes实现，比tiny aes快不少（当然还是没有加速版的快），现在我把tiny aes基本彻底换掉了。接口还是tiny aes的，实现已经换掉了。

docker暂时需求不强烈，我已经把所有常用的平台的toolchain都找全了，基本涵盖你那个docker image里的所有target，docker做不做都可以。

**Comment by 20083017** [comment]
@linusyang @wangyu
咨询个问题  aes-gcm-256 有armv7的汇编优化吗~
