### ISSUE TITLE
[Feature request] Security/crypto overhaul

### ISSUE THREAD

**Issue by StevenDoesStuffs** [wangyu-/udp2raw-tunnel#153]
Hello! I’d be great if this program supported more crypto such as different ciphers, different hashes, authenticated encryption, key exchange, and identity verification. For users looking to secure their udp connection, this would be great. I’d be willing to work on this issue if you’d consider linking OpenSSL. Currently, the most secure option available in the program is AES128-CBC + MD5. There are a few issues with this. MD5 is generally considered insecure within the crypto community; CBC is slower and less secure than GCM, and support for ChaCha20-Poly1305 would make everything quite a bit faster, especially for low powered devices without support for hardware AES.

**Comment by wangyu-** [comment]
>Currently, the most secure option available in the program is AES128-CBC + MD5. There are a few issues with this. MD5 is generally considered insecure within the crypto community.

Yes, there exists a few issues with `AES128-CBC + MD5`, there are some TODO in encrypt.cpp to support HMAC/AE/AEAD.  I just dont have enough time to implement it recently.

>support for ChaCha20-Poly1305 would make everything quite a bit faster, especially for low powered devices without support for hardware AES.

Agree.

>I’d be willing to work on this issue if you’d consider linking OpenSSL

The reason why I chose not to link OpenSSL was to make the project easy to compile(and yes, it cause many inconvenience). 

Can you make linking OpenSSL as an option? That is, support both linking to OpenSSL  and not linking to OpenSSL.  Will this make the work a lot harder?  We can discuss about this.

**Comment by StevenDoesStuffs** [comment]
Of course openssl can be optional, although those who choose to compile without it will have to use the old ciphers. Imma start working on this now. Thanks for the prompt reply!

**Comment by StevenDoesStuffs** [comment]
One more question. It looks like you already have mbedtls, so I'll probably just use that, but do you want to keep tiny-aes? Things will be much simpler without it. Also, would it be okay to use mbedtls as a static library? It should support all platforms.

**Comment by StevenDoesStuffs** [comment]
@wangyu- One more question. It looks like you already have mbedtls, so I'll probably just use that, but do you want to keep tiny-aes? Things will be much simpler without it. Also, would it be okay to use mbedtls as a static library? It should support all platforms.

**Comment by wangyu-** [comment]
>One more question. It looks like you already have mbedtls, so I'll probably just use that, but do you want to keep tiny-aes? Things will be much simpler without it. Also, would it be okay to use mbedtls as a static library? It should support all platforms.

We dont have full mbedtls. There are just a few files from mbedtls/polarssl.  Tiny-aes is no longer really used now. The first version of udp2raw uses tiny-aes, but its too slow, so we changed the implementation to mbedtls(not full mbedtls, just a few files from it). 

So, at the moment, we still use the `lib/aes.h` from tiny-aes, but `lib/aes.c` (tiny-aes' implementation) is no longer linked, instead we link `lib/aes_faster_c/aes.c` from mbedtls with a wrapper `lib/aes_faster_c/wrapper.c`.

>Update: I've automated the building of mbedtls as a static library. Building is not longer too complex. Is it still neccecary for it to be optional? Also, because the makefile actually builds mbedtls, no installation of anything additional is needed.

Can you post a demo? Will it work for cross-compile?

**Comment by wangyu-** [comment]
>Currently, the most secure option available in the program is AES128-CBC + MD5.

Hmac-sha1 is supported now. For anyone who worry about the security of AES+md5(hash-under-encrytion scheme) can switch to AES+hmac-sha1(encrpt-then-hmac shceme).

>support for ChaCha20-Poly1305 would make everything quite a bit faster, especially for low powered devices without support for hardware AES.

use this work around for low performance device:  disable encryption/use weak encryption in udp2raw, and resort to encrytion at higher level

**Comment by wangyu-** [comment]
This issue is closed due to inactivity.  I have no plan to implement it (link to openssl/mbedtls and support more cipher and hashs), I also currently have no plan to merge/review pull request of related feature. If anyone is interested in sending a pull request, talk with me before writing the code.
