### ISSUE TITLE
直接使用udp2raw，套用openvpn的UDP模式，连上后一会自动断开

### ISSUE THREAD

**Issue by milebye** [wangyu-/udp2raw-tunnel#157]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)
之前没有加您udpspeeder上的5个参数，直接连不上。
双方都加上后，连上后不久自动断开。
显示：event_wait : Interrupted system call (code=4)
google 了一下，好像说是自己手动停止断开，但实际是自动断开...

有人这样成功过吗？  能否给些帮助？
默认的openvpn配置文件是直接导出梅林的openvpn配置，只在后面加了5个参数。

**Comment by milebye** [comment]
好像无关... 发现直连效果也是一样。。。

**Comment by DustinWin** [comment]
我也遇到过，不知道怎么解决。
