### ISSUE TITLE
编译出错...

### ISSUE THREAD

**Issue by wxlg1117** [wangyu-/udp2raw-tunnel#161]
amd64平台centos 7 编译出错了,大神们知道是需要安装哪些库么?

root@vultr udp2raw-tunnel]# make
echo "const char *gitversion = \"2c2d897bc2140dbe77cea99f92942425632088e6\";" > git_version.h
rm -f udp2raw
g++   -o udp2raw          -I. main.cpp lib/md5.c encrypt.cpp log.cpp network.cpp common.cpp  connection.cpp misc.cpp fd_manager.cpp -lpthread lib/aes_faster_c/aes.c lib/aes_faster_c/wrapper.c -std=c++11 -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers -lrt -ggdb -static -O3
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

**Comment by wangyu-** [comment]
https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/build_guide.md

**Comment by wxlg1117** [comment]
yum groupinstall 'Development Tools'有安装全套的,然后还缺...

最后换成ubuntu 14编译可以了.

**Comment by wxlg1117** [comment]
无意间坚决了, 还是缺少库:
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

yum install glibc-static


/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
yum install libstdc++-static

**Comment by iugo** [comment]
错误提示对我这种不会写 C++ 的, 很难懂.

找到一些参考 https://stackoverflow.com/questions/44275897/no-package-glibc-static-available 但是作用不够大.

CentOS 7 测试 `glibc-static` 与 `libstdc++-static` 足够解决问题了.
