### ISSUE TITLE
[咨询]中转串联udp2raw

### ISSUE THREAD

**Issue by neighbor007** [wangyu-/udp2raw-tunnel#167]
首先，说一下环境，以及目的
环境：a（本地）-----b（国内中转[与c之间部署udp2raw])------海外vps[ssr+udp2raw]
目的：主要用来加速游戏，国内放个中转 1是为了方便不需要手动分离ssr-redir，2是提升链路稳定性。
问题：想问一下这种方法，nat穿透会不会有问题，是不是 无法支持p2p类型的链接；如果不可行，我在a和b再加一个udp2raw 是不是能解决nat穿透问题。

打扰了，望能回复给一些建议，谢谢。

For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

**Comment by wangyu-** [comment]
>问题：想问一下这种方法，nat穿透会不会有问题，是不是 无法支持p2p类型的链接；如果不可行，我在a和b再加一个udp2raw 是不是能解决nat穿透问题。

p2p能不能支持取决于$$本身。  不论加不加udp2raw 和UDPspeeder都不会有区别。 

openvpn+udp2raw+UDPspeeder p2p没问题，电驴是highid，用软件测出来是full cone NAT。 

$$据一些玩家反馈，是支持p2p的。 但是曾经有版本的$$有bug，p2p不能正常工作，后来修了:

https://github.com/shadowsocks/shadowsocks-libev/issues/1883

还有一点要注意的是，不要用$$的`--reuse-port`和`--workers`选项，可能会使你的nat类型变差。

**Comment by neighbor007** [comment]
我在中间加了一个中转服务器也不会对nat穿透造成影响是嘛

**Comment by wangyu-** [comment]
不会。 不管是udp2raw和udpspeeder部署在本机，还是中转服务器上，没有影响。

**Comment by neighbor007** [comment]
多谢指点。
