### ISSUE TITLE
openvpn串联udp2raw 网络吞吐量低 

### ISSUE THREAD

**Issue by jason2000915** [wangyu-/udp2raw-tunnel#172]
#10 和这位的问题比较像
客户端100Mb电信光纤 服务器vultr 5刀版美国
但下载速度只有最快3MB/s 下载时客户端CPU占用14% 服务端占用60%

用了某交通工具下载速度能达到10MB/S
scp直连下载也有7MB/s
是openvpn协议的问题吗

客户端为linux虚拟机和windows7
中转客户端为linux虚拟机
虚拟机使用VirtualBox 桥接

客户端 服务器 iptables皆设为允许并清空
仅有服务器端加上-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

google了各种方式都解决不了 实在没办法了 来发个issue

 - - - - - - - - - - - - - - - - - - - - - - - - -
# iperf3.5测试结果
# TCP

`[root@localhost ~]# iperf3 -c 10.8.0.1 -p 2010 -b 0
Connecting to host 10.8.0.1, port 2010
[  5] local 10.8.0.6 port 49076 connected to 10.8.0.1 port 2010
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   689 KBytes  5.65 Mbits/sec    1    130 KBytes       
[  5]   1.00-2.00   sec  2.52 MBytes  21.1 Mbits/sec  136    799 KBytes       
[  5]   2.00-3.00   sec  2.42 MBytes  20.3 Mbits/sec  605    650 KBytes       
[  5]   3.00-4.00   sec  1.14 MBytes  9.60 Mbits/sec    1    782 KBytes       
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec  269    782 KBytes       
[  5]   5.00-6.00   sec  2.50 MBytes  21.0 Mbits/sec    3    674 KBytes       
[  5]   6.00-7.00   sec  1.18 MBytes  9.93 Mbits/sec  420    701 KBytes       
[  5]   7.00-8.00   sec  2.46 MBytes  20.6 Mbits/sec  126    699 KBytes       
[  5]   8.00-9.00   sec  1.25 MBytes  10.5 Mbits/sec  298    780 KBytes       
[  5]   9.00-10.00  sec  1.25 MBytes  10.5 Mbits/sec  146    690 KBytes       

[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  15.4 MBytes  12.9 Mbits/sec  2005             sender
[  5]   0.00-10.71  sec  13.7 MBytes  10.8 Mbits/sec                  receiver`

Accepted connection from 10.8.0.6, port 49074
[  5] local 10.8.0.1 port 2010 connected to 10.8.0.6 port 49076
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   131 KBytes  1.07 Mbits/sec                  
[  5]   1.00-2.00   sec  1.07 MBytes  8.95 Mbits/sec                  
[  5]   2.00-3.00   sec  1.67 MBytes  14.0 Mbits/sec                  
[  5]   3.00-4.00   sec  1.50 MBytes  12.6 Mbits/sec                  
[  5]   4.00-5.00   sec   119 KBytes   977 Kbits/sec                  
[  5]   5.00-6.00   sec  2.75 MBytes  23.1 Mbits/sec                  
[  5]   6.00-7.00   sec  1.02 MBytes  8.58 Mbits/sec                  
[  5]   7.00-8.00   sec  1.57 MBytes  13.1 Mbits/sec                  
[  5]   8.00-9.00   sec  2.12 MBytes  17.8 Mbits/sec                  
[  5]   9.00-10.00  sec  1.48 MBytes  12.4 Mbits/sec                  
[  5]  10.00-10.71  sec   312 KBytes  3.62 Mbits/sec                  

[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.71  sec  13.7 MBytes  10.8 Mbits/sec

# UDP

[root@localhost ~]# iperf3 -c 10.8.0.1 -p 2010 -b 100M -u
Connecting to host 10.8.0.1, port 2010
[  5] local 10.8.0.6 port 58454 connected to 10.8.0.1 port 2010
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec  11.9 MBytes  99.9 Mbits/sec  11448  
[  5]   1.00-2.00   sec  11.9 MBytes   100 Mbits/sec  11457  
[  5]   2.00-3.00   sec  11.9 MBytes   100 Mbits/sec  11459  
[  5]   3.00-4.00   sec  11.9 MBytes   100 Mbits/sec  11456  
[  5]   4.00-5.00   sec  11.9 MBytes   100 Mbits/sec  11457  
[  5]   5.00-6.00   sec  11.9 MBytes   100 Mbits/sec  11464  
[  5]   6.00-7.00   sec  11.9 MBytes   100 Mbits/sec  11452  
[  5]   7.00-8.00   sec  11.9 MBytes   100 Mbits/sec  11457  
[  5]   8.00-9.00   sec  11.9 MBytes   100 Mbits/sec  11457  
[  5]   9.00-10.00  sec  11.9 MBytes   100 Mbits/sec  11457  
 
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-10.00  sec   119 MBytes   100 Mbits/sec  0.000 ms  0/114564 (0%)  sender
[  5]   0.00-10.75  sec  5.37 MBytes  4.19 Mbits/sec  2.970 ms  109047/114212 (95%)  receiver

[root@vultr ~]# iperf3 -s -p 2010
-----------------------------------------------------------
Server listening on 2010
-----------------------------------------------------------
Accepted connection from 10.8.0.6, port 49080
[  5] local 10.8.0.1 port 2010 connected to 10.8.0.6 port 58454
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec   784 KBytes  6.42 Mbits/sec  0.833 ms  4747/5483 (87%)  
[  5]   1.00-2.00   sec   717 KBytes  5.87 Mbits/sec  2.122 ms  7409/8082 (92%)  
[  5]   2.00-3.00   sec   674 KBytes  5.53 Mbits/sec  0.952 ms  11218/11851 (95%)  
[  5]   3.00-4.00   sec   589 KBytes  4.83 Mbits/sec  0.614 ms  10515/11068 (95%)  
[  5]   4.00-5.00   sec   595 KBytes  4.87 Mbits/sec  0.895 ms  11246/11804 (95%)  
[  5]   5.00-6.00   sec   474 KBytes  3.89 Mbits/sec  0.775 ms  10606/11051 (96%)  
[  5]   6.00-7.00   sec   378 KBytes  3.10 Mbits/sec  4.233 ms  11821/12176 (97%)  
[  5]   7.00-8.00   sec   291 KBytes  2.38 Mbits/sec  1.318 ms  10819/11092 (98%)  
[  5]   8.00-9.00   sec   419 KBytes  3.43 Mbits/sec  1.557 ms  10529/10922 (96%)  
[  5]   9.00-10.00  sec   390 KBytes  3.19 Mbits/sec  1.159 ms  11313/11679 (97%)  
[  5]  10.00-10.75  sec   192 KBytes  2.10 Mbits/sec  2.970 ms  8824/9004 (98%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[SUM]  0.0-10.7 sec  2 datagrams received out-of-order
[  5]   0.00-10.75  sec  5.37 MBytes  4.19 Mbits/sec  2.970 ms  109047/114212 (95%)  receiver

- - - - - - - - - - - - - - - - - - - - - - - - -

# openvpn配置文件 —— 服务端

#

mode server
proto udp
port 1190
dev tun

ca ca.crt
cert server.crt
key server.key
dh dh.pem

server 10.8.0.0 255.255.255.0

push "redirect-gateway def1 bypass-dhcp"

push "dhcp-option DNS 80.67.169.12"
push "dhcp-option DNS 80.67.169.40"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

keepalive 10 120
reneg-sec 18000

persist-key
persist-tun

verb 4
mute 20
status openvpn-status.log

client-config-dir ccd

script-security 3

username-as-common-name
verify-client-cert none
auth-user-pass-verify /etc/openvpn/scripts/login.sh via-env

max-clients 50

client-connect /etc/openvpn/scripts/connect.sh
client-disconnect /etc/openvpn/scripts/disconnect.sh

route 192.168.1.0 255.255.255.0

fragment 1200
mssfix 1200

sndbuf 0
rcvbuf 0      ##### 已经在系统中设置为4000000（sysctl.conf）

comp-lzo no

cipher none 
auth none 

push "txqueuelen 4000"
txqueuelen 4000
#

- - - - - - - - - - - - - - - - - - - - - - - - -

# openvpn配置文件 —— 客户端

##
client
dev tun
proto udp
topology subnet
remote 192.168.1.10 1194
resolv-retry infinite

ca ca.crt
;key-direction 1
auth-user-pass
auth-nocache

nobind
persist-key
persist-tun
verb 4

fragment 1200       ##### very important    you can turn it up a bit. but,the lower the safer
mssfix 1200         ##### very important
comp-lzo no
sndbuf 0      ##### 
rcvbuf 0      ##### 已经在系统中设置为4000000（sysctl.conf）

cipher none      ##### disable openvpn 's cipher and auth for maxmized peformance. 
auth none        ##### you can enable openvpn's cipher and auth,if you dont care about peformance,or you dont trust udp2raw 's encryption

up /etc/openvpn/update-resolv.sh
down /etc/openvpn/update-resolv.sh
##
-------------------------------------------

# udp2raw命令——服务端

/root/udp2raw_amd64_hw_aes -s -l 0.0.0.0:11940 -r 127.0.0.1:1190 --raw-mode faketcp -k xxxxxx --cipher-mode xor --sock-buf 10240 --force-sock-buf

# udp2raw命令——客户端

/root/udp2raw_amd64_hw_aes -c -l 0.0.0.0:1194 -r x.x.x.x:11940 --raw-mode faketcp -k xxxxxx --cipher-mode xor --sock-buf 10240 --force-sock-buf
-------------------------------------------

**Comment by jason2000915** [comment]
> 这个是下载文件还是iperf3结果？

在windows上用IDM多线程下载文件的结果

> 我看你在之前的版本里说过，kcptun能到 7 8 MB/s. 可以用kcptun+udp2raw试一下，排除openvpn的问题。

kcptun我原来在搭某交通工具的时候就试过 刚刚又试了一遍 在打满CPU打满网络的情况下也能达到5-6MB/s

> 我不清楚你的方法和我在wiki里推荐的参数是不是等价的，不过这个buf大小确实可能影响吞吐率。

这个我sndbuf rcvbuf 4000000也试过 速度没有变化

**Comment by wangyu-** [comment]
>kcptun我原来在搭某交通工具的时候就试过 刚刚又试了一遍 在打满CPU打满网络的情况下也能达到5-6MB/s

这个是kcptun套上udp2raw后的速度吗？

>在打满CPU打满网络的情况下也能达到5-6MB/s

在虚拟机环境下5-6mb应该打不满cpu吧？

**Comment by jason2000915** [comment]
> 这个是kcptun套上udp2raw后的速度吗？

是的

> 在虚拟机环境下5-6mb应该打不满cpu吧？

用的Vultr 5刀VPS 服务器CPU打满了

**Comment by wangyu-** [comment]
>scp直连下载也有7MB/s

这个是直接从服务器scp到本地吗？

>在windows上用IDM多线程下载文件的结果单线程还要慢

你这个是从第三方服务器上下载到本地吗？如果是从自己的VPS上拖到本地速度如何？ 

多线程和单线程下载对于openvpn来说理论上应该没啥区别，openvpn是端口复用的，即使你多线程下载，对外也只有一个端口一个连接在通信。如果多线程和单线程有区别很大的话，不太正常。

**Comment by jason2000915** [comment]
> 这个是直接从服务器scp到本地吗？

我IDM下的是Vultr官方洛杉矶的测试文件 服务器也在洛杉矶

> 你这个是从第三方服务器上下载到本地吗？如果是从自己的VPS上拖到本地速度如何？

依旧很慢 1.5MB/s  IDM 2-3MB/s 相差应该不算很大吧

**Comment by jason2000915** [comment]
> 你这个是从第三方服务器上下载到本地吗？如果是从自己的VPS上拖到本地速度如何？

我用两台Vultr服务器之间用相同配置文件 相同环境 scp传文件最大速度依旧3MB/s封顶 ，而两台服务器下载官方测试文件都能达到200-300MB/s的速度

**Comment by wangyu-** [comment]
>我用两台Vultr服务器之间用相同配置文件 相同环境 scp传文件最大速度依旧3MB/s封顶

你说的这个是在2个VPS之间建好了udp2raw+openvpn连接，之后用scp通过openvpn分配的ip去拷文件么？

两台vps之间没有QOS和墙，你可以尝试只用openvpn不用udp2raw，看是不是问题依旧。

**Comment by jason2000915** [comment]
> 两台vps之间没有QOS和墙，你可以尝试只用openvpn不用udp2raw，看是不是问题依旧。怀疑openvpn，就拿openvpn单独试一下。

只有4-5MB/s 是openvpn的问题

**Comment by wangyu-** [comment]
>刚发现 用了fragment 0；mssfix 0然后把tun设备mtu改到24000 scp传输速度有质的飞升 到了12MB/s
>但也只是vps服务器之间能这么改 本地改了mtu完全传不了

以太网一般一个帧最多只能传1500。mtu改成24000以后，要分16个分片，16个只要丢一个就16个包全废了。只有局域网才能用大mtu，因为局域网基本不丢包。 我觉得《计算机网络》书上讲得比我明白，你还是去看书吧。

改成24000后可能是因为系统调用的次数减少了，所以性能提高了？不过这只能解释在CPU打满的情况下。 我觉得你有可能是某个核的CPU打满了。

>但下载速度只有最快3MB/s 下载时客户端CPU占用14% 服务端占用60%

不知道你看的CPU占用是总的CPU占用，还是OpenVPN所在的核的CPU占用。OpenVPN只能用一个核。

**Comment by jason2000915** [comment]
> 没遇到过类似问题。估计还是你自己的VPS问题，或者openvpn版本问题。

啊 我测反了 iperf3加上-R选项之后数据正常了 但是scp下载服务器文件速度依旧很慢 不知道是为啥？

windows连接VPN下载第三方网站的内容也是很慢 速度不超过3MB/s 下载的是Vu的测试文件 地点和服务器位置一样

**Comment by jason2000915** [comment]
解决了 我没在两端udp2raw上加上-a选项 还有就是iptables没有完全清空 导致下载速度慢 麻烦wangyu了！十分感谢指点！
