### ISSUE TITLE
在路由上加速kcp的疑问

### ISSUE THREAD

**Issue by i258559** [wangyu-/udp2raw-tunnel#18]
想在已经跑了kcp的ac68u上运行，假设服务器ip 23.23.223.223，ss端口443，kcp端口666，ss密码为a，kcp密码为b，服务器上的运行参数是？
./udp2raw_amd64 -s -l0.0.0.0:443 -r 127.0.0.1:666 -k "b" --raw-mode faketcp -a

68u参数是？
./udp2raw_arm -c -r 23.23.223.223:443 -l0.0.0.0:666 --raw-mode faketcp -a -k "b"

**Comment by wangyu-** [comment]
服务器上：

你的ss端口已经监听在443了，udp2raw_amd64再监听在443会失败。
```
./udp2raw_amd64 -s -l0.0.0.0:8855 -r 127.0.0.1:666 -k "b" --raw-mode faketcp -a
```
68U上：
```
./udp2raw_arm -c -r 23.23.223.223:8855 -l0.0.0.0:666 --raw-mode faketcp -a -k "b"
```

你这个路由器装的什么系统？如果是自己配置的openwrt应该比较简单，随便搞搞就通了。如果是梅林固件之类，你得研究下--lower-level选项怎么用了。

**Comment by i258559** [comment]
多谢大佬回复，路由上跑的是梅林固件，KS改版，“--lower-level” - -还没没了解过，我搜索一把。

ps：8855这个端口只要不和其他重复就可以了吧？

**Comment by wangyu-** [comment]
用的是梅林固件，可要做好连不通的心里准备了。固件的作者没有考虑到你会在kcp前面串个东西，所以会麻烦一点。

最好的办法就是--lower-level。

#11 #1 里面有关于--lower-level选项怎么用的信息。看#11的吧，这个比较短也比较新。

**Comment by wangyu-** [comment]
```
格式 ： --lower-level eth0#00:23:45:67:89:b9

eth0换成你的默认网卡。  00:23:45:67:89:b9换成你网关的mac（不是本机的mac）

ip route命令可以查到网关和默认网卡。 然后用arp -a <网关ip>，可以查到这个mac。 这样（预期）可以绕过SNAT，你就可以不用改iptables了。

```

**Comment by i258559** [comment]
多谢大佬的指点，周末尝试一下，再次拜谢。

**Comment by i258559** [comment]
@wangyu- 查到默认网关IP为  113.119.24.1，但使用 arp -a 113.119.24.1 查询，提示为：
No match found in 7 entries

**Comment by wangyu-** [comment]
@i258559  你把`ifconfig`，`ip route`，`arp -a` 结果发送到wangyucn@gmail.com

**Comment by i258559** [comment]
@wangyu- 0 0大佬这么早，发邮件了

**Comment by wangyu-** [comment]
@i258559  用这个 ppp0#00:00:00:00:00:00

**Comment by i258559** [comment]
@wangyu- 不行，还是一样的报错，- -b

**Comment by wangyu-** [comment]
报的错是什么，你贴出来一下。

**Comment by i258559** [comment]
和之前的一样，打码的是服务器!的地址
[tim 20170819084511](https://user-images.githubusercontent.com/23690792/29481945-6f95e470-84ba-11e7-8395-d6842df63f95.png)

**Comment by wangyu-** [comment]
你这个机器上的iptables貌似工作不正常呀，没有INPUT chain？
你执行一下我邮件里发给你的命令，我连上去看一眼。

**Comment by i258559** [comment]
改了好了密码wangyu123，这就是梅林改版koolshare最新的7.6

**Comment by wangyu-** [comment]
@i258559  看一下邮件

**Comment by wangyu-** [comment]
问题解决了，原因是@i258559 的梅林固件上的iptables 没有comment模块。  现在已经连通。

**Comment by wangyu-** [comment]
@i258559   我新release了一版，修正了`-a`自动添加iptables失效的问题。还增加了`--keep-rule选项`，定期监控iptables，如果丢了就重新加，防止规则被梅林固件删掉。你可以试用一下，期待反馈。

**Comment by helaobibi** [comment]
@i258559  楼主把kcp转到本地，然后再用ss插件转发本地的127.0.0.1？可以用吗？

**Comment by elric8** [comment]
@i258559 
能都分享一下
在梅林路由上安装udp2raw-tunnel的经验
万分感谢
