### ISSUE TITLE
我想请教一下作者,关于const_id为什么要append在规则名上?

### ISSUE THREAD

**Issue by nickfox-taterli** [wangyu-/udp2raw-tunnel#185]
我阅读main.cpp看到如下代码,这个const_id就是将来要用来做iptables的名字的append,但是我不太懂,为什么要这么做呢?这里面有什么玄机吗?

init_random_number_fd();
srand(get_true_random_number_nz());
const_id=get_true_random_number_nz();

**Comment by wangyu-** [comment]
因为可能会有多个udp2raw进程，udp2raw 加了`-a`后会自动添加/删除iptables，把const_id加上去可以防止一个进程不小心把另一个进程的iptables删了。

const_id还有别的用途，这个不是主要用途。

**Comment by nickfox-taterli** [comment]
是这样的,我打算把这个软件移植到我的硬件平台上,实现专用硬件加速,我的硬件平台:https://github.com/nickfox-taterli/LwIP_STM32F4-Discovery 使用这种协议栈是不需要防火墙设施的,因为都是直接底层发包,RAW方式同样支持,如果const_id只是用于防止防火墙规则覆盖,这看起来和我这里移植没什么关系?

**Comment by wangyu-** [comment]
>如果const_id只是用于防止防火墙规则覆盖,这看起来和我这里移植没什么关系?

既然你不需要防火墙规则，iptables这里应该就跟你的移植没什么关系了。
