### ISSUE TITLE
udp2raw如何在已经使用了KCPtun一键安装脚本的情况下安装

### ISSUE THREAD

**Issue by Kevin-Loeng** [wangyu-/udp2raw-tunnel#19]
我一开始是看按这篇博客来一键安装KCPtun的：[小内存福音，Kcptun Shadowsocks加速方案](https://blog.kuoruan.com/110.html)
这篇博客里也有教安装并使用了kcptun-linux-amd64 。成功以后发现UDP被运营商限制得厉害，所以现在想用你的udp2raw-tunnel，请问要怎么在使用了一键安装的脚本的基础上安装，不胜感激。

**Comment by wangyu-** [comment]
这个呀，我也没用过这个一键安装脚本，你得具体情况具体分析一下了。

基本的思路是：

本来的连接是
SS_client---->KCP_client-----------国际网络------------->KCP_server-------->SS_server

现在你在KCP_client和KCP_server间串联个udp2raw就可以了：
SS_client--->KCP_client---->udp2raw_client----国际网络--->udp2raw_server--->KCP_server--->SS_server

**Comment by i258559** [comment]
这个问题其实和我问题差不多 ，只不过我的是在路由上跑    #18

**Comment by wangyu-** [comment]
@i258559 他这个要简单一些，你用的梅林固件对扩展不友好，要用--lower-level。

**Comment by i258559** [comment]
@wangyu- 嗯，不过路由翻全家通用，手机啥也直接支持，更安逸。我周末回家试试，有疑问再来求教，\(//∇//)\

**Comment by wangyu-** [comment]
@i258559 自己通过openwrt手动搭的也支持透明代理的，一个路由，所有设备通用。需要打的命令只需要10几行。。。

**Comment by i258559** [comment]
@wangyu- 主要路由固件自带了ss+kcp，这个方便，之前一直没怎么折腾过路由，所以（；￣ェ￣）

**Comment by sdysj** [comment]
不用kcp而直接用 udp2raw+ss 能起到加速作用吗？

**Comment by wangyu-** [comment]
如果你的UDP被QoS了，或者不稳定。能起到一定改善速度的效果。

但是udp2raw只解决udp qos，不是加速器，能比你直接ss改善多少就不好说了，在跨国连接上建议配合kcptun/finalspeed使用。

**Comment by yyysuo** [comment]
下面是针对已经部署了ss+kcptun方案的系统的修改经验，供各位参考：
服务器端
1：上传udp2raw_amd64到kcptun目录
2：执行chmod -x udp2raw_amd64和chmod 777 udp2raw_amd64.
3：复制start.sh，更改里面的内容为
#!/bin/bash
cd /root/kcptun/
./udp2raw_amd64 -s -l0.0.0.0:8855 -r 127.0.0.1:改成KCPTUN服务端口 -k "passwd" --raw-mode faketcp -a
并改名为accstart.sh
4：执行chmod -x accstart.sh和chmod 777 accstart.sh
5：执行以下命令，添加开机启动（centos）
chmod +x /etc/rc.d/rc.local;echo "sh /root/kcptun/accstart.sh" >> /etc/rc.d/rc.local

虚拟机端（下载udp2raw的vb镜像）：
1：用putty登陆虚拟机
2：执行命令
cd /root/
./udp2raw_x86 -c -l0.0.0.0:3334  -r改成VPS IP:8855 --sock-buf 10240 -a -k "passwd" --raw-mode faketcp &

电脑端
1：复制kcptun的原文件夹Seattle为Seattle-acc，并更改里面的Seattle.vbs的kcptun本地端口 vps ip和端口
exeConfig = "client_windows_amd64.exe -l :12950（改成KCP本地端口，需要不同于原kcptun端口） -r VPS IP:端口 -key KCPTUN密码 -nocomp -mtu 1300 -sndwnd 2048 -rcvwnd 2048 -crypt salsa20 -mode fast2 -dscp 0 -conn 8 -autoexpire 20"
2：启动复制的kcptun

ShadowSocks端
1：复制KCP-Seattle条目为KCP-Seattle-Acc，
2：更改端口为12950

大功告成。

**Comment by sxml** [comment]
求大神做个 udp2raw一键脚本 谢谢!
