### ISSUE TITLE
udp2raw能连上但是用nat类型测试显示udpblcoked

### ISSUE THREAD

**Issue by zhonghao659** [wangyu-/udp2raw-tunnel#194]
[路由器用的梅林固件，设置什么的试了很多遍，科学+kcp+udpspeeder，科学+kcp+udpspeeder+udp2raw，科学+kcp+udp2raw都试过，每一种组合都能连上服务器，服务器端截图如下：
![image](https://user-images.githubusercontent.com/17142858/43672750-1e72d6ca-97e7-11e8-9cc4-0a63c6ca460b.png)
这图是使用科学+kcp+udp2raw然后使用nat类型测试后服务器反馈的数据。总之就是梅林固件只要使用游戏模式，不管怎么搭配，都会udpblcoked但是能科学上网，但是其他模式不会udpblocked，我的网是移动的网，没有公网ip。

**Comment by leebhn** [comment]
看到你的串联，我理解为kcp将tcp流量转为udp流量再通udpspeeder加速后从udp2raw转出，你的服务器最终只收到tcp的流量请求，所以当然udp不通。
我记得udpspeeder的开发者有一个指南，禁用kcptun的fec，只让udpspeeder启用fec可以使kcp负责tcp流量，而udpspeeder负责udp流量。

**Comment by zhonghao659** [comment]
> 看到你的串联，我理解为kcp将tcp流量转为udp流量再通udpspeeder加速后从udp2raw转出，你的服务器最终只收到tcp的流量请求，所以当然udp不通。
> 我记得udpspeeder的开发者有一个指南，禁用kcptun的fec，只让udpspeeder启用fec可以使kcp负责tcp流量，而udpspeeder负责udp流量。

已经解决了，谢谢
