### ISSUE TITLE
Can UDP bind on server side?

### ISSUE THREAD

**Issue by basncy** [wangyu-/udp2raw-tunnel#195]
Current version works only when the UDP server and udp2raw server runs on the same side, can we make it reverse?
Which network topology looks like:
UDP client --> udp2raw server ------------ udp2raw client ----> UDP server.

**Comment by wangyu-** [comment]
What you are looking for is a reverse-tunnel or a VPN, there is no such built-in features in udp2raw.

>UDP client --> udp2raw server ------------ udp2raw client ----> UDP server.

use a reverse-tunnel or VPN together with udp2raw, then it will definitely work,for example:

```
UDP client -->( VPN server<--- udp2raw server <------------ udp2raw client <---VPN client)--> UDP server.
```

**Comment by basncy** [comment]
ok, thanks.
