### ISSUE TITLE
加密安全不，是否需要配合SS使用

### ISSUE THREAD

**Issue by muziling** [wangyu-/udp2raw-tunnel#197]
目前只用了tinyfecvpn+udp2raw 来使用，都开启了-k密码参数，不配合SS加密，不知道安全不。
或者udp2raw 是否有强加密选项？

**Comment by wangyu-** [comment]
tinyfecvpn的`-k`不是严肃的加密。

udp2raw最高的加密是`aes128cbc/aes128cfb+sha1_hmac`；encrypt-then-MAC 方式，相当于一种AE/AEAD。  至于安全性如何，难以一句话回答`是安全的/不安全的`，请自己拿捏。

**Comment by muziling** [comment]
好的，谢谢
