### ISSUE TITLE
节点中转，OVPN连接30秒一断流

### ISSUE THREAD

**Issue by Handsome1080P** [wangyu-/udp2raw-tunnel#199]
网络扑拓图：
Ovpn客户端   -----------  中继服务器>udpspeeder> udp2raw  --------------    udp2raw>udpspeeder>服务器

客户端使用53端口UDP普通直连中继服务器，中继服务器上使用UDP2RAW和UDPSPEEDER与后端服务器连接。目前问题是客户端连上中继服务器后，30s一断流，30后无数据连接，超时180S后重新连接，然后循环。重连后30秒内可以上网，30后无数据包接受。如果同客户端与中继服务器统一局域网，同53端口连接中继服务器，没有上诉情况。怀疑53被干扰，单在中继服务器上部署ovpn服务器，并使用53端口外网连接，没有上述情况。
中继服务器
![中继](https://i.loli.net/2018/08/21/5b7c314babc00.png);
服务器
![服务端](https://i.loli.net/2018/08/21/5b7c314babb03.png);
客户端
![客户端](https://i.loli.net/2018/08/21/5b7c3262bb577.png);

**Comment by phc217** [comment]
不要用53、80这种被重点监控的端口，用1024以内的冷门端口即可。

**Comment by Handsome1080P** [comment]
重裝了下ovpn，解決了
