### ISSUE TITLE
请问下，这个程序可以让udp通过tcp走？同时通过tcptun减少掉包率吗？

### ISSUE THREAD

**Issue by genics** [wangyu-/udp2raw-tunnel#2]
另外希望有x86的lede的编译好的文件，迫不及待想试试，我是游戏需求，因为fifa这个游戏走udp，我这边掉包率很严重，想通过kcptun加你这个来改善，不知道能不能行？期待大神解答。

**Comment by wangyu-** [comment]
我刚才在release里发布了x86的binary。你可以试一下是否兼容你的lede环境。

你说的tcptun应该是kcptun吧。 你说的这个方案是不可行的。 kcptun本身就是利用udp协议，实现了一个优化版的类似tcp的协议，来达到加速tcp的目的，可以说是使用udp加速tcp。你不能把udp流量变成tcp以后再用kcptun把流量变成udp来加速他本身。

udp2raw是用来绕过udp屏蔽，或者udp qos的。游戏一般流量很小，丢包高一般都因为网络链路本身很差，不是qos的问题。 所以，udp2raw不适合你的需求。

不过我有一套专门的udp加速方案，之前我自己用来玩美服的brawl stars和亚服的mobile legend的，对于游戏丢包效果很好。再过几天我把代码和文档完善了以后，会传上来。

**Comment by genics** [comment]
明白了，十分感谢，题目打错了，我意思就是说kcptun。那期待你完善后的游戏加速方案。我链路确实本身很差，现在用沙田和阿里云的ss，我mtr了一下cn2的丢包率都有百分之20到80.。。

我重新整理下思路，kcptun是通过udp走的，你这个程序目的是让kcptun不受udpqos 和封锁对吧，然而kcptun本身只能加速tcp，所以说udp在这个情况下是没有加速效果的，我理解对吧？

**Comment by wangyu-** [comment]
差不多是这个意思。

20~80%这个丢包率有点太高了。

udp加速一般两种方案：
1.找个丢包低的服务器中转
2.通过多倍发包、FEC的方式发送冗余数据，抵消丢包的影响。

我那个项目用的是方案2.  如果高峰时候真有80%的丢包率，就算发5倍的冗余数据也只能把丢包降到30%,发十倍也只能降到10%。

估计你这么高的丢包只能用方案1，或者直接换服务器了。

**Comment by genics** [comment]
我是说mtr里面到了cn2那个节点有时候是百分之20到百分之80的丢包，直接ping 目标服务器丢包没那么高。我想试试你的多倍发包解决下问题，本来以为kcptun的多倍发包能解决。结果他只解决tcp的问题。要是有一个多倍发包能同时解决tcp和udp就好了。因为fifa这个游戏掉不掉线是看tcp（通过tcp保持和服务器的链接）实际游戏中延迟卡顿是看udp的。（udp和玩家直连，当然也可以通过lede的游戏模式通过ss中转udp）

**Comment by wangyu-** [comment]
了解了。可能只是那个节点限制了icmp的回复频率，实际没那么糟。

同时加速tcp和udp可以做到。先等我把项目发出来吧。

**Comment by genics** [comment]
好的，好的~

**Comment by wangyu-** [comment]
udp加速器已发布。
https://github.com/wangyu-/UDPspeeder

**Comment by wangyu-** [comment]
@genics  udp加速器已发布
https://github.com/wangyu-/UDPspeeder
