### ISSUE TITLE
请教：CPU是BCM4708型号的选哪个文件

### ISSUE THREAD

**Issue by i258559** [wangyu-/udp2raw-tunnel#20]
查了下，68U的CPU型号是BCM4708，20170818.0 release包里面有两个类似的文件：udp2raw_bcm2708，和udp2raw_arm，那么，BCM4708的CPU选哪个比较适合？（在openwrt页面是有bcm47XX的资源，但自编译手残档看说明也不是很懂（；￣ェ￣））

**Comment by wangyu-** [comment]
用udp2raw_arm。

**Comment by i258559** [comment]
收到，明天周末可以折腾一波了

**Comment by i258559** [comment]
<img width="1054" alt="2017-08-18 17 46 42" src="https://user-images.githubusercontent.com/23690792/29453752-56ec418a-843d-11e7-925c-73ddbfb5e2a0.png">
在瓦工上试跑了下，自动添加后就卡住了(见图)，debian8 mini x86_64

**Comment by wangyu-** [comment]
必须c s都运行了才能跟图里一样。

**Comment by i258559** [comment]
了解，如果和图一样输出的，就可以不管，断开ssh了？

**Comment by wangyu-** [comment]
确实和图里的输出一样就证明udp2raw已经通了。不管了是什么意思呢？

**Comment by i258559** [comment]
不管了：意思是断开命令输入端与路由/服务器的ssh链接

**Comment by wangyu-** [comment]
直接断开链接运行的命令会被杀死吧。你用screen,tmux,nohup之类的命令让它运行在后台再退。

**Comment by i258559** [comment]
收到，明天折腾下，希望路由能跑起来=。=
