### ISSUE TITLE
长城宽带测试结果很不理想

### ISSUE THREAD

**Issue by wuyanteng** [wangyu-/udp2raw-tunnel#211]
kcptun+udpspeeder+udp2raw架构，长宽测试结果简直怀疑人生，fast最大下载2M左右，还没有不使用这个架构的速度高。

长宽真特么垃圾！Fuck

**Comment by Handsome1080P** [comment]
先用KCPTUN把TCP转成UDP，在用udp2raw转成TCP，你TM真是个人才。自己神经病还怪别人，绝了，智障吧你

**Comment by Handsome1080P** [comment]
你是我第一个见到这么白痴的人

**Comment by wuyanteng** [comment]
> 先用KCPTUN把TCP转成UDP，在用udp2raw转成TCP，你TM真是个人才。自己神经病还怪别人，绝了，智障吧你

kcp+udp2raw速度上不去，我又使用udpspeederv2加速了udp, 速度还是不行，你个傻屌，什么素质，自己不看看udpspeeder啥作用

**Comment by wangyu-** [comment]
就此停止吧。 如果再出现人身攻击的语言，就直接屏蔽回复权限了。

**Comment by wangyu-** [comment]
>fast最大下载2M左右，还没有不使用这个架构的速度高

kcptun本身自带fec，再加udpspeeder收益不大。 如果没调好参数，变慢也是有可能的。
