### ISSUE TITLE
OVPN服务端配置问题以及速度超级慢

### ISSUE THREAD

**Issue by Handsome1080P** [wangyu-/udp2raw-tunnel#213]
大佬的推荐ovpn服务端配置里有这几行：
mssfix 1200
fragment 1200
sndbuf 4000000
rcvbuf 4000000
但是在我的实际测试中，只有第一个mssfix可以防止udp2raw出现huge packets。fragment添加会导致客户端出现 frag ttl expired i=*错误。sndbuf和rcvbuf设置的太大了，添加后根本无法上网，网页无法打开，无法ping通域名以及ip，无法解析地址。
所以我自己从新改了下，只保留了mssfix，sndbuf和rcvbuf改成了以下：
mssfix 1200
sndbuf 393216
rcvbuf 393216
![TIM截图20181012023706.png](https://i.loli.net/2018/10/12/5bbf9ae2ec7a9.png)
UDP2RAW:
udp2raw -s -l0.0.0.0:2500 -r127.0.0.1:2345 -k "123456" --raw-mode faketcp -a --cipher-mode xor --auth-mode simple
UDPSPEEDER:
speederv2 -s -l0.0.0.0:2345 -r127.0.0.1:2333  -f2:4 --timeout 1

目前的问题就是：速度提不上去，我香港的HKBN服务端网口是1Gbit，本地网络是100Mbit，但是使用UDPSPEEDER+UDP2RAW速度总是在10-30Mbit左右徘徊，十分缓慢。
服务端是旧笔记本，CPU是I5-6300HQ，16G内存，千M网卡，所以性能不是问题。
本地客户端是台式机装的Debian 9。
服务端和本地客户端都没有任何报错信息，所以请问这是什么问题，怎么解决？

**Comment by pandalion98** [comment]
I sometimes also experience this. It seems like this is more with OpenVPN than udp2raw.

Have you tried https://community.openvpn.net/openvpn/wiki/Gigabit_Networks_Linux ?
