### ISSUE TITLE
是否有可能用于加速teamviewer？

### ISSUE THREAD

**Issue by terrytw** [wangyu-/udp2raw-tunnel#224]
wangyu大大你好，突发奇想：
家里面是电信的，公司是移动的，用teamviewer远程工作的时候感觉特别的卡
怀疑是移动对UDP进行QOS所导致的
网上查了半天，只有一个文章语焉不详的讲到说，teamviewer会通过服务器把两台没有公网IP的电脑进行链接，然后用UDP穿透的方法来进行直连
我在想可不可以监测一下用到的UDP端口，然后在公司开客户端，在家里的路由器（有公网IP的OPENWRT X86_64）上开服务端，来加速teamviewer？

大大觉得这个主意咋样？

**Comment by wangyu-** [comment]
应该可以。如果是QOS就用udp2raw，如果是网络丢包高就UDPspeeder。

>我在想可不可以监测一下用到的UDP端口，然后在公司开客户端，在家里的路由器（有公网IP的OPENWRT X86_64）上开服务端，来加速teamviewer？

你可以在不需要知道端口的情况下， 透过udp2raw/UDPspeeder拨一条VPN到server，然后用VPN的ip访问server。

**Comment by terrytw** [comment]
> 你可以在不需要知道端口的情况下， 透过udp2raw/UDPspeeder拨一条VPN到server，然后用VPN的ip访问server。

请问能不能详细解释一下？我有点儿没看懂，谢谢！

**Comment by wangyu-** [comment]
就好像这个链接里说的例子一样：
https://github.com/wangyu-/tinyfecVPN#getting-started

**Comment by terrytw** [comment]
好的，谢谢！
