### ISSUE TITLE
如何同时监听在ipv4和ipv6上？

### ISSUE THREAD

**Issue by verniyb** [wangyu-/udp2raw-tunnel#227]
教程和wiki中只单独给出了ipv4和ipv6各自的监听方法，我尝试了一些配置的写法(单词port代表端口号)

`-l 0.0.0.0:port,[::]:port`    逗号分隔，逗号后的内容被忽略
`-l 0.0.0.0:port [::]:port`    空格分隔，空格后的内容被忽略
`-l 0.0.0.0:port -l [::]:port` 两个l参数，参数重复错误
`-l [0.0.0.0,[::]]:port`         无法正确解析

是否有同时监听在ipv4和ipv6上的正确写法？

我使用了udp2raw和udpspeeder串联给shadowsocks加速的方式。如果不能同时监听v4和v6，那就意味着必须要开两套这样的一组程序。是否有更好的解决办法？

希望能得到帮助，谢谢

**Comment by wangyu-** [comment]
>是否有同时监听在ipv4和ipv6上的正确写法？

没有。

>我使用了udp2raw和udpspeeder串联给shadowsocks加速的方式。如果不能同时监听v4和v6，那就意味着必须要开两套这样的一组程序。是否有更好的解决办法？

udp2raw 想要同时监听ipv4和ipv6必须要开两个。 UDPspeeder server只需要开一个。可以2个udp2raw server指向同一个UDPspeeder server。
