### ISSUE TITLE
nohup命令无法让进程在后台运行

### ISSUE THREAD

**Issue by i258559** [wangyu-/udp2raw-tunnel#23]
nohup 命令可以在后台运行，但只要C或S任一断开了ssh链接，则失效，是nohup命令的问题？但之前用与net-speeder时又是正常的说-。-

nohup ./udp2raw_amd64 -s -l 0.0.0.0:2323 -r 127.0.0.1:65022 -a -k "123456" --raw-mode faketcp --cipher xor >./udp2raw.log 2>&1 &

nohup ./udp2raw_arm -c -r 112.112.51.222:2323 -l 0.0.0.0:65022 --raw-mode faketcp -k "123456" --lower-level  ppp0#00:00:00:00:00:00 --cipher xor >./udp2raw.log 2>&1 &

**Comment by i258559** [comment]
问题通过搜索解决了，不是最后”&“的问题，是要断开ssh需要通过”exit“来进行，我之前都是直接断开，于是扑街了- -b

**Comment by i258559** [comment]
刚又试了下，还是有连接异常的情况。原因不明了。但可以肯定的是如果不断ssh，目前没出现过断开的情况- -b

**Comment by wangyu-** [comment]
@i258559  应该不用这么复杂，安装个screen或者tmux试试。

**Comment by i258559** [comment]
好，我看看这2个怎么搞

**Comment by linhua55** [comment]
@i258559 
nohup和 disown 一块用

nohup [command] & disown
