### ISSUE TITLE
【效果反馈】搬瓦工CN2GIA+锐速

### ISSUE THREAD

**Issue by guorenxi** [wangyu-/udp2raw-tunnel#246]
昨天测试了搬瓦工著名的 CN2 GIA 线路，在开启锐速之后，TinyFecVPN+UDP2RAW 串联网速极慢，但是SS能直接跑满，可能是锐速产生了不良的印象。

**Comment by haodong** [comment]
把锐速关掉试试

**Comment by zzlinwq** [comment]
不会 吧

[speedtest-cli.zip](https://github.com/wangyu-/udp2raw-tunnel/files/2871679/speedtest-cli.zip)

**Comment by Handsome1080P** [comment]
wangyu早就回復過不要用銳速，BBR無影響，還在問這種問題
