### ISSUE TITLE
串联加速UDP2RAW提示huge packet, data_len > 1800,dropped

### ISSUE THREAD

**Issue by Handsome1080P** [wangyu-/udp2raw-tunnel#261]
server环境：实体机CENTOS 7,KERNEL 5.0
client环境：实体机WINDOWS 10 1809+OPENVPN 

使用OPENVPN+UDPSPEEDER+UDP2RAW串联加速，UDPSPEEDER使用MODE0，udp2raw的iptables按照WIKI清理，重新设定了许多次，包括手动-g/自动-a设定UDP2RAW iptables表。iptables版本为最新版本。

openvpn server配置文档如下：

> dev tun
persist-key
persist-tun
port 2333
proto udp
keepalive 10 120
client-to-client
push "redirect-gateway def1"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 1.1.1.1"
push "topology subnet"
reneg-sec 0
duplicate-cn
ca /etc/openvpn/keys/ca.crt
cert /etc/openvpn/keys/server.crt
key /etc/openvpn/keys/server.key 
dh /etc/openvpn/keys/dh2048.pem
server 10.8.0.0 255.255.255.0
user nobody
group nobody
auth none
cipher none
push "block-outside-dns"
ifconfig-pool-persist ipp.txt
status openvpn-status.log
log /etc/openvpn/openvpn.log
verb 3
mute 20
compress
sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"
mssfix 1200
fragment 1200
txqueuelen 4000

按照wiki，client和server端都设定了mssfix 和fragment等关键参数，但是在Windows openvpn client log依旧显示

> adjusting link_mtu to 1629

在无法解决问题后，查询其他issue,尝试设定过

> tun-mtu 1200

> link-mtu 1200

但是设定后Windows直接无法连接。

**Comment by PHCSJC** [comment]
我昨天也反馈了，有个临时的解决方案：
https://github.com/wangyu-/udp2raw-tunnel/issues/260

**Comment by Handsome1080P** [comment]
> 我昨天也反馈了，有个临时的解决方案，大佬几个月没现身了，可能忙别的去了：
> https://github.com/wangyu-/udp2raw-tunnel/issues/260

没卵用。现在加速变成减速了，比原来更加丢包

**Comment by gitrootid** [comment]
期待修复这个问题

**Comment by wangyu-** [comment]
>在看youtube时会大量出现这个警告，但似乎并不影响视频的正常播放，速度也还不错，在一些其它网站也会出现这个警告，但没有y2那么多，比如PC端的google play也会少量出现这个警告。

从目前反馈和我自己的测试来看，只是在网络上有大量包的时候，会偶尔有几个包粘在一起。对实际使用没有明显可感知的影响。

我目前比较忙，没有时间去解决这个本来就影响不大的问题。

>没卵用。现在加速变成减速了，比原来更加丢包

>期待修复这个问题

使用udp2raw后比原来慢有很多可能的原因，具体可以翻看以前的issue排查。希望你们在网络效果不好的时候冷静分析原因，不要盲目往一个问题上甩锅，(一厢情愿地)认为这个问题解决了你的网络就可以变快了。

当然你们也可以用数据证明我说的是错的。 比如对比`关闭gso和gro`前后的性能， 比如自己改代码修复这个问题然后对比修复前后的性能。 如果解决这个问题会有明显的性能提升，我会高优先级考虑的。

**Comment by wangyu-** [comment]
已修，见：https://github.com/wangyu-/udp2raw-tunnel/issues/226

你们可以试用下，看问题有没有改善。
