### ISSUE TITLE
希望增加 udp2raw 在 openwrt  上的多进程支持

### ISSUE THREAD

**Issue by ykfq** [wangyu-/udp2raw-tunnel#262]
我现在使用 $$ + kcptun + udpspeeder + udp2raw 实现了 2串2并 方案，在linux 虚拟机中运行正常，但是将客户端服务搬上 openwrt 以后，发现 udp2raw 只能有一个进程存在，即要么给 kcptun 加壳，要么给 udpspeeder 加壳，这样就不能愉快的体验游戏了。

希望能考虑增加 udp2raw 在 openwrt  上的多进程支持。

搜了一下已有 issue，没有类似问题，因此新增一个，如果已有解决方案，烦请引用一下，然后关闭本 issue。

感谢作者及活跃的社区伙伴们。

**Comment by Handsome1080P** [comment]
多複製幾份改名字不得了，screen了解一下

**Comment by ykfq** [comment]
> 多複製幾份改名字不得了，screen了解一下

已经试过了，udp 和 tcp 监听在同一端口，sstap 测试只有一个协议能用。

**Comment by zhfreal** [comment]
没有发现在Linux发行版和openwrt上运行udp2raw有什么不同。udp2raw 有一个openwrt的luci-app，直接在web管理端就能实现多个udp2raw的运行。

**Comment by ykfq** [comment]
> 没有发现在Linux发行版和openwrt上运行udp2raw有什么不同。udp2raw 有一个openwrt的luci-app，直接在web管理端就能实现多个udp2raw的运行。

谢谢，回去试试。最近发现路由器性能不行，使用 IDM 下载的时候 CPU 会100%，所以不想折腾了。
