### ISSUE TITLE
VPS不支持iptables，有没办法使用？

### ISSUE THREAD

**Issue by xuiv** [wangyu-/udp2raw-tunnel#264]
VPS的linux内核不支持tuntap设备，不允许iptables操作，udp2raw可以运行，但是不可以修改iptables。socat可以tcp和udp端口互相转换，但是tcp转成udp后再转回tcp，工作不正常，我估计socat相互转端口后不能双向转输了。

**Comment by xuiv** [comment]
我打算代理玩游戏，udp延迟有300ms，没有什么软件能在vps上把udp转成tcp，vps只能走websocket.

**Comment by wxlg1117** [comment]
换vps
