### ISSUE TITLE
如何为v2ray的mkcp进行伪装

### ISSUE THREAD

**Issue by smallprogram** [wangyu-/udp2raw-tunnel#267]
您好，我想请问以下如何使用udp2raw为v2ray的mkcp进行伪装，我在google等找了好久也没有找到一个解决方案。
自己尝试了很多次，udp2raw，client和server已经可以互通，就是不知道如何让v2ray的mkcp走这条通道。
恳请大佬能给一个关于v2ray的伪装教程。在此先跪谢。Orz

**Comment by bwang24** [comment]
本地v2ray客户端出站设置成本地udp2raw的监听端口， 服务端udp2raw转发到服务端v2ray监听的端口就行了

**Comment by smallprogram** [comment]
> 本地v2ray客户端出站设置成本地udp2raw的监听端口， 服务端udp2raw转发到服务端v2ray监听的端口就行了

目前直接基于TCP协议进行伪装，基本上没什么大问题了
