### ISSUE TITLE
开机无法自动运行

### ISSUE THREAD

**Issue by pkron** [wangyu-/udp2raw-tunnel#27]
开机无法自动运行，包括使用 nohup 和 screen 命令启动。只有通过 SSH 启动后，通过 exit 退出才能后台运行。

**Comment by wangyu-** [comment]
nohup和screen只是防止你退出ssh后进程被杀掉。没有开机自动启动的功能。

如果是普通的linux（包括openwrt），把你的命令加到/etc/rc.local里。如果是其他路由器固件，在网上找相应的办法吧。

**Comment by pkron** [comment]
我的硬件是 树莓派，命令已写入 /etc/rc.local，唯独这个启动不了。
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by wangyu-** [comment]
你把命令重定向到一个文件，看看报什么错。

**Comment by wangyu-** [comment]
一般这种问题是因为系统启动时候有什么东西没初始化好。

你写个脚本延迟启动。或者一个脚本：

run_udp2raw.sh

while true
do
sleep 10
udp2raw .......
done

然后在rc.local里加上：
sh run_udp2raw.sh&

这样，只要udp2raw启动失败了，过十秒就再启动一次。

**Comment by wangyu-** [comment]
一般这种问题是因为系统启动时候有什么东西没初始化好。

你写个脚本延迟启动。或者一个脚本：

run_udp2raw.sh

while true
do
sleep 10
udp2raw .......    >/udp2raw.log  2>&1   
done

然后在rc.local里加上：
sh run_udp2raw.sh&

这样，只要udp2raw启动失败了，过十秒就再启动一次。

如果一直失败就去看udp2raw.log

**Comment by pkron** [comment]
^[[32m[2017-08-20 04:25:29][INFO]argc=9 ^[[0m^[[32mspeeder ^[[0m^[[32m-c ^[[0m^[[32m-l ^[[0m^[[32m192.168.50.2:53 ^[[0m^[[32m-r ^[[0m^[[32m服务器隐藏 ^[[0m^[[32m-d2 ^[[0m^[[32m-k ^[[0m^[[32mSK48YEEEDQ4GTTHZ ^[[0m^[[32m
^[[0m^[[31m[2017-08-20 04:25:29][FATAL]socket bind error^[[0m^[[0m

**Comment by wangyu-** [comment]
你不用vim，用cat 或者tail看就没这么多乱码了。

原因是网络没初始化好。用前面我说的办法。只要启动失败过10表就再试一次。

**Comment by pkron** [comment]
我试了一下，绑定 0.0.0.0:53 就可以正常启动~

**Comment by wangyu-** [comment]
建议你还是写个脚本吧。否则说不定哪次启动又不好使了。

**Comment by pkron** [comment]
好的，我试试~

**Comment by dfyun520** [comment]
> 一般这种问题是因为系统启动时候有什么东西没初始化好。
> 
> 你写个脚本延迟启动。或者一个脚本：
> 
> run_udp2raw.sh
> 
> while true
> do
> sleep 10
> udp2raw ....... >/udp2raw.log 2>&1
> done
> 
> 然后在rc.local里加上：
> sh run_udp2raw.sh&
> 
> 这样，只要udp2raw启动失败了，过十秒就再启动一次。
> 
> 如果一直失败就去看udp2raw.log

这个是什么意思啊？怎么操作
