### ISSUE TITLE
udp2raw通过端口转发无法连接

### ISSUE THREAD

**Issue by fofocx** [wangyu-/udp2raw-tunnel#270]
我有需要udp连接的内网服务器A和客户端C，AC没有直接的连接，需要通过公共服务器B做中转穿透，B只开放了tcp，所以开始的思路是用udp2raw代理udp，在B上做端口转发，把udp2raw连接起来，然而并不能
设置是A这边udp2raw server监听tcp 8848，B上8848端口转发到A上的8848，C client -rB的8848端口，启动后client一直在resyn
后来怀疑转发有问题就在client上做本地测试，在C上做8848的server -l监听0.0.0.0，用ssh隧道做8838到8848的转发，client -r到本地非127的ip:8838端口，也没通。再往后用docker进行尝试，server 的8848端口用-p暴露到 宿主，client只有连接到docker的ip时才通，用宿主ip就不行。
用netcat查过几次转发都应该是通的，然而udp2raw就是没有连接起来
这个问题困扰比较久，实在不知道是怎么回事

**Comment by Handsome1080P** [comment]
檢查客戶端的iptables，drop的應該是A的IP和端口，而不是中繼

**Comment by fofocx** [comment]
> 檢查客戶端的iptables，drop的應該是A的IP和端口，而不是中繼
谢谢，我重新安装检查一遍

**Comment by lewisseng** [comment]
我自己也試過在路由器作端口轉發是無法連接成功的，路由轉發和udp2raw伺服器端端口要一致

**Comment by fofocx** [comment]
> 我自己也試過在路由器作端口轉發是無法連接成功的，路由轉發和udp2raw伺服器端端口要一致

可能
