### ISSUE TITLE
请问mtu-warn是啥 只是个警告么?

### ISSUE THREAD

**Issue by kxmp** [wangyu-/udp2raw-tunnel#273]
这个有没有像其他软件一样 可以直接限制mtu大小. 
从没用过这个东西. 这个协议头部是多大? (刚看了下 好像是32字节tcp头 然后外加心跳包)
我需要怎样把mtu设置为最佳的?
mtu-warn只是个警告的话 那目前是不是还没有配置mtu的参数啊.

2019-07-11 15:17:24
看了下流量 目前跑出来了1289的mss 
ipmtu=1341 (1341-52=1289mss)
看起来是自动拆包的!!? (不太确定. 看了下v2 quic直连 1279的ipmtu 原来它本身就很小啊!!!)
要是能手动配置下把他抬高点 那效率就更高了 :D

另外请问那个win客户端的easy-faketcp和faketcp什么区别啊!!!

**Comment by Handsome1080P** [comment]
最新的test版可以試試，MTU-warn通病

**Comment by Handsome1080P** [comment]
還有問問題之前先把所有wiki都看了再問，不然會覺得很傻逼

**Comment by kxmp** [comment]
wiki我当然看了啊 过来再问问确认下~~
