### ISSUE TITLE
一点点小疑问

### ISSUE THREAD

**Issue by kxmp** [wangyu-/udp2raw-tunnel#274]
--auth-mode           <string>        avaliable values:hmac_sha1,md5(default
),crc32,simple,none

这里面的模式 最高的是hmac_sha1
那么那个md5 也是hmac么? hmac_md5??

**Comment by Equim-chan** [comment]
从 encrypt.cpp 上看，只有 hmac_sha1 是 hmac，其他的是直接 hash。

**Comment by kxmp** [comment]
感谢解答
