### ISSUE TITLE
HTTPS connections still not working when using WireGuard + Udp2Raw

### ISSUE THREAD

**Issue by ShadowOfHarbringer** [wangyu-/udp2raw-tunnel#282]
The same issue as #208.

I am using Wireguard + udp2raw. Version:

udp2raw-tunnel
git version:5cc304a261    build date:Sep  2 2019 22:15:36

I have decreased the MTU to 1300, then 1200 and HTTPS traffic is still not working. Also added --fix-gro. Didn't help.

What is working and what is not:
- TCP+UDP traffic (Bittorrent): OK
- TCP SOCKS4 traffic: OK
- HTTP browser direct traffic: OK
- HTTPS browser direct traffic: FAIL

So I can browse HTTPS & HTTP if I do it through SOCKS4 Proxy, but not directly. Weird.

This has to be some other issue than MTU.

**Comment by ShadowOfHarbringer** [comment]
I have just also tried your suggestion - to use UDPspeeder.

It works like this

Web Browser -> Wireguard -> UDPspeeder -> Udp2Raw -> [INTERNET] -> Udp2Raw -> UDPspeeder ->  Wireguard -> [VPS] -> Google.com

Still not working.

**Comment by ShadowOfHarbringer** [comment]
I have just also tried your suggestion - to use UDPspeeder.

It works like this

Web Browser -> [LOCAL COMPUTER] -> Wireguard -> UDPspeeder -> Udp2Raw -> [INTERNET] -> [VPS] -> Udp2Raw -> UDPspeeder -> Wireguard ->  Google.com

Still not working.

**Comment by ShadowOfHarbringer** [comment]
I have now tried MTU 1000 and MTU 800. No change, HTTPS not working.

**Comment by ShadowOfHarbringer** [comment]
Here is my current configuration:

CLIENT:

udp2raw -c -l127.0.0.1:10444  -rREMOTE.VPS.IP.ADDRESS:443  -k "vpn_password" --raw-mode faketcp -a --fix-gro
speederv2 -c -l0.0.0.0:10443  -r127.0.0.1:10444 -f100:1

Wireguard:
[Interface]
PrivateKey = *******************
PostUp = iptables -A FORWARD -i wg0-client -j ACCEPT; ip6tables -A FORWARD -i wg0-client -j ACCEPT
PostDown = iptables -D FORWARD -i wg0-client -j ACCEPT; ip6tables -D FORWARD -i wg0-client -j ACCEPT
Address = 10.92.92.32/24
DNS = 10.92.92.1

[Peer]
PublicKey = *******************
Endpoint = 127.0.0.1:10443
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 16



SERVER:

udp2raw -s -l0.0.0.0:443 -r 127.0.0.1:445   -k "vpn_password" --raw-mode faketcp -a --fix-g
speederv2 -s -l127.0.0.1:445 -r 127.0.0.1:444  -f100:1 --mtu 1200

Wireguard:
[Interface]
Address = 10.92.92.1/24
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; ip6tables -D FORWARD -i wg0 -j ACCEPT
ListenPort = 444
PrivateKey = ***************

[Peer]
PublicKey = ***************
AllowedIPs = 10.92.92.0/24

**Comment by ShadowOfHarbringer** [comment]
I have also tried hard-to OpenVPN tunnel inside Wireguard tunnel, inside udp2raw tunnel.

OpenVPN in both  TCP and UDP modes, with low MTU and MSSFIX. Still not working.

At this point I seriously doubt it has to do with MTU. It must be some issue with packet ordering in HTTPS when using over wireguard tunneled through udp2raw.

Tried 3 browsers:
- Steam browser
- Firefox Browser
- Lynx Browser

When in HTTPS, DNS is resolved, browser shows "connecting", but forever hangs in "connecting state" and cannot connect.

**Comment by ShadowOfHarbringer** [comment]
I have now left just OpenVPN + udp2raw.... MTU is at 1200, Fragment at 1200.

HTTPS still not working in any browser.

Lynx browser is stuck at "Making https connection to wp.pl"

**Comment by ShadowOfHarbringer** [comment]
OK, the issue is ISP is apparently doing some kind of deep packet inspection.

I will close the issue for now.

**Comment by wannabecyborg** [comment]
I had a similar problem, I solved it by changing the ip of the remote server from 443 to any other

**Comment by 0x00111** [comment]
I also encountered the same problem. At 0.0.0.0/0, HTTPS cannot function properly and packet loss is very severe. I have now considered giving up on wg

**Comment by wangyu-** [comment]
>I had a similar problem, I solved it by changing the ip of the remote server from 443 to any other

this is a known problem, I don't have a elegant solution now, but I have noted the problem and the workaround inside this link:

https://github.com/wangyu-/udp2raw/wiki/Known-issues-and-solutions
