### ISSUE TITLE
cpu占用太高了

### ISSUE THREAD

**Issue by lersh** [wangyu-/udp2raw-tunnel#29]
现在在路由器上跑了ssr,kcptun,还有udp2raw，一看视频，cpu占用那个高啊，而且似乎udp2raw的占用是最高的，能不能使用一些低强度的加密算法，或者可以允许用户选择低强度的加密算法，来降低一些cpu的占用？

**Comment by wangyu-** [comment]
> 或者可以允许用户选择低强度的加密算法
认真读一下readme吧，本来就有的。用--cipher xor --auth simple

> 而且似乎udp2raw的占用是最高的
现在最新发布的release里有汇编加速版的加密了。arm上用arm_asm_aes，性能可以提高一倍（但是肯定还是--cipher xor更快）。

**Comment by lersh** [comment]
谢谢了
