### ISSUE TITLE
请问出现“500 内部服务器错误”如何修复？

### ISSUE THREAD

**Issue by lalalalualua** [wangyu-/udp2raw-tunnel#305]
安装后在设置页面处显示“500 内部服务器错误”，该如何修复呢？

udp2raw 隧道 - 设置
500 内部服务器错误
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute firstchild dispatcher target for entry '/admin/services/udp2raw'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/udp2raw/general'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'udp2raw/status'.
A runtime error occured: [string "/usr/lib/lua/luci/view/udp2raw/status.htm"]:4: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by zhaoxuzuzhi** [comment]
请问有解决办法了吗？我直接编译到固件上，会报错500，安装ipk正常
