### ISSUE TITLE
windows版本电脑进入休眠后,唤醒后进程KILL掉问题

### ISSUE THREAD

**Issue by CatMsg** [wangyu-/udp2raw-tunnel#309]
下面是启动命令

@echo OFF
%1 start mshta vbscript:createobject("wscript.shell").run("""%~0"" ::",0)(window.close)&&exit
@ping 127.0.0.1 -n 10 >nul
taskkill /f /im client_windows_amd64.exe
taskkill /f /im udp2raw.exe
taskkill /f /im speederv2.exe
taskkill /f /im tinymapper.exe
start /b client_windows_amd64.exe -l :123 -r XXXXX:XXXX -key "******" -crypt none -nocomp -mtu 1350 -sndwnd 20480 -rcvwnd 20480 -mode fast2
start /b udp2raw.exe -c -l127.0.0.1:3333 -rXXXXXX:XXXX -k "coding" --raw-mode faketcp
start /b speederv2.exe -c -l0.0.0.0:4444 -r127.0.0.1:3333 -k "coding" -f2:4 --mode 0 timeout 0
start /b tinymapper.exe -l0.0.0.0:4444 -r127.0.0.1:123 -t

**Comment by wangyu-** [comment]
暂时用这个方法解决一下：

https://github.com/wangyu-/udp2raw-tunnel/wiki/%E8%BF%9B%E7%A8%8B%E4%BF%9D%E6%B4%BB

**Comment by CatMsg** [comment]
> 暂时用这个方法解决一下：
> 
> https://github.com/wangyu-/udp2raw-tunnel/wiki/%E8%BF%9B%E7%A8%8B%E4%BF%9D%E6%B4%BB

挂掉的是客户端(windows)电脑的进程,非服务端

**Comment by wangyu-** [comment]
同样的原理windows也可以

**Comment by CatMsg** [comment]
> 同样的原理windows也可以

试了一下,已放弃,还是手动重启一下算了
