### ISSUE TITLE
问下如何编译ramips的版本

### ISSUE THREAD

**Issue by lersh** [wangyu-/udp2raw-tunnel#31]
我想在小米路由mini上运行，cpu是MTK 7620a，架构是ramips的，不知道如何编辑，想请教下，谢谢

**Comment by wangyu-** [comment]
用ar71xx版本试一下，如果不行再自己编译。

自己编译的话，readme里有编译教程。

**Comment by lersh** [comment]
我试过ar71xx版本不行，不能运行。
openwrt的SDK我也下载了，尝试按照readme的方法，改了makefile，但是便于提示mipsel-openwrt-linux-g++: warning: environment variable 'STAGING_DIR' not defined
不知道这个变量该在哪里定义啊？

**Comment by wangyu-** [comment]
那个不用管。没事的。

**Comment by wangyu-** [comment]
那个warning不用管。没事的。

**Comment by lersh** [comment]
呃，那然后就退出了，编译成功了？生成文件在什么地方？

**Comment by lersh** [comment]
好的，我看看生成的文件是不是可以使用

**Comment by wangyu-** [comment]
教程里原话：
```执行make cross，目录下生成udp2raw_cross文件。编译完成。```

我提醒一下，多次不仔细看readme，可能会被ban掉提问题的权利 = =。

**Comment by lersh** [comment]
Sorry，刚才看到了。我会再注意看下readme的
我看了下，发现生成的udp2raw_cross只有168K，和realse里的各个预编译版本容量差距很大。
放到路由器下运行，提示can't load library 'libstdc++.so.6'，
我仔细看了下readme，并没有发现如何将这些需要lib编译进最终可执行程序的方法，不知道能否告知一下，谢谢

**Comment by wangyu-** [comment]
你用make cross2编译一下。cross2编译出来的是静态的。 但是前提是你的toolchain带静态库。

**Comment by lersh** [comment]
好的，谢谢了，编译成功了
