### ISSUE TITLE
Tunnel traffic "firefox"

### ISSUE THREAD

**Issue by zoubane777** [wangyu-/udp2raw-tunnel#32]
Hello , i need some help to tunnel all the traffic using udp2raw i excuted udp2raw in the server and in the client but i have no clue how i can tunnel the traffic in firefox , thx for the project

**Comment by wangyu-** [comment]
Hi,zoubane777:
Web browsing is usualy TCP traffic. Udp2raw is a udp tunnel.If you want to tunnel TCP traffic you can use Openvpn+udp2raw.But you can also tunnel your TCP traffic  by only using OpenVpn.Udp2raw only helps to deal with UDP blocking or UDP Qos.

May I ask you a question,why do you want to use udp2raw to tunnel the traffic in firefox?

**Comment by zoubane777** [comment]
my Isp is blocking some websites , and none seems to work , i tried iodine "dns tunnel" ,vpn , and ssh but none seems to work  , so my question is can i use udp2raw like iodine ti tunnel my traffic through it ? and how to use it with OPenvpn ( and sorry i am not an expert ) iam just a noob :) thank you again for the reply

**Comment by wangyu-** [comment]
Sorry udp2raw cant do this directly. 

The SSH method should work,I suspect you didnt do it correctly.You can also try shadowsocks,google for it.

**Comment by zoubane777** [comment]
can i ask you how to configure udp2raw with openvpn ??

**Comment by wangyu-** [comment]
check:
https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/openvpn_guide.md
