### ISSUE TITLE
wireguard + udp2raw会使nat变成Symmetric

### ISSUE THREAD

**Issue by Ssssix40** [wangyu-/udp2raw-tunnel#356]
家里本来是fullcone，为了玩外网游戏使用wireguard+udp2raw会导致nat变成Symmetric
然后单纯wireguard则没有问题
请问是我设置的有问题么？
还是说udp2raw会增加nat
## server
wg0.conf
```conf
[Interface]
PrivateKey =
Address = 10.0.0.1/24
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 52540
DNS = 8.8.8.8
MTU = 1200
[Peer]
PublicKey = 
AllowedIPs = 10.0.0.2/32

```
```shell
nohup /root/app/udp2raw -s -l0.0.0.0:9898 -r 127.0.0.1:52540 --raw-mode faketcp -a -k password>/root/app/logs/udp2raw.log 2>&1 &
```
## clinet
wg0.conf
```conf
[Interface]
PrivateKey = 
Address = 10.0.0.2
DNS = 8.8.8.8
[Peer]
PublicKey = 
Endpoint = 127.0.0.1:3453
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
```
```shell
ip route add ip via $(ip route | awk '$1=="default" {print $3}')

nohup /root/udp2raw -c -r ip:9898 -l 127.0.0.1:3453 --raw-mode faketcp -k kiki >/root/udp2raw.log 2>&1 &
```

**Comment by Jimmy-Z** [comment]
这跟wireguard和udp2raw都没有关系，有两层NAT，服务器那边的也有NAT。

**Comment by Ssssix40** [comment]
> 这跟wireguard和udp2raw都没有关系，有两层NAT，服务器那边的也有NAT。

如果是服务器有nat的话, 单纯使用wireguard应该不会是nat1吧
我这边测试单纯wireguard是nat1的

**Comment by wangyu-** [comment]
我觉得理论上udp2raw不会影响nat类型。 

不过之前有人反映过udp2raw+$$和只用$$比，会改变NAT类型。后来发现是$$的一个option和tunnel(不限于udp2raw)不太兼容，关掉以后NAT类型就一样了。 (所以我也不太好下结论说肯定不会影响)

如果要继续追查原因：
1. 多测试几次，确保测试结果是稳定的。
2. 测试一下 tinyportMapper+ wireguard会不会影响nat类型。   如果也会影响，那可能是wireguard对tunnel的兼容问题导致的。 如果不会影响，那很可能是mtu问题导致的。

**Comment by Ssssix40** [comment]
> 1. 多测试几次，确保测试结果是稳定的。
> 2. 测试一下 tinyportMapper+ wireguard会不会影响nat类型。   如果也会影响，那可能是wireguard对tunnel的兼容问题导致的。 如果不会影响，那很可能是mtu问题导致的。

我今天在不同时段进行了多次测试：
1. 目前可以确定跟udp2raw，应该关系不大。之前之所以会测试裸wireguard nat1, wg+udp2raw nat4的原因猜测是我当时没有控制好变量，因为我发现一些stun服务器可以得到nat1的结果，比如google， 但是一些服务器却是nat4，比如qq的（当然大部分为nat4），而这些可以得到nat1结果的服务器，无论在什么情况下都会得到nat1（包括裸wg，wg+udp2raw，wg+tinyportmapper）。
2. wireguard的使用甚至有时候会影响到我腾讯云的vps的nat，在开启wg之前是nat1，开启之后变成了nat4。（这一点存疑，我怀疑是腾讯云本身nat就有问题，因为有一次我没有开启任何服务，pystun的结果也是nat4）
3. 然后我尝试修改mtu, 1000, 1200, 1420,这些值都无法改变结果。

因为跟udp2raw关系不大， 所以我暂时close了。
谢谢回复~

**Comment by Ssssix40** [comment]
解决了。
大致的原因是：

>TLDR: Linux内核树上未实现真正意义上的Full Cone NAT，Linux的 SNAT/MASQUERADE（以iptables的配置为例）均是Symmetric NAT。

[原文](https://blog.chionlab.moe/2018/02/09/full-cone-nat-with-linux/)

而wireguard需要用到`iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`。

上面原文的作者解决了这一个问题，具体的解决方法[点我](https://www.jianshu.com/p/88e7cd6a0c95)

**Comment by Jimmy-Z** [comment]
所以就是我猜测的原因，服务器那一层NAT导致了问题。
