### ISSUE TITLE
ICMP mode need to add port option?

### ISSUE THREAD

**Issue by Handsome1080P** [wangyu-/udp2raw-tunnel#357]
I am using ICMP mode,need I add port option both server and client side?Real ICMP need not port.

**Comment by Handsome1080P** [comment]
Ps. Remote port

**Comment by wangyu-** [comment]
For client's `-r` and server's `-s` option in ICMP mode, you do need to follow the `ip:port` format. But the `port` simply has no effect, you can write any port, or just 0, no difference.

**Comment by Handsome1080P** [comment]
> For client's `-r` and server's `-s` option in ICMP mode, you do need to follow the `ip:port` format. But the `port` simply has no effect, you can write any port, or just 0, no difference.

got,thx
