### ISSUE TITLE
不会编译，求编译mac 和 windows 文件

### ISSUE THREAD

**Issue by mengzhihoing** [wangyu-/udp2raw-tunnel#36]
不会编译，求编译mac 和 windows 文件，thx

**Comment by wangyu-** [comment]
不支持编译mac和windows的binary。

用release里的虚拟机文件。

**Comment by wangyu-** [comment]
https://github.com/wangyu-/udp2raw-tunnel/releases

**Comment by mengzhihoing** [comment]
@wangyu- 感谢，mac的虚拟机parallels不支持那两种类型的虚拟机文件，看来只能路由器或windows上了。

**Comment by wangyu-** [comment]
装个virtualbox,只要100mb

**Comment by mengzhihoing** [comment]
@wangyu- 原来mac也有virtualbox，安装了，但是不大明白这个怎么用，我用virtualbox 导入虚拟机，然后选了 openwrt12.09  ，然后这个怎么配置？看文档貌似不是特别明白？没有运行命令？怎么绑定vps的ip端口，请指教，谢谢。

**Comment by wangyu-** [comment]
这个虚拟机里面的运行的openwrt，其实就是个精简版的Linux。跟桌面linux类似的用法。

直接在虚拟机的图形界面打命令进去，启动udp2raw client，连接到你的server。然后再从虚拟机外面访问udp2raw client监听的端口。

openwrt自带ssh服务器，也可以ssh进去。ssh进去的好处是可以用复制粘贴。账号root,密码123456

**Comment by diigu** [comment]
查了下用的epoll，只支持linux系，而mac用的是kqueue，所以无法在mac和windows等无epoll支持的系统上compile。
