### ISSUE TITLE
g_ip_id_counter overflow

### ISSUE THREAD

**Issue by andylau004** [wangyu-/udp2raw-tunnel#365]
English Only (except for bug reporting).
文件:   network.cpp
函数:   int send_raw_ip(raw_info_t &raw_info,const char * payload,int payloadlen)
```
unsigned short g_ip_id_counter=0;
iph->id = htons (g_ip_id_counter++); //Id of this packet
```

g_ip_id_counter
是 uint16 类型，65535次执行后，会溢出吧

**Comment by wangyu-** [comment]
no problem, it's as expected. when it overflows it just wrap back to zero.
