### ISSUE TITLE
roaming support?

### ISSUE THREAD

**Issue by bitching** [wangyu-/udp2raw-tunnel#375]
I'm using wireguard to connect 3 locations which have dynamic public ip.
so the roaming feature of wireguard is important.
but obviously it can not co-exist with UDPSpeeder+UDP2Raw.
is there any chance to achieve roaming in UDP2raw?

**Comment by wangyu-** [comment]
I am not very familiar with the roaming feature of wireguard.  Could you plz briefly explain what the roaming feature is, and how does UDPspeeder and udp2raw break this feature?   Also, is there any known tunnel that can work well with wireguard without breaking the roaming feature? 

>I'm using wireguard to connect 3 locations which have dynamic public ip.

If you just want to connect to a server with dynamic IP, dynamic DNS is one possible way.

**Comment by bitching** [comment]
assume alice(1.1.1.1)----wg----bob(2.2.2.2) functioning normally.
when bob's ip changed to 3.3.3.3, alice will acknowledge bob's is now 3.3.3.3 after bob communicates with alice, so there are no further problems.

now with UDPSpeeder+UDP2Raw, alice needs to specify udp2raw to connect 2.2.2.2.
when bob's ip changed to 3.3.3.3, alice needs to manually specify udp2raw to connect 3.3.3.3.

dynamic dns is a workaround, but not good enough.
it needs to restart udp2raw regularly, and operator's dns cache, dns delay will be troublesome.
the availability will be much lower than roaming.

**Comment by wangyu-** [comment]
Let me make sure I understand your example correctly.

1. How does Alice know Bob's IP is 2.2.2.2 at the begining?  (seems like you still need a way similiar to dynamic DNS at the begining, or you have to do something manually)

2. If Alice is behind NAT, after Bob change its IP to 3.3.3.3 (from 2.2.2.2), how could Bob let Alice know the new IP? (seems like you example only works when alice is not behind NAT, or alice's NAT is full-cone)

**Comment by bitching** [comment]
1.dynamic dns is for convenience but not required, i actually use it.
2.it seemed that without assistance. the workaround is a bit complicated but doable. and it's off topic. 
(https://www.jordanwhited.com/posts/wireguard-endpoint-discovery-nat-traversal/)
(https://github.com/pirate/wireguard-docs#NAT-to-NAT-Connections)

if we use wireguard+UDPSpeeder+UDP2Raw, the roaming feature relies on udp2raw.

**Comment by wangyu-** [comment]
It's important to mention NAT, for a program to work gracefully with tunnel, usually the program should be NAT-friendly.  From my experience, if a program is not NAT-friendly, then it almost always means the program is not tunnel-friendly.

For me, the problem you mentioned is not restricted to udp2raw/UDPspeeder, it happens with any tunnel. The essential problem is the roaming feature of wireguard is not tunnel-friendly.  I am afraid the problem can't be solved easily, unless:

1. udp2raw implements it's own roaming feature. (in this way you do not even need wireguard to have roaming feature anymore....  everthing behind udp2raw will automatically be roaming)

2. implement the feature of udp2raw/UDPspeeder into wireguard

>for me, all my nodes are not behind nat.

I see all your nodes are not behind nat.  Although the roaming feature of wireguard works very well for your case, it's not a general solution that always works for every network environment (especially it fails when alice is behind NAT, which is not rare). I am not planning to implement the roaming feature into udp2raw itself in the near feature.

**Comment by bitching** [comment]
it's a pity.
as far as i know, there is no way to make nat to nat connections without assistance`(such as stun and turn)`.
also there is no universal approach except server forwarding`(as n2n's supernode)`.
thanks for your patient relpy anyway.
still wait for this in the future.

**Comment by wangyu-** [comment]
I will consider implementing the roaming feature in future(not the near future), but it's not guaranteed.

Precisely speaking, the roaming feature you mentioned is server-side roaming (server's IP is changed). According to the document, wireguard supports both client-side roaming and server-sider roaming.  At the moment, udp2raw actually already supports client-side roaming. Server-side roaming is a bit more tricky, especially the current iptables rule generated by udp2raw is not very compatible with it.  Another potential problem is TCP is one-to-one (and that affects fakeTCP), even though the server-sider roaming is implemented, it might not be able to work when the client is behind full-cone NAT(depends on how the NAT middle-ware is implemented).

**Comment by bitching** [comment]
got it.
thanks for explanation.
will keep an eye on this project.
