### ISSUE TITLE
启动服务时，报错提示 failed to parse

### ISSUE THREAD

**Issue by OXERIS** [wangyu-/udp2raw-tunnel#376]
环境：服务部署在软路由的openwrt上，网内设备“192.168.50.64” 已将软路由opwnwrt设置为网关，通过软路由上网
 如题
![image](https://user-images.githubusercontent.com/18722082/104870324-2f0e8280-5983-11eb-924e-86d9fca4a3d1.png)

**Comment by wangyu-** [comment]
There is obviously a format issue in the `-r` option,

**Comment by smilence86** [comment]
我也遇到，项目首页示例迷惑人：
![image](https://github.com/wangyu-/udp2raw/assets/6102831/afef90b4-a3a3-44aa-8eca-206927204563)

-l参数后面缺少空格，导致解析失败
![image](https://github.com/wangyu-/udp2raw/assets/6102831/b3c135ac-8281-4430-b764-99d67192e21f)

**Comment by wangyu-** [comment]
>我也遇到，项目首页示例迷惑人

跟系统有关，linux上加不加空格都行。

OP的问题是多加了个冒号，跟你的明显不是一回事。

**Comment by OXERIS** [comment]
> > 我也遇到，项目首页示例迷惑人
> 
> 跟系统有关，linux上加不加空格都行。
> 
> OP的问题是多加了个冒号，跟你的明显不是一回事。

谢谢
