### ISSUE TITLE
能否以这个lede 为母本进行集成

### ISSUE THREAD

**Issue by spamering** [wangyu-/udp2raw-tunnel#38]
http://firmware.koolshare.cn/LEDE_X64_fw867/ 
这里的 lede 做的比较好  能否以 这个 lede 为模板 进行集成

**Comment by wangyu-** [comment]
请问你说的集成是什么意思

如果是说在lede上运行的话，只需要把udp2raw拷贝过去运行就可以了（如果udp2raw_amd64不能直接运行，可能需要自己编译，也很简单，有教程）。

如果是说集成到这个固件里面，作为固件的一部分。这个只有固件的维护者们才能做到了，你应该把这个问题提交给固件的维护者。

**Comment by spamering** [comment]
可能需要自己编译，也很简单，有教程 
能不能发一下教程

**Comment by wangyu-** [comment]
https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/build_guide.zh-cn.md

**Comment by spamering** [comment]
在lede路由里编译 我不会  在linux 我已经用上了

**Comment by wangyu-** [comment]
一般的路由器不支持在路由器里编译，需要交叉编译，具体过程看教程吧。

**Comment by spamering** [comment]
兄弟有没有qq

**Comment by spamering** [comment]
我想找你定制一个系统

**Comment by wangyu-** [comment]
我不怎么用qq，我profile里面有gmail地址。可以用hangout或者直接发邮件跟我联系。

**Comment by wangyu-** [comment]
udp2raw和udpspeeder已被这个固件集成。
