### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wangyu-/udp2raw-tunnel#39]
I would like to point out that identifiers like “[`_ENCRYPTION_H_`](https://github.com/wangyu-/udp2raw-tunnel/blob/0266163b126956ca43be41e655daf80ce2ee54b2/encrypt.h#L1 "Update candidate")” and “[`_MD5_H_`](https://github.com/wangyu-/udp2raw-tunnel/blob/687666cf05dd8b6e4f22a863034782266f6eeabd/lib/md5.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wangyu-** [comment]
thx for pointing this out,fixed.
