### ISSUE TITLE
[Feature Request] AES-GCM instead of CBC

### ISSUE THREAD

**Issue by epicgoldenlife** [wangyu-/udp2raw-tunnel#392]
Is it possible that traffic can be encrypted with AES in GCM mode? Not only is it a stream cipher, which makes it appropriate for encrypting UDP streams, but it is also authenticated encryption. This beats CBC, which is a block cipher, and does not have authenticated encryption.

Also, AES GCM is shown to perform much better than CBC, especially devices that support AES NI.

**Comment by wangyu-** [comment]
We have already supported AES CFB, which is a stream cipher.  Although CBC/CFB itself is only for encryption, we have HMAC-SHA1 for authentication. 
Assume used correctly,  I do not see any evidence of AES-CFB+HMAC-SHA1 being weaker than AES-GCM.
With CBC/CFB, we already supported AES NI. (use `udp2raw_amd64_hw_aes`).

>AES GCM is shown to perform much better than CBC

How much better? Is that also true for CFB? Would you please provide the reference?
