### ISSUE TITLE
Fake TCP Latency Do Not Match Tcping Latency

### ISSUE THREAD

**Issue by Handsome1080P** [wangyu-/udp2raw-tunnel#397]
**Client to server tcping latency: Average 40-60ms**
![Untitled.png](https://i.loli.net/2021/06/02/LwrfW45JKukecBP.png)
**Client to server ICMP: Average 30-50ms**
![2.png](https://i.loli.net/2021/06/02/9IuJ8KYvClMagZh.png)
**Server Commands:**
`command=/root/speed/udp2raw -s -l0.0.0.0:13720 -r127.0.0.1:10 --raw-mode faketcp --cipher-mode aes128cbc --auth-mode md5 --seq-mode 3 --log-level 4 -k "01010011" --dev eth0 --sock-buf 10240 --force-sock-buf`

`command=/usr/local/bin/tinyvpn -s -l 127.0.0.1:10 --sub-net 10.4.0.0 --tun-dev tun4 --report 10 --sock-buf 10240 --mode 0 --mtu 1250 -f10:6 --timeout 3 --disable-obscure --log-level 0`

`-A INPUT -p tcp -m multiport --dports 13720 -j DROP`

**Client Commands:**
`command=/usr/local/bin/udp2raw -c -l127.0.0.1:10 -r2.2.2.2:13720 --raw-mode faketcp --cipher-mode aes128cbc --auth-mode md5 --seq-mode 3 --log-level 4 -k "01010011" --sock-buf 10240 --force-sock-buf`

`command=/usr/local/bin/tinyvpn -c -r 127.0.0.1:10 --sub-net 10.4.0.0 --tun-dev vpn1 --report 10 --sock-buf 10240 --mode 0 --mtu 1250 -f10:6 --timeout 3 --disable-obscure --log-level 0`

`-A INPUT -s 2.2.2.2/32 -p tcp -m multiport --sports 13720 -j DROP`

**But if I ping 10.4.0.1 from the vpn1 interface,I got about 70-100ms latency.I have try to change my local public IP or just restart udp2raw,tcping latency and ICMP no change,but ping from vpn1 interface latency can be lower or higher.I don't know why.I think if this is ISP route balance's problem,but TCPing latency always no change.I have try to use real TCP tunnel to test,the latency is 45ms with some package loss and no latency change**
![image.png](https://i.loli.net/2021/06/02/4Nx2B6ewt5qLhjU.png)

**Client Logs below:** 
![4.png](https://i.loli.net/2021/06/02/y5YjcDsrHLvXSC6.png)
**Server logs below**
![wq.png](https://i.loli.net/2021/06/02/L6CDmXl85buAEIs.png)

**Comment by wangyu-** [comment]
I assume you mean `latency` by saying `legacy`.

>but ping from vpn1 interface legacy can be lower or higher.I don't know why.I think if this is ISP route balance's problem

This is as expected, I had similar experiences, I believe it's caused by route balance.

>but TCPing legacy always no change

I am not sure. But TCPing measures the latency by `SYN`  and `SYN-ACK` packets, it doesn't send TCP payloads. Possibly the ISP is giving the TCP handshaking message higher priority. 

>But if I ping 10.4.0.1 from the vpn1 interface,I got about 70-100ms legacy.

You are using `timeout 3` on boths sides of tinyfecVPN, it adds 6ms latency, although it doesn't explain everything. 

>I have try to use real TCP tunnel to test,the legacy is 45ms with some package loss and no legacy change

I am not sure how you tested it. If the tunnel is real TCP, it should be reliable. For my understanding packet loss shouldn't be observed.

**Comment by Handsome1080P** [comment]
> I assume you mean `latency` by saying `legacy`.
> 
> > but ping from vpn1 interface legacy can be lower or higher.I don't know why.I think if this is ISP route balance's problem
> 
> This is as expected, I had similar experiences, I believe it's caused by route balance.
> 
> > but TCPing legacy always no change
> 
> I am not sure. But TCPing measures the latency by `SYN`  and `SYN-ACK` packets, it doesn't send TCP payloads. Possibly the ISP is giving the TCP handshaking message higher priority.
> 
> > But if I ping 10.4.0.1 from the vpn1 interface,I got about 70-100ms legacy.
> 
> You are using `timeout 3` on boths sides of tinyfecVPN, it adds 6ms latency, although it doesn't explain everything.
> 
> > I have try to use real TCP tunnel to test,the legacy is 45ms with some package loss and no legacy change
> 
> I am not sure how you tested it. If the tunnel is real TCP, it should be reliable. For my understanding packet loss shouldn't be observed.

I am testing use TCP VPN, just ping the vpn gateway.The real TCP latency is stable,the value between 40 to 50ms and with some packages lost.Otherway,I test use Udp2raw ICMP mode,but can't match the real ICMP latency value (Just Ping).So what is the issue?
