### ISSUE TITLE
iptables把服务端的端口DROP了,也能连通

### ISSUE THREAD

**Issue by thankeyes** [wangyu-/udp2raw-tunnel#40]
iptables把服务端的端口DROP了,为了只让自己特定的IP连,然而其他IP也能连通,这是为什么?
另外客户端的key和服务端不一致也能连通,不过会有很多丢包.

命令只加了--cipher-mode none,其他和github里的列子一样

**Comment by wangyu-** [comment]
>iptables把服务端的端口DROP了,为了只让自己特定的IP连,然而其他IP也能连通,这是为什么?
另外客户端的key和服务端不一致也能连通,不过会有很多丢包.

udp2raw在2层收包，iptables工作在3层，udp2raw收包不受iptables影响。

如果使用了--lower-level选项，那么发包也是在2层，收发包都不受iptables影响。

你的情况，首先确保没使用`--lower-level`。然后在iptables的output链里把 **发送** 屏蔽掉。可以达到你的目的（只允许指定的ip连接）。在input链屏蔽掉 **接收** 是不会有效果的。

>另外客户端的key和服务端不一致也能连通,不过会有很多丢包.
>命令只加了--cipher-mode none,其他和github里的列子一样

加了`--cipher-mode none`以后，key相关的功能就被关掉了。不建议使用`--cipher-mode none`

**Comment by thankeyes** [comment]
可以考虑加入指定IP才能收包限制功能不?
测试了,服务端-l 0.0.0.0 不能改成指定ip

**Comment by wangyu-** [comment]
`-l 0.0.0.0`这个决定的是server bind在哪个ip地址。跟你说的功能不是一回事。

>可以考虑加入指定IP才能收包限制功能不?用output来限制有点膈应.

用iptables就能实现类似的功能，感觉没有在udp2raw里面再做一次的必要。暂时没有做的打算。
