### ISSUE TITLE
openvz+vmware用faketcp不通

### ISSUE THREAD

**Issue by PHCSJC** [wangyu-/udp2raw-tunnel#41]
环境：
服务器端：openvz+centos6.8_x64+kcptun
客户端：win7+openwrt12.09_x86_vmware_image_with_udp2raw_pre_installed

1.--raw-mode用faketcp不通
2.--raw-mode用udp可以通，说明整个配置是没问题的
3.用ssh服务测试的
4.-a 参数去掉也不行
5.命令是完全参照示例里写的，没有添加其它参数
6.我不确定是否和openvz有关，只是猜测

**Comment by wangyu-** [comment]
虚拟机网卡是不是桥接模式？

**Comment by PHCSJC** [comment]
@wangyu-  确实是这个问题，之前是nat模式，换成桥接后好了，原来必须得桥接，谢谢！

**Comment by PHCSJC** [comment]
另一个请教：后期会增加windows客户端吗？还是windows上无法实现必须得linux呢？

**Comment by wangyu-** [comment]
在windows上实现一个困难是需要改得东西比较多，维护起来麻烦。

另一个困难是windows没iptables，用什么东西替代我暂时也没有想法。

短期不会有windows原生客户端。

**Comment by PHCSJC** [comment]
我这速度明显提高了很多，1080p完全没问题。
再有一个疑惑：我开启的bbr，对udp2raw-tunnel会有加速作用吗？

**Comment by wangyu-** [comment]
>再有一个疑惑：我开启的bbr，对udp2raw-tunnel会有加速作用吗？

没作用。但是不冲突，可以开。

**Comment by PHCSJC** [comment]
再请教，我在docker下运行，报这个错误，是不支持吗？还是哪里不对？
[2017-09-04 15:18:35][INFO]argc=10 /root/udp2raw/udp2raw_amd64 -s -l 0.0.0.0:9080 -r 127.0.0.1:443 -k dcOa145I0NoK --raw-mode faketcp 
[2017-09-04 15:18:35][INFO]important variables: log_level=4:INFO raw_mode=faketcp cipher_mode=aes128cbc auth_mode=md5 key=dcOa145I0NoK local_ip=0.0.0.0 local_port=9080 remote_ip=127.0.0.1 remote_port=443 source_ip=0.0.0.0 source_port=0 socket_buf_size=1048576 
[2017-09-04 15:18:35][INFO]const_id:3c1787b6
[2017-09-04 15:18:35][FATAL]SO_SNDBUFFORCE fail

**Comment by wangyu-** [comment]
你下载这个版本试一下，然后贴一下日志。
https://github.com/wangyu-/udp2raw-tunnel/files/1267468/udp2raw_amd64.zip

**Comment by PHCSJC** [comment]
报错：
[2017-09-04 15:29:36][INFO]argc=10 /root/udp2raw/udp2raw_amd64 -s -l 0.0.0.0:9080 -r 127.0.0.1:443 -k dcOa145I0NoK --raw-mode faketcp 
[2017-09-04 15:29:36][INFO]important variables: log_level=4:INFO raw_mode=faketcp cipher_mode=aes128cbc auth_mode=md5 key=dcOa145I0NoK local_ip=0.0.0.0 local_port=9080 remote_ip=127.0.0.1 remote_port=443 source_ip=0.0.0.0 source_port=0 socket_buf_size=1048576 
[2017-09-04 15:29:36][INFO]const_id:26bdfd4a
[2017-09-04 15:29:36][FATAL]SO_SNDBUFFORCE fail  socket_buf_size=1048576  errno=Operation not permitted

**Comment by wangyu-** [comment]
这个账户是root吗？貌似你的机器不允许SO_SNDBUFFORCE这个操作。

用--sock-buf 100试一下，看是否能运行。

**Comment by PHCSJC** [comment]
加了--sock-buf 100这个还是报错。docker启动没有root权限，这样不行吗？
[2017-09-04 15:35:14][INFO]argc=12 /root/udp2raw/udp2raw_amd64 -s -l 0.0.0.0:9080 -r 127.0.0.1:443 -k dcOa145I0NoK --raw-mode faketcp --sock-buf 100 
[2017-09-04 15:35:14][INFO]important variables: log_level=4:INFO raw_mode=faketcp cipher_mode=aes128cbc auth_mode=md5 key=dcOa145I0NoK local_ip=0.0.0.0 local_port=9080 remote_ip=127.0.0.1 remote_port=443 source_ip=0.0.0.0 source_port=0 socket_buf_size=102400 
[2017-09-04 15:35:14][INFO]const_id:abb195ae
[2017-09-04 15:35:14][FATAL]SO_SNDBUFFORCE fail  socket_buf_size=102400  errno=Operation not permitted

**Comment by PHCSJC** [comment]
[2017-09-04 15:48:32][INFO][main.cpp,func:process_arg,line:2802]argc=11 /root/udp2raw/udp2raw_amd64 -s -l 0.0.0.0:9080 -r 127.0.0.1:443 -k dcOa145I0NoK --raw-mode faketcp --log-position 
[2017-09-04 15:48:32][INFO][main.cpp,func:process_arg,line:3098]important variables: log_level=4:INFO raw_mode=faketcp cipher_mode=aes128cbc auth_mode=md5 key=dcOa145I0NoK local_ip=0.0.0.0 local_port=9080 remote_ip=127.0.0.1 remote_port=443 source_ip=0.0.0.0 source_port=0 socket_buf_size=1048576 
[2017-09-04 15:48:32][INFO][main.cpp,func:main,line:3390]const_id:219e4ad
[2017-09-04 15:48:32][FATAL][network.cpp,func:init_raw_socket,line:204]SO_SNDBUFFORCE fail  socket_buf_size=1048576  errno=Operation not permitted

**Comment by wangyu-** [comment]
[udp2raw_binaries.tar.gz](https://github.com/wangyu-/udp2raw-tunnel/files/1274074/udp2raw_binaries.tar.gz)

**Comment by PHCSJC** [comment]
可以了，非常感谢，同时加了这个参数--seq-mode 0才稳定。

**Comment by wangyu-** [comment]
`--seq-mode 0`这个应该不用吧，加了这个反而会有明显的特征，容易被封掉。
你觉得这个稳定可能是运气因素造成的。
建议用`--seq-mode 1`或`--seq-mode 2`.

**Comment by PHCSJC** [comment]
好的，我试试。请问1和2是什么意思？

**Comment by wangyu-** [comment]
`--seq-mode 0`表示关掉tcp序号的模拟。
`--seq-mode 1`表示模拟不丢包情况下的tcp序号。
`--seq-mode 2`假装有一定丢包，序号有时增长有时不涨。

**Comment by PHCSJC** [comment]
我有一个nat的server，1是默认，试了很多次确实不稳定，网页一打开就断，改成0就可以了，我再试试2
我另一台非nat的服务器，没有加--seq-mode这个参数没有问题。

**Comment by wangyu-** [comment]
nat的server是说阿里云的1:1nat吗？

**Comment by PHCSJC** [comment]
不是， 一个不知名的。

**Comment by wangyu-** [comment]
麻烦你把这个vps供应商的名字发到我邮箱里 wangyucn@gmail.com

哪天有时间我注册一个试试，看看是什么原因。

**Comment by PHCSJC** [comment]
发你邮箱了

**Comment by wangyu-** [comment]
多谢

**Comment by PHCSJC** [comment]
刚试了参数2几分钟，能打开，但感觉好像速度要慢些，不知道是否是错觉。

**Comment by wangyu-** [comment]
可以用www.speedtest.net之类的网站测速试一下。

**Comment by PHCSJC** [comment]
又试了下参数1，确实不行，又断了。

**Comment by wangyu-** [comment]
>又试了下参数1，确实不行，又断了。
了解了。多谢反馈。

**Comment by PHCSJC** [comment]
现在的测试是：
1.一个nat server+一个docker，用0正常，用1不行，用2好像有些慢。
2.另一个普通的server，默认就正常。

**Comment by PHCSJC** [comment]
我的docker的用户名和密码发你邮箱了，你先拿去测试吧，可以随意kill任何进程。

**Comment by wangyu-** [comment]
多谢，我已经连上去在测试了。

**Comment by wangyu-** [comment]
发布了一个新版。https://github.com/wangyu-/udp2raw-tunnel/releases/edit/20170906.0

预计不需要`--seq-mode 0`就可以正常运行。

**Comment by PHCSJC** [comment]
@wangyu- 可以了，速度飞起。

**Comment by PHCSJC** [comment]
@wangyu- 查看是否支持aes的命令对吗？aes的性能提升大概有多少呢？
grep -m1 -o aes /proc/cpuinfo

**Comment by wangyu-** [comment]
硬件加速版的AES有好几倍的性能提升。 具体见#15， 里面有个性能测试。

汇编加速版的也至少有50%的性能提升。

你用的是amd64的cpu是吧。你下载udp2raw_amd64_hw_aes运行一下试试，如果可以运行那就是支持了。

**Comment by wangyu-** [comment]
`grep -m1 -o aes /proc/cpuinfo`

这个我也不清楚。AES加速相关的代码是 @linusyang 写的，不确定是否这里显示出的AES支持就是他用的那个方法。目前最好的办法是运行一下试试，AES加速版是单独的binary，如果不支持会运行不了。

**Comment by PHCSJC** [comment]
@wangyu- 试了aes版本的，可以运行，谢谢！

**Comment by PHCSJC** [comment]
目前windows要开启虚拟机的方法还是稍显麻烦，有些人可能都没听说过，看到虚拟机可能就望而却步了，还是建议有更简单的直接运行的客户端。

**Comment by wangyu-** [comment]
这个已经加到 #17 的contribute guide里了。

这个需要改的东西比较多，window下的开发我自己也不熟悉，只能等别人贡献代码了。

**Comment by wangyu-** [comment]
@PHCSJC 
你好，我有个问题。我上次登陆到你的docker vps上面去调试，发现 -a选项是没法添加iptables的，就算自己手动打命令运行iptables也不可以。

后来只好放弃添加iptables规则，直接运行。但是我观察到，client这端是不会收到RST包的（正常情况下只有在server端添加了iptables规则才有这样的效果）。你这个server是NAT的，我猜你大概在VPS的WEB界面上对9080配置过端口映射。现在我想问一下，你是否有通过某些办法对9080添加了udp2raw生成的iptables规则？

**Comment by PHCSJC** [comment]
@wangyu- 你是否有通过某种办法对9080添加了udp2raw所需的iptables规则？没有，我只是启用了9080端口，没有其它任何配置。
这个docker没有完整的root的权限，所以使用不了iptables。

**Comment by wangyu-** [comment]
@PHCSJC 多谢，了解了。

**Comment by PHCSJC** [comment]
我的路由器是斐讯k2p，刷的官改ROM，执行udp2raw时报错，是哪里操作不对吗？
root@K2P:/tmp# ./udp2raw_mips34kc -h
./udp2raw_mips34kc: line 1: syntax error: unexpected "("

**Comment by wangyu-** [comment]
> ./udp2raw_mips34kc: line 1: syntax error: unexpected "("

binary选择的不对。查一下cpu架构。如果没有合适的就自己编译，参考readme里面的编译教程。

**Comment by PHCSJC** [comment]
mt7621是mips架构的，用udp2raw_mips34kc应该没有错吧？再就是不会编译喔。

**Comment by wangyu-** [comment]
貌似你这个路由器的CPU运行在'little endian'模式，我编译的那个是'big endian'的。

编译教程： https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/build_guide.zh-cn.md

**Comment by PHCSJC** [comment]
好吧，这个对于我来说难道太大，我还是等高人适配吧。

**Comment by wangyu-** [comment]
@PHCSJC 

我新发布了一版release.增加了'little endian'的mips binary.

https://github.com/wangyu-/udp2raw-tunnel/releases

文件名：udp2raw_mips24kc_be和udp2raw_mips24kc_be_asm_aes.

不保证可以用，我手上没有可测试的环境。

**Comment by PHCSJC** [comment]
@wangyu- 
k2p上测试的udp2raw_mips24kc_le_asm_aes，没有问题，给你点个赞！

**Comment by wangyu-** [comment]
多谢反馈。
>udp2raw_mips24kc_be和udp2raw_mips24kc_be_asm_aes.

是udp2raw_mips24kc_le和udp2raw_mips24kc_le_asm_aes。

前面的写错了。

**Comment by PHCSJC** [comment]
看1080p视频，CPU 9%-15%，这个负载完全可以正常使用。

**Comment by PHCSJC** [comment]
小米路由器mini(mt7620)：默认参数，看1080p视频，CPU 40%-60%。单个用户没问题。

**Comment by wangyu-** [comment]
>小米路由器mini（mt7620）：udp2raw_mips24kc_le_asm_aes，默认参数，看1080p视频，CPU 40%-60%。单个用户没问题。

多谢反馈。

另外，看1080p视频这样测试出来的结果可能不是最准确的。因为YouTube不会尝试一直打满你的带宽，有时候Youtube在缓冲，有时候Youtube是空闲的，测出来结果可能会偏低。

测性能可以在server 用 `iperf3 -s` ，在client用 `iperf3 -c <server_ip>  -P30 -t100`和`iperf3 -c <server_ip>  -P30 -R -t100`，这样iperf3会尝试打满你的带宽。

**Comment by wangyu-** [comment]
> 我只是用来看看视频、搜索。速度我观察了下

下载大文件观察也可以，我觉得比开Youtube观察准确。

>iperf3不会用喔，抱歉。

没事，我只是顺便说下YouTube测CPU这个方法可能不是很可靠。

**Comment by PHCSJC** [comment]
下载了个大文件试了下，50M带宽打满，小米路由器mini上cpu占用率40%-50%

**Comment by PHCSJC** [comment]
昨天晚上server进程崩溃了，看发布了新版本20170911.0，是解决的这个问题吗？

**Comment by wangyu-** [comment]
>昨天晚上server进程崩溃了

崩溃是指程序自己退出了吗？具体现象是什么。

>看发布了新版本20170911.0，是解决的这个问题吗？

昨天修的那个bug会导致性能问题，极端情况下会导致server连不上，但是不会退出。过几分钟后等有问题的连接被回收掉之后server会自己活过来。

>昨天晚上server进程崩溃了
我这边最近一个月都没观察到崩溃，server是vultr日本512mb内存。

建议运行一下`ulimit -c unlimited`，这样程序崩溃后会在当前目录产生一个core文件。把这个文件传给我，可以用它找到崩溃的原因。

**Comment by PHCSJC** [comment]
kcptun，ssr都还在，就udp2raw进程没了。
今天刚更新的0911版本，目前未出现崩溃。
运行了ulimit -c unlimited，再观察看看。

**Comment by wangyu-** [comment]
在这个问题查明之前，可以用这个脚本：
```
# /bin/sh
while true
do
xxxxxxxxxxxxxxxxxxxxxx//运行udp2raw
sleep 10
done
```
这样在udp2raw退出后会自动重新运行。

**Comment by PHCSJC** [comment]
好的，谢谢

**Comment by linhua55** [comment]
@wangyu- 
> 另一个困难是windows没iptables，用什么东西替代我暂时也没有想法。

可借鉴 finalSpeed的方法：
https://github.com/Chion82/kcptun-raw/issues/2#issue-203957142

**Comment by wangyu-** [comment]
@linhua55 

好方法，收藏了。

**Comment by PHCSJC** [comment]
期待早日出win版本

**Comment by PHCSJC** [comment]
好像在更新0911版本后，打开网页的速度慢了。

**Comment by wangyu-** [comment]
>好像在更新0911版本后，打开网页的速度慢了。

我用iperf3测了一下，结果跟之前是一样的。可能是网络本身的问题，再观察观察吧。

**Comment by PHCSJC** [comment]
好的，再观察看看。

**Comment by PHCSJC** [comment]
又测了一下，发现如果在看视频的同时去看别的走udp2raw的网站，延时会大，估计有0.5-2秒吧，而用kcptun+ss就不会有这么明显。

**Comment by PHCSJC** [comment]
实际上建立的不是udp连接，是raw socket的连接，因为使用了信道复用(multiplex)的方法，下层连接只有一条，而且目前只能是一条。

刚看到这个，和这个是否有些关系呢？

**Comment by wangyu-** [comment]
>又测了一下，发现如果在看视频的同时去看别的走udp2raw的网站，延时会大，估计有0.5-2秒吧，而用kcptun+ss就不会有这么明显。

有延迟变大本身是正常的。至于为什么更明显，这个测试过于笼统，具体原因我也无法确定。可能你额外套上udp2raw后CPU占用变高了；也可能是你用了udp2raw后视频的下载速度变快了，挤占了打开网页的带宽；也许像`好像在更新0911版本后，打开网页的速度慢了`一样，是网络环境本身波动造成的。

>实际上建立的不是udp连接，是raw socket的连接，因为使用了信道复用(multiplex)的方法，下层连接只有一条，而且目前只能是一条。
>刚看到这个，和这个是否有些关系呢？

应该不是，如果你的kcptun没特意改过相关参数的话，底层的连接也是只有一条。
