### ISSUE TITLE
Windows下vmware虚拟机里面运行udp2raw，无法加速kcptun

### ISSUE THREAD

**Issue by yyysuo** [wangyu-/udp2raw-tunnel#42]
操作系统：windows 10 pro x64
udp2raw版本：0826 X86
kcptun版本：20170525
vmware版本：VMware® Workstation 12 Pro
vmware网络：NAT模式  网关192.168.88.1
openwrt ip：192.168.88.130

openwrt跑在虚拟机，kcptun运行在主机，指向openwrt的udp2raw地址192.168.88.130:3334
报sent tcp syn错误，并且不停的在握手，请问大神有可能是什么原因？

我在路由器上跑udp2raw,kcptun指向路由上的udp2raw是没有问题的。

![2017-09-04_131833](https://user-images.githubusercontent.com/10081071/30012913-d474434c-9175-11e7-920a-1fa3f9c496f3.png)

**Comment by yyysuo** [comment]
虚拟机里面执行的命令是：
cd /root/
./udp2raw_x86 -c -l0.0.0.0:4444  -rvpsip:vpsport -a -k "passwd" --raw-mode faketcp &

**Comment by wangyu-** [comment]
>vmware网络：NAT模式 网关192.168.88.1

NAT模式不行，要用桥接。认真看readme.md和readme.txt呀。

**Comment by yyysuo** [comment]
我先按桥接来的，失败了又转的NAT，桥接会报下面的错误。

![2017-09-04_134636](https://user-images.githubusercontent.com/10081071/30013225-e95d99aa-9177-11e7-90ab-f100bf3a2f3d.png)

**Comment by wangyu-** [comment]
日志里没有错误。但是貌似你的KCPTUN一直在重试没有连接成功。你server上的KCPTUN服务端是不是被kill掉了。

**Comment by yyysuo** [comment]
vps端应该没有问题，因为我路由器上跑着udp2raw，虚拟机里面也跑着udp2raw,两个kcptun都跑在笔记本电脑上，用路由器里面的udp2raw加速是没有问题的，我这个回帖就是通过加速回帖的，效果非常赞，延迟很低，很稳定。

**Comment by yyysuo** [comment]
对了，需要装vmware tools吗？我看vmware总是问要不要装。

**Comment by wangyu-** [comment]
你试一下在电脑上ping虚拟机的ip，和用ssh连接虚拟机里的ssh服务器，看是否正常。

从你的日志看，udp2raw已经连通了，而且一直没有掉线。但是kcptun没连上。你再想想有没有什么其他的差异。

不需要vmware tools。

**Comment by wangyu-** [comment]
如果还是没线索的话。建议把kcptun换成udp模式的netcat，测试一下是否可以正常发送/接受数据。

**Comment by yyysuo** [comment]
主机ping不通虚拟机的IP，我怀疑是kcptun和虚拟机里面的udp2raw连接不上。

**Comment by wangyu-** [comment]
>主机ping不通虚拟机的IP

这个不正常。可能是虚拟机的BUG(有时候vmware就是怎么也连接不通，必须去virtual network edit那里重置一下才正常)。

也可能是防火墙策略。

正常情况下是可以ping通的。先想办法ping通吧。

从你的日志看，你的虚拟机可以收到windows发送的数据，而windows收不到虚拟机发送的数据。

另外问一下,ssh连虚拟机的ip可以连进去吗？

**Comment by yyysuo** [comment]
进不去

**Comment by wangyu-** [comment]
不正常。虚拟机本身的问题或者防火墙问题。如果懒得找原因，装个virtualbox试下吧。我觉得这个的桥接比较稳定。

**Comment by yyysuo** [comment]
装了vb没有问题了，不过为什么加了udp2raw之后youtube的速度在2000kpbs左右，不加Udp2raw反而有8000kpbs，哪里设置的不正确吗？

**Comment by wangyu-** [comment]
是不是拿路由器测的，路由器CPU不好，用AES加密CPU会被打满，只有一点速度。

试一下用`--sock-buf 10240`把buf调满，排除buf问题。用`--cipher-mode xor`和`--auth-mode simple`把加密调到最低，排除性能问题。

如果还是不行

用speedtest.net测试看看，如果还是加了udp2raw更慢。那可能你的线路对udp和tcp有不同的路由策略，tcp的线路没有udp的好。就直接用kcptun吧。

（我这边icmp和tcp有不同的路由策略，icmp连上去延迟比tcp小很多，但是icmp能达到的吞吐量比tcp低）

**Comment by yyysuo** [comment]
路由器Newifi mini CPU很快100%了，Newifi D1基本上在50%以下。
目前在电信网络下发现kcptun走udp2raw通道速度反而会降低，感觉上是降低了延迟和增加了稳定性。
明天测试一下联通的网络，我办公室的网络超烂，貌似也对UDP做了QOS。

**Comment by yyysuo** [comment]
联通网络测试，这个网络应该是对UDP直接做了丢包劣化的,udp2raw对延迟的改善都是明显可查的。
VPS1：
SS：300kpbs
SS+KCPTUN 200kpbs
SS+KCPTUN+UDP2RAW 8000kpbs

VPS2：
SS：6000kpbs
SS+KCPTUN 150kpbs
SS+KCPTUN+UDP2RAW 5500kpbs

**Comment by wangyu-** [comment]
不错。多谢反馈测试结果。

**Comment by yyysuo** [comment]
大神如果有时间方便的话，还是出个win下的客户端吧，以我为例，经常背着电脑到处跑,openwrt分配到的IP总是变，那么本地kcptun的配置文件总是需要改，比较麻烦，失去了一开始设想的不断线的初衷了。

**Comment by yyysuo** [comment]
虚拟机里面的openwrt在主机切换网络后貌似不能自动获取ip，所以主要换网络之后不仅要改kcptun配置，还要重启openwrt才行，还是等好心人编译个win版的吧

**Comment by wangyu-** [comment]
>虚拟机里面的openwrt在主机切换网络后貌似不能自动获取ip，所以主要换网络之后不仅要改kcptun配置，还要重启openwrt才行

切换网络后运行一下`udhcpc -i br-lan`就可以获取新ip了。如果不想打命令，就写个脚本加入rc.local里，每10秒运行一次，就能自动获取ip了。

不能自动获取貌似是这个版本的openwrt的bug，以后我把openwrt换成lede试试。

**Comment by wangyu-** [comment]
>换网络默认情况不能自动获取貌似是这个版本的openwrt的bug，以后我把openwrt换成lede试试。

已经换成lede了。如果是vmware，更换网络后全自动获取新ip。如果是virtualbox，你把virtualbox的网卡断一下重新连上就可以获取新ip了。

**Comment by yyysuo** [comment]
再反馈一 个现象吧，老毛子固件某个版本结合运营商的QOS策略可能会导致udp2raw失效，我更新路由器固件后重启解决了问题。

**Comment by yyysuo** [comment]
vmware导入虚拟机之后不分配IPV4的地址，查了一下，网上说是pdnsd占用了53端口

**Comment by wangyu-** [comment]
>再反馈一 个现象吧，老毛子固件某个版本结合运营商的QOS策略可能会导致udp2raw失效，我更新路由器固件后重启解决了问题。

这个看起来问题在固件里，你看看是否能联系到固件作者，把问题反映给他。

>vmware导入虚拟机之后不分配IPV4的地址，查了一下，网上说是pdnsd占用了53端口

获取地址靠DHCP协议，貌似跟53端口没有关系。你的其他虚拟机能获得地址吗，之前的镜像可以获得地址，只有最新下载的这个不可以是吗？

**Comment by wangyu-** [comment]
> vmware导入虚拟机之后不分配IPV4的地址，查了一下，网上说是pdnsd占用了53端口

你之前不是用vmware可以获取地址，但是ping不通也无法ssh进去吗。后来安装了virtualbox解决了。看起来你的vmware本身有问题。

现在为什么换回vmware了？

**Comment by yyysuo** [comment]
我就是试试vmware行不行 vb没问题 很棒   记录路由器固件问题是给后来者排除问题提供一种可能

**Comment by wangyu-** [comment]
>我就是试试vmware行不行
把vmware重装一下吧。你现在的vmware桥接网卡模式本身有问题，换什么版本应该都不会好使。

![capture](https://user-images.githubusercontent.com/4922024/30308144-1d6fea48-9738-11e7-9e21-e7916bb474ba.PNG)

试一下手动指定桥接的网卡可不可以，如果还不可以，可以尝试点左下角的restore default，如果还不好使，基本上只能靠重装解决了。

>记录路由器固件问题是给后来者排除问题提供一种可能

好，多谢反馈。

**Comment by wangyu-** [comment]
>我就是试试vmware行不行

把vmware重装一下吧。你现在的vmware桥接网卡模式本身有问题，换什么版本应该都不会好使。

![capture](https://user-images.githubusercontent.com/4922024/30308144-1d6fea48-9738-11e7-9e21-e7916bb474ba.PNG)

试一下手动指定桥接的网卡可不可以，如果还不可以，可以尝试点左下角的restore default，如果还不好使，基本上只能靠重装解决了。

>记录路由器固件问题是给后来者排除问题提供一种可能

好，多谢反馈。
