### ISSUE TITLE
Is it icmp mode work? 

### ISSUE THREAD

**Issue by Cwek** [wangyu-/udp2raw-tunnel#429]
As title.
And some question for config.

- Is it need to set `/proc/sys/net/ipv4/icmp_echo_ignore_all` to 1?
- Does the size of the `sock-buf` need to be smaller than the MTU value of the link, for example, less than 1500?

**Comment by HiGarfield** [comment]
> As title. 

I am using icmp. It works normally.

> And some question for config.
> 
> * Is it need to set `/proc/sys/net/ipv4/icmp_echo_ignore_all` to 1?

Not needed.

> * Does the size of the `sock-buf` need to be smaller than the MTU value of the link, for example, less than 1500?

No.
