### ISSUE TITLE
Few questions to ask!

### ISSUE THREAD

**Issue by hikris007** [wangyu-/udp2raw-tunnel#439]
I have a few questions to ask
1. Can udp2raw be used for scientific internet access?
2. is the encryption secure enough compared to v2ray?
3. is it better than v2ray to disguise traffic from GFW?

I hope you can take time out of your busy schedule to answer these questions, thanks!

**Comment by poorp** [comment]
I am not an expert but from my own experience I can say:
1. yes
2. yes, if the encryption option you specify in udp2raw's config is a good one
3. It can be at times, but v2ray certainly has a lot of options that can be used to disguise (using x-ui panel you can do many transport modes and tls options easily)

**Comment by wangyu-** [comment]
>2. is the encryption secure enough compared to v2ray?

I think none of udp2raw or v2ray or $$ is backended by a security team, if you need serious encryption you should use wireguard or openvpn or ssh proxy or something else.

see https://github.com/wangyu-/udp2raw/wiki/Notes-on-encryption

**Comment by hikris007** [comment]
@wangyu- @poorp Thank you for your answer,have a great day!
