### ISSUE TITLE
需要守护吗？如何卸载？

### ISSUE THREAD

**Issue by darvenzil** [wangyu-/udp2raw-tunnel#44]
楼主你好！
1、这个TUNNEL在Linux里需要守护吗？
2、似乎教程里没有说到在Linux如何卸载？

**Comment by wangyu-** [comment]
>1、这个TUNNEL在Linux里需要守护吗？
这个是什么意思？

你只要想办法让udp2raw client和server一直运行不被杀掉就可以了。任何方法都可以。

>2、似乎教程里没有说到在Linux如何卸载？

这个本身就不要安装，也就不需要卸载。你要运行udp2raw只要下载个文件，如果你不想用了，删了就是。

**Comment by darvenzil** [comment]
明白，close。
