### ISSUE TITLE
想问下这个支持BBR吗

### ISSUE THREAD

**Issue by yevision94** [wangyu-/udp2raw-tunnel#45]
如题，最近在用BBR，效果还不错，比KC简单，不知道能不能配合这个一起搞事情？

**Comment by wangyu-** [comment]
>这个支持BBR吗

udp2raw只适用于udp,BBR只适用于tcp。互相独立，互不干扰。两者不相干，没有支不支持的说法。

>不知道能不能配合这个一起搞事情？

如果你说的是udp2raw和BBR效果叠加。那么不能。

如果你说用BBR加速tcp，udp2raw "加速" udp，可行。

**Comment by diigu** [comment]
BBR只支持TCP，udp2raw并无加速效果，只是为了欺骗QoS。kcptun和finalspeed是udp加速，和BBR和udp2raw毛关系都没有。
