### ISSUE TITLE
希望加上输出日志到syslog功能

### ISSUE THREAD

**Issue by HSXX** [wangyu-/udp2raw-tunnel#47]
希望加上输出日志到syslog功能

**Comment by wangyu-** [comment]
参考这里的方法，方法本身足够简单，没有必要在udp2raw里面实现一遍。

http://urbanautomaton.com/blog/2014/09/09/redirecting-bash-script-output-to-syslog/

https://unix.stackexchange.com/questions/124455/linux-how-to-redirect-stdout-stderr-to-logger
