### ISSUE TITLE
启用了之后确实可以解除udp封锁，但是Xbox主机派对无法启动？

### ISSUE THREAD

**Issue by lingaoyi** [wangyu-/udp2raw-tunnel#499]
作者能帮忙解决一下吗？

**Comment by wangyu-** [comment]
english only

**Comment by wangyu-** [comment]
You are asking for help, but you don't even want to clearly descript your problem: no configuration or network topology provided. I cannot understand what you are doing at all.

**Comment by lingaoyi** [comment]
It is indeed possible to unblock UDP after enabling it, but the Xbox console party cannot be started?
