### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by suikatomoki** [wangyu-/udp2raw-tunnel#5]
怎么报 undefined reference to `__gxx_personality_v0' 错误
32位Ubuntu

**Comment by wangyu-** [comment]
我上次遇到这个错误是因为有的平台的编译工具不带静态库。

你把-static去掉试试

**Comment by suikatomoki** [comment]
我删了makefile重新cmake就好了
makefile还是别留了吧

**Comment by wangyu-** [comment]
那个makefile是我手写的，交叉编译时要用。

暂时不删。

**Comment by suikatomoki** [comment]
原来如此 谢谢

**Comment by suikatomoki** [comment]
再问一下 是 -k password 还是 -k “password”

**Comment by wangyu-** [comment]
没有区别.这个引号在传给命令行时自己就去掉了。只有在你用特殊符号的时候加不加引号才有区别。

中间的空格也是加不加都可以的。

**Comment by suikatomoki** [comment]
lede
make CC=mips-openwrt-linux-g++
提示对‘__cxa_rethrow’未定义的引用
如何解决

**Comment by wangyu-** [comment]
不要用 make cc=，交叉编译的参数不一样。
编辑makefile 然后make cross
参考：
https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/build_guide.zh-cn.md

**Comment by suikatomoki** [comment]
这样编译是成功了 但lede运行提示 _ZSt17__throw_bad_allocv symbol not found

**Comment by wangyu-** [comment]
感觉是你的交叉编译工具和lede所带的运行库版本不匹配。尝试换版本。
或者如果你的交叉编译工具带静态库，使用静态编译 （加上-static参数）。

**Comment by wangyu-** [comment]
你git pull一下，更新最新的makefile，试下make cross2 。cross2是静态编译，但是没有o3优化。

**Comment by suikatomoki** [comment]
应该不是不匹配原因
我都是从
https://downloads.lede-project.org/releases/17.01.2/targets/ar71xx/nand/ 
下载的

**Comment by suikatomoki** [comment]
你还没更新好呢 我怎么pull

**Comment by wangyu-** [comment]
我是先push了才回的帖呀。

**Comment by suikatomoki** [comment]
ok了 可以运行了

**Comment by suikatomoki** [comment]
![qq 20170812114147](https://user-images.githubusercontent.com/10336224/29237555-410fd546-7f53-11e7-98b3-79932bad542b.png)

崩了 
./udp2raw_tunnel -s -l0.0.0.0:156 -r 127.0.0.1:15985 -a -k none  --raw-mode faketcp --auth-mode none --cipher-mode none
 
./udp2raw_tunnel -c -l0.0.0.0:15985 -rserver_ip:156 -a -k none --raw-mode faketcp --auth-mode none --cipher-mode none

**Comment by wangyu-** [comment]
server崩了？ server是刚才编译的lede?

**Comment by suikatomoki** [comment]
server崩了 server是32位ubuntu

**Comment by wangyu-** [comment]
你用我编译的x86版本试一下。如果还是崩,就gdb ./udp2raw_tunnel   core  ，然后打bt，查看一下core里的栈信息。

**Comment by suikatomoki** [comment]
lede是客户端 客户端没事 15985 是ss-redir与ss-server的端口

你说的x86是啥意思 i686 的意思吗 还是windows x86

**Comment by suikatomoki** [comment]
我懂了 还是崩了  我试试gdb

**Comment by wangyu-** [comment]
就是在release包里的那个udp2raw_x86，32位linux系统用udp2raw_x86。如果是64位系统，用udp2raw_amd64。

**Comment by suikatomoki** [comment]
刚才搞错了 要运行udp2raw_x86 这次正常了 谢谢

**Comment by wangyu-** [comment]
没事。

路由器不要用aes加密，很慢。

**Comment by suikatomoki** [comment]
我用的none 不加密了

**Comment by wangyu-** [comment]
推荐cipher设成xor,auth设成simp,这两个几乎没什么性能损失。如果你坚持设成none，那最好加上--disable-anti-replay。
