### ISSUE TITLE
建议releases加上动态编译版本

### ISSUE THREAD

**Issue by HSXX** [wangyu-/udp2raw-tunnel#50]
动态编译比静态编译小了2M以上，建议可以在文件名称加上编译所用的库名

**Comment by HSXX** [comment]
单独安装C++库也只有300多K，虚拟机镜像换成动态编译也可以大幅减小体积

**Comment by wangyu-** [comment]
不静态编译的话，binary不止依赖于c库的类型(glibc,musl,ulibc)，还依赖于c库的版本。

编译出来的binary数量要翻好几倍，也不能照顾到所有平台，用户也难以知道要选哪个binary。

用make cross交叉编译出来的binary是动态的，可以尝试自己编译。

**Comment by HSXX** [comment]
自己动态编译才200多K，静态的有2.6M

**Comment by PHCSJC** [comment]
对于我这种小白来说还是静态的好，路由器的剩余空间也够了。

**Comment by jiangtiandao** [comment]
makefile 加个动态的 target 如何？

**Comment by wangyu-** [comment]
@jiangtiandao 
已加，见：
 https://github.com/wangyu-/udp2raw-tunnel/commit/e1a97c03b54cf434c9705b2f9d70ad9ca04b4fb3
