### ISSUE TITLE
The issue of multiple ports with kcptun and udp2raw。

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/udp2raw-tunnel#503]
I am using kcptun in conjunction with udp2raw, and I know that kcptun supports multiple ports. Does udp2raw also support multiple ports?

**Comment by HiGarfield** [comment]
You can run multiple instances of udp2raw, with each instance using a separate port.

**Comment by wangyu-** [comment]
udp2raw doesn't have similiar multiple port as kcptun.

running multiple insntances is the only way.

**Comment by maojianyou** [comment]
> 您可以运行 udp2raw 的多个实例，每个实例使用单独的端口。

**Comment by maojianyou** [comment]
> You can run multiple instances of udp2raw, with each instance using a separate port.

If multiple instances are used, it is equivalent to running multiple udp2raw processes, resulting in a high number of udp2raw instances. Since kcptun only utilizes a single port for service, it would be beneficial if there is an automated mechanism to identify the specific port among, for example, 100 ports, eliminating the need to spawn numerous udp2raw processes unnecessarily.

**Comment by maojianyou** [comment]
> udp2raw doesn't have similiar multiple port as kcptun.
> 
> running multiple insntances is the only way.

If multiple instances are used, it is equivalent to running multiple udp2raw processes, resulting in a high number of udp2raw instances. Since kcptun only utilizes a single port for service, it would be beneficial if there is an automated mechanism to identify the specific port among, for example, 100 ports, eliminating the need to spawn numerous udp2raw processes unnecessarily.
