### ISSUE TITLE
FakeTCP 可以加入混肴，伪装成 http 或者 https 吗？

### ISSUE THREAD

**Issue by qiang-yu** [wangyu-/udp2raw-tunnel#51]
FakeTCP 如果可以进一步伪装成 http 或者 https 影响效果会更好，一些地方 QoS对 大数据量的 tcp 也会做限制的，只有 http, https 是完全没限制

**Comment by wangyu-** [comment]
这个功能可以有，但是优先级不会很高。

首先。我在几个网络环境上试用过**R的混淆，跟原版比没发现有明显效果。

其次。混淆成http/https也不能完全保证就不被限速了,只是能降低被限速的几率。而且这种混淆实现起来有多种方法。可以是模拟长连接，也可以模拟短连接；包装数据也有多种办法。如果要做得比较完善，需要像**R那样提供一个列表，供选择尝试哪个效果好。并不是简单做一下，就能达到预期的效果。

如果有人给udp2raw添加了类似功能，并且证明了有效果，我可以merge代码。

实现一个最简单版本的http混淆，可以wrap一下下面这两个函数，在发包前加上http header，收包后去掉header:
int send_raw0(raw_info_t &raw_info,const char * payload,int payloadlen)
int recv_raw0(raw_info_t &raw_info,char * &payload,int &payloadlen)

**Comment by qiang-yu** [comment]
**R 的混淆是有效果的，这个取决于网络，如果你的网络本身对tcp大流量不限制确实看不出区别
但是对于一些网络，比如学校，或者某种大局域网，混淆成 http/https 效果还是相当明显的

现在尝试把  ShadowVPN/muon + UDPspeeder + udp2raw-tunnel  组合起来使用，比**R效果更好

ShadowVPN/muon 这两个比 OpenVPN 轻很多，部署到 OpenWrt 上很方便

**Comment by PHCSJC** [comment]
@wangyu- 
全国各地的Qos策略都不一样，伪装数据类似确实有效果，所以我之前一直用ssr，伪装成https还可以增强安全性，希望能增加https伪装。

**Comment by githubtc** [comment]
@wangyu-
能不能简单实现下http混淆。

**Comment by wangyu-** [comment]
已加入Contribution Guide
