### ISSUE TITLE
FakeTCP 模式下，端口可以复用吗？

### ISSUE THREAD

**Issue by qiang-yu** [wangyu-/udp2raw-tunnel#52]
比如，我用 443 端口，这一个端口可以同时用 udp2raw-tunnel 和 nginx(ssl) 吗？

因为我看 udp2raw-tunnel 加入 iptables 的规则其实是 drop 掉包，如果不 drop，这些包可以正常到 nginx 去吗？  就是实现  udp2raw-tunnel 和 https 服务器同时工作，都用 443 端口

不知道这样行不行？

**Comment by wangyu-** [comment]
这样不行。

>就是实现 udp2raw-tunnel 和 https 服务器同时工作，都用 443 端口
这样的话udp2raw-tunnel 和https会收到互相的数据，造成问题。

目前udp2raw-tunnel会特意用tcp socket bind到监听的端口，以防止有人用类似的用法。如果你尝试同时让 udp2raw-tunnel和https服务器监听在443，会有一个启动不起来。
