### ISSUE TITLE
实验配合**R使用，**R无法连接，求教

### ISSUE THREAD

**Issue by Steve-luo** [wangyu-/udp2raw-tunnel#53]
现在情况是，服务器 server_ready，客户端 client_ready，确认 udp2raw 可用
服务器上安装了监听 80 端口的 **R，udp2raw 设置用 443 端口交流，转发流量至 80 端口
`./udp2raw_amd64 -s -l0.0.0.0:443 -r127.0.0.1:80 -k"passwd" --raw-mode faketcp -a`

客户端用的是 VirtualBox，地址 192.168.31.238，监听端口 8678
`./udp2raw_x86_asm_aes -c -r服务器IP:443 -l0.0.0.0:8678 --raw-mode faketcp -a -k”passwd”`

**R 客户端直连 服务器IP:80 可以正常使用，但是连接 192.168.31.238:8678 无法使用
求教哪里配置出错了，谢谢

**Comment by wangyu-** [comment]
>**R 客户端直连 服务器IP:80 可以正常使用，但是连接 192.168.31.238:8678 无法使用
求教哪里配置出错了

**R同时监听在TCP和UDP端口。你上面的命令只是把server上的**R的udp端口映射到本地了。所以无法使用。

**Comment by Steve-luo** [comment]
@wangyu- 就是要在服务端用iptables再加一条443到80的tcp转发吗？我对iptables的命令还是一团浆糊，还请教一下要怎么用。

**Comment by PHCSJC** [comment]
我也用的ssr，没有问题，iptables不用手动添加。
看看udp2raw客户端启动时有ready提示吗？
再就是虚拟用的桥接吗？必须桥接，不能nat。

**Comment by Steve-luo** [comment]
@PHCSJC 服务端和客户端两边都ready，虚拟机是桥接网络无误，路由器可以看到分配给虚拟机的新ip。你的客户端是怎么配置的？

**Comment by wangyu-** [comment]
@Steve-luo 

@PHCSJC 在xxr client和server之间用了kcptun加速，跟你情况不一样。

@PHCSJC 需要用udp2raw是因为kcptun把tcp流量变成了udp。

你只用xxr,浏览网页和看视频一般都只走tcp流量，udp2raw是针对udp的。你能不能说明下，你想用xxr+udp2raw是为了达到什么目的？

**Comment by Steve-luo** [comment]
@wangyu- 我们学校的网block所有的udp连接，所以想通过这个方法把udp伪装为tcp。我本身在国外，所以xxr只是用来越过学校的防火墙。可能和udp2raw的主要目的不太一致。

**Comment by wangyu-** [comment]
@Steve-luo 

所以你想要让所有udp连接走xxr的sock5代理，然后再由udp2raw变成tcp?

**Comment by Steve-luo** [comment]
@wangyu- 顺序应该是 udp走xxr客户端到udp2raw，再由udp2raw发送至服务器，服务器再映射到xxr的监听端口，躲过学校的防火墙。这么一想我好想知道问题在哪里了，udp2raw是只能通过udp流量的吗？所以要实现这个路径需要配合kcptun使用才对，是这样吗？

**Comment by wangyu-** [comment]
>顺序应该是 udp走xxr客户端到udp2raw，再由udp2raw发送至服务器，服务器再映射到xxr的监听端口，躲过学校的防火墙。

这么用完全没问题，跟udp2raw的目的也一致。

>udp2raw是只能通过udp流量的吗？

是的，udp2raw只能转发udp流量。

>所以要实现这个路径需要配合kcptun使用才对，是这样吗？

你现在问题是，xxr监听了tcp和udp的80，你只用udp2raw把udp的80映射到了本地，只映射udp SSR是不能正常工作的(貌似)。不管你用什么方法，把tcp的80也映射到本地就可以了。可以用iptables或ssh tunnel或ncat实现，kcptun也可以。具体命令你自己研究一下。

**Comment by wangyu-** [comment]
>**R 客户端直连 服务器IP:80 可以正常使用，但是连接 192.168.31.238:8678 无法使用
求教哪里配置出错了，谢谢

另外，我想问一下，你是怎么确认`直连 服务器IP:80 可以正常使用`的。

**Comment by Steve-luo** [comment]
@wangyu- 可能是我没有表述清楚，我的意思就是说xxr本身是正常的，通过udp2raw不能用。我再自己折腾折腾，感谢指点。

**Comment by wangyu-** [comment]
@Steve-luo 
> 可能是我没有表述清楚，我的意思就是说xxr本身是正常的，通过udp2raw不能用

不是表达问题。我问的是你靠什么方法确认的`xxr本身是正常的，通过udp2raw不能用`。比如，你用浏览器+ssr插件，或者是什么其他的办法。

**Comment by Steve-luo** [comment]
@wangyu- 就是chrome+SwitchySharp。

**Comment by wangyu-** [comment]
@Steve-luo 

>就是chrome+SwitchySharp

这个走的是tcp，不产生udp流量（除非网站和浏览器都开启了quic）。没法测试` udp走xxr客户端到udp2raw，再由udp2raw发送至服务器，服务器再映射到xxr的监听端口，躲过学校的防火墙`这个过程。

至于为什么`通过udp2raw不能用`，就是像前面说的，没有把tcp端口也映射过来。如果你的用udp only的程序，通过ssr的socks5连接，很可能已经可以正常工作了。

**Comment by Steve-luo** [comment]
@wangyu- 彻底搞定了。在LEDE上转发确实成功了，但是DNS有问题，无法解析地址。新装了一个Ubuntu Server之后加上iptables转发完美运行。感谢~
