### ISSUE TITLE
Why --mtu-warn is 1375 default?

### ISSUE THREAD

**Issue by jearton** [wangyu-/udp2raw-tunnel#530]
I found that even sending packets larger than 1375 was OK, just with warning logs. So should I raise the mtu warning threshold?

**Comment by wangyu-** [comment]
udp2raw acutally doesn't know what is the exact mtu your network supports.
1375 is only an experiential value.
you can supress the warning by `--mtu-warn 9999`

**Comment by wangyu-** [comment]
there is an article in the wiki on MTU:
https://github.com/wangyu-/udp2raw/wiki/about-mtu

**Comment by jearton** [comment]
OK, I got it.
