### ISSUE TITLE
udp2raw generates too much traffic, so what load will it have?（udp2raw占用过多带宽，即使没有任何负载？）

### ISSUE THREAD

**Issue by haohetao** [wangyu-/udp2raw-tunnel#535]
English Only.
no udp2raw, network traffic
incoming 5kb/s
outgoing 20kb/s

with udp2raw,network traffic
incoming 30kb/s
outgoing 60kb/s

500MB of network traffic wasted per day。

**Comment by wangyu-** [comment]
there are overheads introduced by:
1. extra header
2. heatbeat

You can turn down the length of heart-beat  by --hb-len (search --hb-len in issues).  If you want to reduce how often hearbeat is send, currently the only way is changing source code


>no udp2raw, network traffic
incoming 5kb/s
outgoing 20kb/s
>with udp2raw,network traffic
incoming 30kb/s
outgoing 60kb/s

By the way your data doesn't look very accurate.  5kb/s->30kb/s doesn't seem to make sense.

If the original traffic is so light, it should only increase a few kb/s. Unless your traffic are all very small packets.

**Comment by haohetao** [comment]
I'm changed heartbeat_interval to 25000 ms,hb_len to 0,However, the traffic still occupies 1-1.5KB/s.
![图片](https://github.com/user-attachments/assets/87451e02-a2aa-4166-a6df-0d38fc4eee63)

**Comment by haohetao** [comment]
I found another udp2raw client in my network( and no change source code), I have closed all other clients, only one is reserved, it is now normal.

![图片](https://github.com/user-attachments/assets/dc661330-5243-4829-a485-b7a7ff96bf97)
