### ISSUE TITLE
udp2raw在windows10 linux子系统不能启动

### ISSUE THREAD

**Issue by githubtc** [wangyu-/udp2raw-tunnel#57]
显示 错误：［FATAL] Failed to create raw_send_fd。

同时希望加入http混淆。

**Comment by wangyu-** [comment]
>显示 错误：［FATAL] Failed to create raw_send_fd。

一般出现这个错误是因为没有用root账号运行。

另外windows10 linux子系统做得不是很完善，不确定udp2raw能否正常工作，不如直接用虚拟机。

**Comment by ntflc** [comment]
参考https://github.com/wangyu-/udp2raw-tunnel/wiki/%E5%9C%A8win10%E7%9A%84linux%E5%AD%90%E7%B3%BB%E7%BB%9F%E4%B8%8A%E5%8E%9F%E7%94%9F%E8%BF%90%E8%A1%8Cudp2raw，在win10的linux子系统里启动udp2raw，也是提示[FATAL]Failed to create raw_send_fd
系统：Windows 10 1703、1709

**Comment by wangyu-** [comment]
@ntflc  用root账号试一下？

我记得之前有人说可以运行，但是加不了iptables。

**Comment by ntflc** [comment]
@wangyu- 用root账号试了也是这样。
如果加了-a，会提示iptables无法添加；不加-g就直接提示[FATAL]Failed to create raw_send_fd

**Comment by wangyu-** [comment]
@ntflc 多谢反馈。

我先把这篇文章去掉了。我机器上现在没有wsl，过几天我装个WSL试一下。

**Comment by wangyu-** [comment]
现在有原生的windows版了，不需要wsl就可以运行。
