### ISSUE TITLE
所以这个项目是udp to raw？和kcptun-raw区别是？

### ISSUE THREAD

**Issue by ohsorry** [wangyu-/udp2raw-tunnel#62]
请教个问题：
[kcptun-raw](https://github.com/Chion82/kcptun-raw)是直接使用raw socket 然后ARQ使用kcp。
这个项目是把udp通过raw socket加工进行伪装？可靠传输怎么保证的？

**Comment by wangyu-** [comment]
kcptun-raw把raw socket这个功能做到kcptun里了。

udp2raw把这个功能做成单独的了。缺点是需要额外部署个udp2raw服务；优点是能配合任意的udp程序使用，达到防udp屏蔽的目的。

**Comment by ohsorry** [comment]
明白了！

**Comment by wangyu-** [comment]
>可靠传输怎么保证的？

在udp2raw这个层面不需要可靠传输，可靠传输由承载的上层应用保证。如果你用udp2raw+kcptun，那么可靠传输就是由kcptun保证的。

**Comment by ohsorry** [comment]
你是对的。
