### ISSUE TITLE
请问--raw-mode udp的话只是给udp包加了层隧道么?

### ISSUE THREAD

**Issue by diguoemo** [wangyu-/udp2raw-tunnel#63]
如题。里面封的l2tp vpn。用faketcp的话，虽然能用 服务端一直报 rst==1的错误。

**Comment by wangyu-** [comment]
>虽然能用 服务端一直报 rst==1的错误。

应该是没添加对iptables规则，或者是client连上之后被你kill掉了。

`--raw-mode udp`的话跟普通的udp隧道差不多。不过底层也是用raw socket实现的。

**Comment by PHCSJC** [comment]
不开新帖了，就在这里问下吧，fifo这个参数没看懂什么意思，表哥能再解释一下吗？

**Comment by wangyu-** [comment]
看一下readme里的说明

>指定一个fifo(named pipe)来向运行中的程序发送命令，例如--fifo fifo.file：
>在client端,可以用echo reconnect >fifo.file来强制client换端口重连（上层不断线）.对Server，目前没有效果。

目前唯一的功能是强制client换端口重连。

**Comment by PHCSJC** [comment]
好吧，貌似明白了一点，目前还是比较稳的。

**Comment by wangyu-** [comment]
@PHCSJC 

我这边的移动线路，有时候会丢包突然变高，但是不断线，需要手动重连才能恢复，大概每隔几天出现一次。这个功能就是为了可以更方便地重连。

请问你在使用时没有类似问题吗？

**Comment by wangyu-** [comment]
>不开新帖了，就在这里问下吧

如果是跟issue主题不想关的内容，建议还是开issue比较好。回复在这里别人遇到类似问题很难找到。

**Comment by PHCSJC** [comment]
好的，明白了

**Comment by wangyu-** [comment]
>我这边的移动线路，有时候会丢包突然变高，但是不断线，需要手动重连才能恢复，大概每隔几天出现一次。这个功能就是为了可以更方便地重连。
>请问你在使用时没有类似问题吗？

@PHCSJC

**Comment by PHCSJC** [comment]
我的现象是，上不了了，然后我重启下客户端就好了，好像跟你说的一样。
有时几天出现一次，有时一天出现好2，3次。

**Comment by wangyu-** [comment]
@PHCSJC 

不清楚是程序BUG还是运营商的限制。怀疑是运营商的限制。

调小MTU后，几率会降低。不重启客户端，强制client重连也可以恢复。

**Comment by PHCSJC** [comment]
@wangyu- 
--fifo这个参数是在服务器端指定吗？我试试效果。是直接加--fifo吗？感觉后面还要加个秒数？

**Comment by wangyu-** [comment]
>--fifo这个参数是在服务器端指定吗？我试试效果。是直接加--fifo吗？感觉后面还要加个数字？

在client端指定，后面要加个文件名，你看下readme。

**Comment by PHCSJC** [comment]
手动执行这个命令来切换端口？
echo reconnect >fifo.file

**Comment by wangyu-** [comment]
嗯

**Comment by wangyu-** [comment]
你试一下就可以，没有副作用，重连不会断线，只会短暂的丢几个包。

**Comment by wangyu-** [comment]
>有时几天出现一次，有时一天出现2，3次。

如果频率很高的话，可以试下调小MTU，到1000以下。

**Comment by PHCSJC** [comment]
你的这个命令我理解是简化版不断线的重启，要是能自动判断就更好了。
这个就暂时不用了，我也写了个简单的重启脚本。
我再试试降低mtu试试。

**Comment by wangyu-** [comment]
>你的这个命令我理解是简化版不断线的重启，要是能自动判断就更好了。

可以这么理解，叫不断线重连更准确些。

程序里面本来就有心跳检测，如果一段时间没收到包，就会`不断线重连`。但是一般这个问题出现时。只是丢包突然变得很高，不会彻底连不上。所以在程序不好判断是否需要自动重连，所以现在提供了一个手动不断线重连的功能。

**Comment by wangyu-** [comment]
@PHCSJC 

需要手动重启client的问题在最新版里应该是解决了。目前为止运行了一周，没有再出问题。
