### ISSUE TITLE
关于重复用 端口 和 检验是否成功有效问题。

### ISSUE THREAD

**Issue by wmjlxl** [wangyu-/udp2raw-tunnel#64]
先谢谢作者提供的udp2raw, 使我有得折腾。

---------quote----------
你在服务器，启动个udp2raw_server。-l0.0.0.0:8855 -r127.0.0.1:<kcptun_server端口>
在本机，启动个udp2raw_server -r<服务器ip>:8855 -l127.0.0.1:<新端口>
然-后改kcptun_client，让它连到127.0.0.1:<新端口>，大概就这个思路。

@wangyu 以上的解说，其中 “<新端口>” ， 想问问这个 可以继续用回 kcptun server 端口？

例如下面设置：
vps 服务器的 SS 端口为 888， kcptun 监听端口为 551

udp2raw 服务端：
./udp2raw -s -l0.0.0.0:8855 -r 127.0.0.1:551 -a -k "pas123" --raw-mode faketcp
udp2raw 客户端：
./udp2raw -c -l0.0.0.0:551 -r123.123.123.123:8855 -a -k "pas123" --raw-mode faketcp

kcptun 服务端：
./server_linux_amd64 -t "127.0.0.1:888" -l ":551" -mode fast1
kcptun 客户端：
./client_linux_amd64 -r "127.0.0.1:551" -l ":888" -mode fast1

这样设置应该没问题吧？ 我可以成功运行。
但是最后的问题就是如何检验 udp2raw 是否生效？

谢谢。

**Comment by wangyu-** [comment]
>以上的解说，其中 “<新端口>” ， 想问问这个 可以继续用回 kcptun server 端口？

可以。

>但是最后的问题就是如何检验 udp2raw 是否生效？

你可以把log等级调高，如果有数据流过，会产生大量log。或者更简单的方式，用top命令看udp2raw的cpu，如果有数据时cpu明显变高，那就说明数据流过了udp2raw。

**Comment by wmjlxl** [comment]
明白了，谢谢 wangyu
