### ISSUE TITLE
和ss一起用tcp流量出不去

### ISSUE THREAD

**Issue by DeclanHuaChen** [wangyu-/udp2raw-tunnel#68]
校园网挂上ss玩游戏时udp间歇性被屏蔽，就想用这个试试。
ss客户端用的sstap，鼓捣好了都连上了，测试发现udp都能连上，tcp出不去。
小白一个，问问这个有办法解决吗？

**Comment by wangyu-** [comment]
udp2raw只支持转发udp。如果你想让sstap测试通过，还需要用socat之类的工具把tcp也转发了。

**Comment by wangyu-** [comment]
可以用这个转发tcp：

https://github.com/wangyu-/tinyPortMapper
