### ISSUE TITLE
AUR package for ArchLinux users

### ISSUE THREAD

**Issue by PeterCxy** [wangyu-/udp2raw-tunnel#7]
I've created an AUR package so that ArchLinux users could install it directly with

```bash
yaourt -S udp2raw-tunnel # or
pacaur -S udp2raw-tunnel
```

The link to the AUR page is https://aur.archlinux.org/packages/udp2raw-tunnel/.

Could you please add this to the README for the convenience of ArchLinux users? Thanks.

**Comment by PeterCxy** [comment]
I am also planning to add it to the `archlinuxcn` repository if this project becomes more stable.

**Comment by wangyu-** [comment]
Sure.Thx for your contribution.I will add it to readme.

**Comment by wangyu-** [comment]
added

**Comment by jpmvferreira** [comment]
It seems that this package was dropped sometime ago.
Could you share the PKDBUILD to fetch the latest stable version for me to use as a reference?
Additionally, How much is it expected that the PKGBUILD to fetch the latest stable version change throughout time? If the answer is not much, maybe I could submit it in the AUR for others to use.
