### ISSUE TITLE
amd64 与 amd64_hw_aes 有什么区别吗？

### ISSUE THREAD

**Issue by bao3** [wangyu-/udp2raw-tunnel#70]
udp2raw_amd64_hw_aes 
udp2raw_amd64

**Comment by wangyu-** [comment]
udp2raw_amd64_hw_aes 是有硬件加速的版本，性能好一些。

udp2raw_amd64是c语言的版本，在没有硬件加速指令的机器上可以用。

**Comment by bao3** [comment]
arm 那个也是同样的道理，对吗？

**Comment by wangyu-** [comment]
>arm 那个也是同样的道理，对吗？

类似的
