### ISSUE TITLE
很奇怪的 bug ~

### ISSUE THREAD

**Issue by bao3** [wangyu-/udp2raw-tunnel#72]
我使用配置文件方式，收到如下**错误消息**：

>
>root@silicon-lotServer:~/Sync/udpspeed# udp2raw -conf-file ./udp2raw.conf
>[2017-10-29 13:00:43][INFO]argc=3 udp2raw -conf-file ./udp2raw.conf
>udp2raw: invalid option -- 'o'
>[2017-10-29 13:00:43][FATAL]unknown option ,code:<o>,<6f>
>

然后我检查了一下配置文件，似乎没什么问题，与是我将里面的参数都直接使用命令行：

`udp2raw -s -l 0.0.0.0:8080 -r 127.0.0.1:7979 -k aaa-bbb-ccc-team-eee --raw-mode faketcp --log-level 1 --cipher-mode aes128cbc --auth-mode  md5 `

这个居然没报错。。。我的配置文件如下：

```
# Basically this file is the equivalent to splitting the command line options into multiple lines
# Each line should contain an option

# This is client
-s
# Or use -s if you use it on server side
# Define local address
-l 0.0.0.0:8080
# Define remote address
-r 127.0.0.1:7979
# Password
-k right-rae-guano-team-sill
# Mode
--raw-mode faketcp
# Log Level
--log-level 1

# iptables auto,but if you meet issue,you could change to
# --lower-level auto
#--keep-rule
#--auto-rule

#avaliable values:aes128cbc(default),xor,none
#--cipher-mode aes128cbc

#avaliable values:md5(default),crc32,simple,none
#--auth-mode  md5

```

**Comment by bao3** [comment]
补充一下，我把配置文件精简成：

```
-s
-l 0.0.0.0:8080
-r 127.0.0.1:7979
--raw-mode faketcp
--log-level 1

```
也依然是同样的错误。

**Comment by wangyu-** [comment]
应该是`--conf-file`

**Comment by bpplpp** [comment]
那我这个怎么解决？一直没找到原因哎……

![image](https://user-images.githubusercontent.com/15948273/64139726-76e74500-ce34-11e9-83c9-273e961a102a.png)

```
-s
-l 0.0.0.0:271
-r 127.0.0.1:6040
-k xxxxxx
--raw-mode faketcp
-a
```

**Comment by bao3** [comment]
@bpplpp 兄台，注意看上面的解答。

**Comment by bpplpp** [comment]
@bao3 我的图片里有执行两次，你看看

**Comment by bao3** [comment]
每行开头用 “-” ,看看是不是有空行

**Comment by bpplpp** [comment]
@bao3 

![image](https://user-images.githubusercontent.com/15948273/64140414-ea8a5180-ce36-11e9-8c00-038d4fd32bd9.png)

咋整…怎么都不行

**Comment by luyu6056** [comment]
同样遇到问题，很无解
 ./udp2raw_amd64 --conf-file server.conf
配置文件内容

-s
# You can add comments like this
# Comments MUST occupy an entire line
# Or they will not work as expected
# Listen address
-l 0.0.0.0:4096
# Remote address
-r 127.0.0.1:7777
-a
-k passwd
--raw-mode faketcp
![image](https://user-images.githubusercontent.com/30688922/69110885-e88b7280-0ab6-11ea-9df9-d8e8b5ca1540.png)

![image](https://user-images.githubusercontent.com/30688922/69110869-e0333780-0ab6-11ea-89a7-0ead0a6946a1.png)

**Comment by wangyu-** [comment]
用你的配置测试了 正常运行 无法复现

**Comment by zyf0330** [comment]
可能是因为是 Windows 编辑的配置文件复制到了 Linux 上，这样即使是手动替换换行符也仍然保留了BOM，无法识别
