### ISSUE TITLE
用了这个加kcptun，ssr的混淆是不是就失效了？

### ISSUE THREAD

**Issue by vipcxj** [wangyu-/udp2raw-tunnel#73]
如题还有这个好像也有加密，kcptun也有加密，ssr也有加密，是不是ssr和kcptun的加密没必要设很强，甚至其中一个可以不加密？

**Comment by wangyu-** [comment]
>用了这个加kcptun，ssr的混淆是不是就失效了

是

>是不是ssr和kcptun的加密没必要设很强，甚至其中一个可以不加密？

差不多。在最外层加密就可以了；开多个加密也可以，以防其中某个有bug之类的。

**Comment by vipcxj** [comment]
所以这个项目有没有加下来增加混淆功能的计划？

**Comment by wangyu-** [comment]
>所以这个项目有没有加下来增加混淆功能的计划？

没有。这个项目的目的是防止运营商的UDP限速，跟**R的目的不同。
