### ISSUE TITLE
MTU 调节问题

### ISSUE THREAD

**Issue by bao3** [wangyu-/udp2raw-tunnel#74]
我在实际使用中，是 udp2raw -> speeder -> openvpn。不过总是有如下错误

```
[2017-10-30 01:42:59][WARN]huge packet,data len=1397 (>=1375).strongly suggested to set a smaller mtu at upper level,to get rid of this warn
```

我理解，我需要调整 MTU，但是我在 openvpn 服务器和客户端都调整了 MTU 为 1300 ，在 speeder 的 MTU 也设置了 1300 。但是实际上的包竟然有 1397 这么大。
以下是我的 udp2raw 设置：

```

```

以下是 speeder 参数：
`/usr/local/bin/speeder -l0.0.0.0:9998 -r 127.0.0.1:8686 -c fe20:10 --mtu 1375 -k "right-rae-guano-team-sill"`

以下是我的 openvpn 设定：

```

client
nobind
dev tun
#cipher none
cipher AES-128-CBC
key-direction 1
remote-cert-tls server
remote 127.0.0.1 9998 udp
tun-mtu 1300
#remote ovn.heibang.club 6553 udp
route 5.3.2.1 255.255.255.255 net_gateway 1
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
down-pre

```

**Comment by wangyu-** [comment]
貌似是OpenVPN的问题，我也能观察到类似现象。

虽然mtu设置成了1200但是还是会出现几个超过1200的包，但是出现了几次之后就不会再出了，不影响正常使用。

**Comment by sdysj** [comment]
udpspeeder + udp2raw + shadowvpn MTU 最大只能设为1200 不然就不能通信。

**Comment by liuyang007** [comment]
我设置了openvpn的选项
link-mtu可以解决，
具体调试可以使用ping -M do -s 1472 target来慢慢调小测试最大mtu

**Comment by jearton** [comment]
我使用了 wireguard -> udp2raw_client -> udp2raw_server -> wireguard, 调试下来发现wireguard 里的 MTU 设置为 1300，是刚好不触发 1375 这个告警的最大 MTU

**Comment by jearton** [comment]
或者不知道是否可以调高 --mtu-warn 的值？默认是1375，看起来只是一个告警阈值，超过1375并不能说明一定不通
