### ISSUE TITLE
路由器使用处理能力低

### ISSUE THREAD

**Issue by ppgl1** [wangyu-/udp2raw-tunnel#75]
比较偏好响应速度，所以kcptun窗口比较调的比较小200，mtu1200；
如果在虚拟机中套上您的udp2raw话，性能没什么损失，举例如下统计
2017/10/30 00:45:19 KCP SNMP:&{BytesSent:1984376956 BytesReceived:5661138 MaxConn:1 ActiveOpens:0 PassiveOpens:1 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:144377 OutPkts:1818878 InSegs:276188 OutSegs:1819431 InBytes:12298476 OutBytes:2107740167 RetransSegs:38183 FastRetransSegs:5703 EarlyRetransSegs:7231 LostSegs:25249 RepeatSegs:27 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}
大概94%效率，不知道算的对不对 用BytesSent/OutBytes的。
如果在路由(斐讯K2)上用您编译的（我不会= =），速度还是能到窗口200，mtu1200的峰值，大概900k，但效率会降到30%左右，服务端大量发包；路由cpu占用率用top看的话最高不超过30%，一般10%左右；

虚拟机里的命令
/root/udp2raw_x86_asm_aes -c -l 0.0.0.0:29888 -r ip:29888 --raw-mode  faketcp -k key --cipher-mode xor --auth-mode simple -a >/tmp/raw.log &
路由里的命令
wget -O /tmp/udp2raw ftp://192.168.100.2/udp2raw_mips24kc_le_asm_aes
chmod +x /tmp/udp2raw
/tmp/udp2raw -c -l 0.0.0.0:29888 -r ip:29888 --raw-mode faketcp -k key --cipher-mode xor --auth-mode simple -a >/dev/null &
vps端
/usr/kcptun/udp2raw_amd64_hw_aes -s -l 0.0.0.0:29888 -r 127.0.0.1:29777 --raw-mode faketcp -k key --cipher-mode xor --auth-mode simple -a >/dev/null &

kcptun的参数
2017/10/30 08:28:33 version: 20171021
2017/10/30 08:28:33 listening on: [::]:29888
2017/10/30 08:28:33 encryption: salsa20
2017/10/30 08:28:33 nodelay parameters: 0 30 2 1
2017/10/30 08:28:33 remote address: 192.168.100.6:29888
2017/10/30 08:28:33 sndwnd: 200 rcvwnd: 200
2017/10/30 08:28:33 compression: false
2017/10/30 08:28:33 mtu: 1200
2017/10/30 08:28:33 datashard: 0 parityshard: 0
2017/10/30 08:28:33 acknodelay: false
2017/10/30 08:28:33 dscp: 46
2017/10/30 08:28:33 sockbuf: 4194304
2017/10/30 08:28:33 keepalive: 10
2017/10/30 08:28:33 conn: 1
2017/10/30 08:28:33 autoexpire: 0
2017/10/30 08:28:33 scavengettl: -1
2017/10/30 08:28:33 snmplog: 
2017/10/30 08:28:33 snmpperiod: 60
2017/10/30 08:28:33 quiet: true

**Comment by wangyu-** [comment]
据我理解你的问题不是`处理能力低`，是发包的利用率变低了。

udp2raw本身不会做重传，重传是kcp协议这一层做的，具体原因可能得熟悉kcptun的代码才能知道。

从日志里看，发包的利用率变低了，从实际流量上看是否也是一样的现象？比如你SCP一个文件过去，用网络产生的流量和文件大小对比。

直接使用kcptun不套udp2raw，是否也是一样的现象？

**Comment by ppgl1** [comment]
我明白您意思，但您可能没细看，我说的是只有路由器里运行效率低，虚拟机里是正常的，我再调高kcptun里的时间片试试

**Comment by wangyu-** [comment]
>从日志里看，发包的利用率变低了，从实际流量上看是否也是一样的现象？比如你SCP一个文件过去，用网络产生的流量和文件大小对比。

我说的意思就是，你再虚拟机里scp和实际流量比一下，然后在路由器里scp再和实际流量比一下，是否能观察到一样的现象。

>直接使用kcptun不套udp2raw，是否也是一样的现象？

在虚拟机和路由器里分别都只用kcptun，是否也有一样的现象。

**Comment by ppgl1** [comment]
忘记说了，kcptun一直是在宿主机（win7）上的，没在路由或者虚拟机，如果不套udpraw时候，路由没有别的服务；
您说的scp问题我没做，系统内怎么看流量我不太会- -，但在vps的面板上看流量是多发的

**Comment by ppgl1** [comment]
通过psftp在vps和主机间传送10MB二进制文件，kcptun客户端在全部测试中运行于主机(win7)
kcptun参数相比上面的贴 interval 加大为50 (2017/10/30 16:53:55 nodelay parameters: 0 50 2 1)

Kcptun log@VPS:

upload to vps (udp2raw running @K2)
2017/10/30 04:19:51 KCP SNMP:&{BytesSent:210687 BytesReceived:10730436 MaxConn:1 ActiveOpens:0 PassiveOpens:1 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:9662 OutPkts:470 InSegs:9685 OutSegs:1211 InBytes:10997664 OutBytes:251623 RetransSegs:3 FastRetransSegs:2 EarlyRetransSegs:0 LostSegs:1 RepeatSegs:32 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

download from vps (udp2raw running @K2)
2017/10/30 04:24:08 KCP SNMP:&{BytesSent:10569983 BytesReceived:33868 MaxConn:1 ActiveOpens:0 PassiveOpens:1 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:596 OutPkts:25392 InSegs:7025 OutSegs:25411 InBytes:202468 OutBytes:30247267 RetransSegs:16055 FastRetransSegs:3455 EarlyRetransSegs:10440 LostSegs:2160 RepeatSegs:0 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

upload to vps (KCP only)
2017/10/30 04:33:30 KCP SNMP:&{BytesSent:204095 BytesReceived:10729740 MaxConn:1 ActiveOpens:0 PassiveOpens:2 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:9674 OutPkts:429 InSegs:9703 OutSegs:645 InBytes:10963988 OutBytes:228163 RetransSegs:2 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:2 RepeatSegs:2 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

download from (vps KCP only)
2017/10/30 04:38:39 KCP SNMP:&{BytesSent:10565735 BytesReceived:34044 MaxConn:2 ActiveOpens:0 PassiveOpens:3 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:209 OutPkts:9292 InSegs:1485 OutSegs:9311 InBytes:70532 OutBytes:10999483 RetransSegs:44 FastRetransSegs:10 EarlyRetransSegs:7 LostSegs:27 RepeatSegs:51 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

upload to vps (udp2raw running @VM)
2017/10/30 04:52:25 KCP SNMP:&{BytesSent:210791 BytesReceived:10729596 MaxConn:1 ActiveOpens:0 PassiveOpens:1 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:9637 OutPkts:423 InSegs:9661 OutSegs:766 InBytes:10966084 OutBytes:238642 RetransSegs:1 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:1 RepeatSegs:4 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

download from vps (udp2raw running @VM)
2017/10/30 04:54:57 KCP SNMP:&{BytesSent:10565111 BytesReceived:34356 MaxConn:1 ActiveOpens:0 PassiveOpens:1 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:214 OutPkts:9657 InSegs:2324 OutSegs:9680 InBytes:90176 OutBytes:11445886 RetransSegs:394 FastRetransSegs:184 EarlyRetransSegs:37 LostSegs:173 RepeatSegs:1 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

虚拟机套udp2raw跟单纯kcp性能接近，说明我搭的环境没问题吧；
K2的收包有3倍，所以我怀疑是处理不及导致服务端超时大量发包，您再看看吧，我没别的路由也没法替换试了。

**Comment by wangyu-** [comment]
```
upload to vps (KCP only)
2017/10/30 04:33:30 KCP SNMP:&{BytesSent:204095 BytesReceived:10729740 MaxConn:1 ActiveOpens:0 PassiveOpens:2 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:9674 OutPkts:429 InSegs:9703 OutSegs:645 InBytes:10963988 OutBytes:228163 RetransSegs:2 FastRetransSegs:0 EarlyRetransSegs:0 LostSegs:2 RepeatSegs:2 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}

download from (vps KCP only)
2017/10/30 04:38:39 KCP SNMP:&{BytesSent:10565735 BytesReceived:34044 MaxConn:2 ActiveOpens:0 PassiveOpens:3 CurrEstab:1 InErrs:0 InCsumErrors:0 KCPInErrors:0 InPkts:209 OutPkts:9292 InSegs:1485 OutSegs:9311 InBytes:70532 OutBytes:10999483 RetransSegs:44 FastRetransSegs:10 EarlyRetransSegs:7 LostSegs:27 RepeatSegs:51 FECRecovered:0 FECErrs:0 FECParityShards:0 FECShortShards:0}
```
这个log是udp2raw运行在路由器上的还是运行在vm上的？

**Comment by ppgl1** [comment]
单纯kcp啊

**Comment by wangyu-** [comment]
>单纯kcp啊

是的。

我的意思是，在单纯kcp的情况下，对比一下kcptun在虚拟机和在路由器上的log。

**Comment by wangyu-** [comment]
你这个单纯kcp，kcptun客户端是运行在路由器上的吗？

**Comment by ppgl1** [comment]
kcptun全在主机里啊 我用的win客户端 第一行就写了- -

**Comment by wangyu-** [comment]
>忘记说了，kcptun一直是在宿主机（win7）上的，没在路由或者虚拟机，如果不套udpraw时候，路由没有别的服务；

好。看漏了，不好意思。

**Comment by wangyu-** [comment]
再问一下你的网络拓扑是哪种情况？

1.你的电脑通过讯飞K2上网

2.你的电脑和讯飞K2处于同一局域网，通过另一台上级路由器上网。

1还是2

**Comment by ppgl1** [comment]
是2，K2是当手机的ap，上级路由是北京联通古董HG8245

**Comment by wangyu-** [comment]
你用虚拟机的时候，流量是 windows虚拟机--------->HG8245--------------->VPS

你用k2的时候，流量是这么走的：
本地windows----->HG8245------>k2------>HG8245--------------------->VPS，流量在wifi局域网里兜圈子了。(windows到k2的流量不是直连的，要通过路由器中转)

可能的原因1，你局域网内同时有3条大流量传输路径，造成了wifi信号冲突，造成了延迟抖动，导致了kcp大量重传。

可能的原因2，你的古董路由CPU受不了，造成了大的延迟，导致了kcp大量重传。

**Comment by wangyu-** [comment]
你可以尝试把kcptun直接运行在k2上试试，估计情况会有缓解。

**Comment by wangyu-** [comment]
>可能的原因2，你的古董路由CPU受不了，造成了大的延迟，导致了kcp大量重传。

也有可能是古董路由的wifi网卡的吞吐量受不了，造成了延迟或者丢包。

**Comment by ppgl1** [comment]
...才3条900k，百兆网有问题吗，没有wifi的事，k2到光猫，电脑到光猫都是网线

**Comment by ppgl1** [comment]
如果别人再有雷同的您再好好研究吧，我可以用vm不影响我用，我只是比较好奇是个例还是共性，所以发个贴

**Comment by wangyu-** [comment]
>...才3条900k，百兆网有问题吗，没有wifi的事，k2到光猫，电脑到光猫都是网线

如果全是有线，那可以排除wifi的问题了。

>如果是hg8240，nat能力的问题那虚拟机一样有问题，都是在光猫后面的啊

你的windows和虚拟机通信是不需要经过hg8240的；但是根据你的描述，你得windows和k2通信是要经过hg8240中转的。

你说的虚拟机一样有问题，不知道是不是理解错了。

**Comment by wangyu-** [comment]
>你的windows和虚拟机通信是不需要经过hg8240的

即使是桥接的，windows和虚拟机通信也都是本地的，不需要经过路由器，我在vmware和virtualbox上做过测试。

**Comment by ppgl1** [comment]
是要通过hg8240，但只是转发，不用nat不怎么费资源吧；
在K2跑udp2raw流量是您说的那么走没错，但我调高了kcptun的interval，50ms，日志里的重传都是earlytrans，和fasttrans我也不知道有什么区别，中文wiki里的kcptun的快速重传是超过2个interval收不到ack就重传，2个已经有100ms了，流量多跑这几个节点算一个5ms，抖动也超不过20ms，我下次跑一下kcptun在k2的，还有有流量在跑的时候在局域网内测测ping。

没理解错，您怀疑的是交换转发能力，我以为您怀疑的是nat能力

**Comment by wangyu-** [comment]
>是要通过hg8240，但只是转发，不用nat不怎么费资源吧；
在K2跑udp2raw流量是您说的那么走没错，但我调高了kcptun的interval，50ms，日志里的重传都是earlytrans，和fasttrans我也不知道有什么区别，中文wiki里的kcptun的快速重传是超过2个interval收不到ack就重传，2个已经有100ms了，流量多跑这几个节点算一个5ms，抖动也超不过20ms，我下次跑一下kcptun在k2的，还有有流量在跑的时候在局域网内测测ping。

我也不太清楚kcptun的这些。目前能怀疑到的只有这个了，您手上有环境，如果方便的话，直接scp个kcptun的client到k2上去测一下，能排除这个问题。

如果您测不了的话，也没关系，我找时间搭个环境自己测试一下吧，今天估计不行，手上有个别的事要做。

**Comment by ppgl1** [comment]
嗯，我下次会把win接到k2，k2接光猫，kcptun一直跑在K2上，这样K2环境比vm环境少了两次转发，如果还有问题就不是网络问题了吧

**Comment by wangyu-** [comment]
>中文wiki里的kcptun的快速重传是超过2个interval收不到ack就重传

能贴一下来源地址吗，我找了一下没找到。据我理解kcp的超时时间是算法自己算出来的，是不能指定的。

你说的interval参数，我查了一下kcp的wiki：

`interval ：协议内部工作的 interval，单位毫秒，比如 10ms或者 20ms`

貌似这个不是超时间。只是kcp算法调用的一个刷新率。

而快速重传的原理是这样的，不是根据超时时间：

>快速重传：
发送端发送了1,2,3,4,5几个包，然后收到远端的ACK: 1, 3, 4, 5，当收到ACK3时，KCP知道2被跳过1次，收到ACK4时，知道2被跳过了2次，此时可以认为2号丢失，不用等超时，直接重传2号包，大大改善了丢包时的传输速度。

而普通重传，的超时依据是RTO，不是interval。

**Comment by wangyu-** [comment]
>嗯，我下次会把win接到k2，k2接光猫，kcptun一直跑在K2上，这样K2环境比vm环境少了两次转发，如果还有问题就不是网络问题了吧

这是个好办法。

**Comment by ppgl1** [comment]
又试了一下，k2上单独跑不了kcptun，日志能连上，然后马上服务端就断开，我是官方固件只删了删广告
但是kcptun配合udp2raw却可以跑通，收包效率还是低
又试了试win连k2，k2连猫的拓扑，这样vm发包也出问题
一套下来，感觉还是k2的锅多点

**Comment by wangyu-** [comment]
>又试了一下，k2上单独跑不了kcptun，日志能连上，然后马上服务端就断开，我是官方固件只删了删广告

单独跑kcptun都跑不了，我觉得这个k2本身应该有一些奇怪的问题了，利用率低应该也不是udp2raw造成的。 用了udp2raw 情况反而从连不上变成了能连上利用率低= =。

等我有时间自己测试一下吧。

**Comment by sdysj** [comment]
买一个 ARM 开发板分担下计算压力，不贵够用。推荐 Orange Pi PC2 、Pine64 (openssl patch 后加解密性能强)，刷 armbian 很好用。

**Comment by ppgl1** [comment]
当年挖的坑，直到今年才大概搞明白，又忘了填，现在补上

电脑板载的螃蟹千兆网卡或者HG8245LAN口，工作在百兆兼容模式时候，处理超过10Mb/s的UDP流就开始丢包（iperf3 -b 10M -u）10M大概8%，30M接近30%，TCP就没有问题，（linux没测，仅指windows）可能跟厂家策略或者驱动有关吧，

简化的例子，HG8245拨号+路由，电脑直连（千兆），工作正常；仅把网卡速度调到百兆，大量丢包，跟上面那些日志类似。
