### ISSUE TITLE
客户端有概率会出现rst==1，重启客户端有概率恢复正常，也有可能还是有rst

### ISSUE THREAD

**Issue by HongdaWang** [wangyu-/udp2raw-tunnel#79]
hi!@wangyu-,首先谢谢你开发这款程序！以下是我的问题描述：

我的客户端是一台在本地局域网中的没有独立公网ip的物理机，系统是centos7 amd64,服务端是openvz的虚拟机，系统是debian8 amd64，udp2raw版本是20170918.0

**客户端配置如下：**
iptables如下，是写死的
$ iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N udp2raw
-A INPUT -s 112.32.59.67/32 -p tcp -m tcp --sport 8888 -j udp2raw
-A udp2raw -j DROP

udp2raw客户端配置文件如下：
-c
-l 0.0.0.0:5555
-r 112.32.59.67:8888
#-a
-k nicai
#--log-level 6
--raw-mode faketcp
#--raw-mode icmp
--cipher-mode none
--auth-mode none

**服务端配置如下**
iptables如下，是写死的
$ iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-N udp2raw
-A INPUT -p tcp -m tcp --dport 8888 -j udp2raw
-A udp2raw -j DROP

udp2raw服务端配置文件如下：
-s
-l 0.0.0.0:8888
-r 127.0.0.1:9999
#-a
-k nicai
#--log-level 1
--raw-mode faketcp
#--raw-mode icmp
--cipher-mode none
--auth-mode none

服务端日志是正常的，没有error。客户端日志中不一定什么时候就会出现rst==1,如下：
[2017-11-02 12:05:17][ERROR][112.32.59.67,8888]rst==1
[2017-11-02 12:05:19][ERROR][112.32.59.67,8888]rst==1
[2017-11-02 12:05:29][ERROR][112.32.59.67,8888]rst==1
[2017-11-02 12:05:31][ERROR][112.32.59.67,8888]rst==1

但是我重启多次客户端后，rst有可能会消失。就跟有概率一样，说不定哪一次重启客户端就会正常了。
我的服务端日志没有error，上边重启的都是客户端，服务端没有重启。

请问这难道是我本地的局域网的问题吗？我有多台国外vps，客户端都在这台centos7服务器上，然而就这个客户端进程会有rst

**Comment by wangyu-** [comment]
我有个疑问，为什么你之前发的截图里RST来自于端口19777？真实的配置到底是怎样的？发到我gmail里。

一般出现RST都是iptables有问题造成的。可能是udp2raw本身需要的iptables规则没有加对，也有可能是其他iptables规则干扰了udp2raw的规则。 

我注意到你的iptables规则不是用-g选项生成的，而是仿照udp2raw自动添加的规则改的，不知道改错了没有。

建议在两端把iptables所有表的规则全都清空，然后用udp2raw的-g选项生成iptables规则，手动加入。

另外在两边加上--lower-level auto选项，这个经常可以解决一些iptables不兼容问题。

**Comment by HongdaWang** [comment]
就是这个，端口改过

**Comment by HongdaWang** [comment]
在就是我不觉得是iptables的问题，如果是iptables的问题，那为什么有时候重启后就正常了呢

**Comment by wangyu-** [comment]
>在就是我不觉得是iptables的问题，如果是iptables的问题，那为什么有时候重启后就正常了呢

同样的逻辑是不是也可以套用在 `不是运营商问题` `不是程序bug` `不是VPS问题上`，我没说肯定是iptables问题，只是建议你清空iptables，先排除iptables问题。

我建议追问题时不要主观臆断，按正常套路来，先排除一些容易排除的问题。

另外，你可以在VPS上用tcpdump抓包，确认一下RST是从VPS上发出来的还是从中间某个未知的设备上发出来的。

**Comment by HongdaWang** [comment]
程序一点问题都没有，最终原因是我的iptables配置错了，不懂iptables的最好是用udp2raw生成的iptables命令行添加iptables规则。我之前发邮件问的王工，再次感谢王工的耐心解答
