### ISSUE TITLE
关于 QUIC 初始化失败

### ISSUE THREAD

**Issue by sdysj** [wangyu-/udp2raw-tunnel#84]
一点小问题，发现套上 udp2raw 后 chrome 的 QUIC 会失效。搜索发现

https://groups.google.com/a/chromium.org/d/msg/proto-quic/uKWLRh9JPCo/P39TV66PWxMJ

- IPv4 then QUIC max packet size = 1350
- If IPv6 then QUIC max packet size = 1350-20 = 1330
- And all initial QUIC HELLO packet MUST be padded to QUIC max packet size.

我是 UDPSpeeder_v1 + udp2raw + shadowvpn (mtu1350) 的。

而 UDPSpeeder_v1 + shadowvpn (mtu1432) QUIC 正常。

**Comment by wangyu-** [comment]
套上udp2raw后数据包变长了。

我不熟悉s***VPN，看你的描述，应该是因为s***VPN对UDP数据包没有拆分能力造成的，不能自动拆分数据包到指定的MTU以下。

用OpenVPN配合`fragment 1200`可以解决； 换UDPspeederV2 用mode 0模式也可以解决，或者直接换成tinyFecVPN。

**Comment by sdysj** [comment]
UDPSpeeder_v2 和 tinyFecVPN 也不行啊，貌似只要 QUIC 握手包少于 1350 都不行。

**Comment by wangyu-** [comment]
你自己的配置问题。

**Comment by sdysj** [comment]
配置没问题啊，正常上网，正常游戏，也就 QUIC 无法工作，换了 openvpn 还是这样，你确定你的可以在刷 youtube 在时 chrome://net-internals/#quic 里看到有 QUIC 连接信息吗，我撤掉 udp2raw 就可以看到了，我觉得这是 QUIC 本身问题，不用也没什么大不了反正加速了速度也差不多也就缓冲时比用 QUIC
 时慢一点而已。

**Comment by wangyu-** [comment]
>你确定你的可以在刷 youtube 时 chrome://net-internals/#quic 里看到有 QUIC 连接信息吗

![quic](https://user-images.githubusercontent.com/4922024/32497234-be6766a0-c380-11e7-90f2-c994e106f0d4.PNG)

udp2raw+tinyFecVPN实测没有问题。

我建议你用tinyFecVPN时候就用默认参数什么也不要改，用UDPspeeder时候除了用`--mode 0`其他什么也不要改。

**Comment by wangyu-** [comment]
`--mtu`是被归类到advanced options里的，如果在不懂怎么用的情况下修改可能会引起严重的副作用。

**Comment by sdysj** [comment]
我是默认参数啊，难道是路由 MSS 问题吗？我再调试一下吧，先关闭。

**Comment by wangyu-** [comment]
我提醒你一下，QUIC是Chrome的实验特性，貌似是不支持socks5的，我是直接在VPN基础上配的路由策略。

如果你用的是VPN+socks5的方法，可能会不行。

**Comment by sdysj** [comment]
我也是策略路由，LEDE 路由上的 ss-redir 连 shadowvpn 内网IP (10.123.1.1) 只转发 TCP，UDP 则走 shadowvpn (MTU 1350,再大就无法通信) ， OrangePiPC 跑的 UDPSpeeder + udp2raw (都是基本设置，没其他特殊修改) 。反正现在怎么设置还是无法完成 QUIC 握手，把 udp2raw 撤了就可以，摊手了。
