### ISSUE TITLE
支持IPSEC吗？

### ISSUE THREAD

**Issue by lishen226** [wangyu-/udp2raw-tunnel#86]
好像不能同时绑两个端口
nohup ./udp2raw_amd64 -s -l0.0.0.0:8855 -r 127.0.0.1:500 -k "passwd" --raw-mode faketcp -a >/dev/null 2>&1
nohup ./udp2raw_amd64 -s -l0.0.0.0:8856 -r 127.0.0.1:4500 -k "passwd" --raw-mode faketcp -a >/dev/null 2>&1
我在服务器上同时运行两个命令，客户端是windows+LEDE虚拟机，在windows上连VPN，提示IKEV认证的错误，。但能看到控制台上分别收到500端口和4500端口的数据。

新手不太会玩。。。KCP是真快

**Comment by wangyu-** [comment]
IPSEC不只会使用UDP端口，会用到一个非UDP的协议，不行。

**Comment by lishen226** [comment]
我用的是IKEV2，确定只用UDP的500和4500端口，因为我VPS防火墙只开了UDP的这两个端口，直连能够连上

**Comment by lishen226** [comment]
改用kcpraw+openvpn了哈，有windows客户端，方便

**Comment by wangyu-** [comment]
>我用的是IKEV2，确定只用UDP的500和4500端口，因为我VPS防火墙只开了UDP的这两个端口，直连能够连上

会用到一个协议号为50的协议，既非TCP也非UDP，你看端口时看不到。

**Comment by lishen226** [comment]
这样啊，谢了
