### ISSUE TITLE
请问source-ip 这个参数是什么意思？

### ISSUE THREAD

**Issue by lixiaominggit** [wangyu-/udp2raw-tunnel#88]
![image](https://user-images.githubusercontent.com/5425397/32657790-9f07e45c-c5dc-11e7-80ee-8da98a4ebe76.png)

**Comment by lixiaominggit** [comment]
是客户端地址还是服务端的？

**Comment by wangyu-** [comment]
一般出这个错误是你的参数填错了，或者网络有问题。

另外，认真读一下：

https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看

**Comment by lixiaominggit** [comment]
感谢回答，上面的问题解决了，是网络不通的问题。

还有个问题，我想同时使用udpspeeder和udp2raw,  那么它俩的使用顺序哪种比较好？先加速还是先伪装？

**Comment by wangyu-** [comment]
只可以是udpspeeder client--->udp2raw client---->udp2rawserver--->udpspeeder server。

其他方法无法连通。

**Comment by lixiaominggit** [comment]
好的，谢谢
