### ISSUE TITLE
请问下使用udp2raw+udpspeeder和单独直接使用udpspeeder会有效果上的区别吗？

### ISSUE THREAD

**Issue by LockVer** [wangyu-/udp2raw-tunnel#95]
1、udp2raw+udpspeeder是不是比单独udpspeeder效果差一些啊？
2、不考虑流量、想降低延迟、使用udpspeeder v1还是v2呢？如何设置能达到最大化的降延迟效果呢？
另外我测试udpspeeder的时候发现个问题，就是那个吃鸡黑屏卡住不动的问题，可能是ss版本造成的，我用的梅林固件上面帮助里面的一键安装，如果使用里面的一键安装Shadowsocks-libev或者Shadowsocks-libev+kcptun就会出现这种情况，而使用另外的就不会。使用梅林固件帮助里面一键安装的朋友可以注意一下。
然后我在使用centos 7以上，都无法接收到客户端的连接，服务端没任何提示，使用6.5 64位、debian 8、Ubuntu 14.04都成功连接。debian 9以及Ubuntu 更高版本没有测试过。

**Comment by wangyu-** [comment]
>1、udp2raw+udpspeeder是不是比单独udpspeeder效果差一些啊？

不是。

你读一下udp2raw和udpspeeder的readme，说得很清楚了。

>2、不考虑流量、想降低延迟、使用udpspeeder v1还是v2呢？如何设置能达到最大化的降延迟效果呢？

https://github.com/wangyu-/UDPspeeder/wiki/使用经验

```
./speederv2 -s -l0.0.0.0:4096 -r127.0.0.1:7777  -f2:4 -k "passwd" --mode 0 -q1
./speederv2 -c -l0.0.0.0:3333 -r44.55.66.77:4096 -f2:4 -k "passwd" --mode 0 -q1
```

>然后我在使用centos 7以上，都无法接收到客户端的连接，服务端没任何提示，使用6.5 64位、debian 
8、Ubuntu 14.04都成功连接

基本上是你系统自带的iptables的问题。或者是s的一键安装脚本的问题。

https://github.com/wangyu-/tinyFecVPN/wiki/清空iptables的方法

**Comment by LockVer** [comment]
@wangyu- 好的。晚上回去试试V2.

**Comment by LockVer** [comment]
@wangyu- 对了，我昨天测试了下，V1+UDP2RAW的话吃鸡就会黑屏卡死，单独用V1就不会。。这个不知道是什么问题。。

**Comment by Hadsital** [comment]
这个建议自己测试一下 我这边直接用udp2raw很好 但是加了udpspeeder会有略微的卡顿

**Comment by LockVer** [comment]
@Hadsital 那你是直接用的udp2raw伪装SS的UDP流量吗？还是udp2raw+kcptun？

**Comment by Hadsital** [comment]
不是 我是openvpn+udp2raw

**Comment by LockVer** [comment]
@Hadsital 哦哦。。openvpn是不是不能单独加速某一个应用啊？我之前用过，但是是全局加速。。这样玩游戏的时候想看网页都没办法。。不过openvpn加速效果感觉比ss好很多。。特别是延迟。。

**Comment by Hadsital** [comment]
`还行吧 你可以不用全局 国内的走国内 写点route 国内不通过openvpn就行了

**Comment by LockVer** [comment]
@Hadsital 就和S**S一样就行了啊，国内的走国内，国外的走国外。。需要做些啥呢。。想搞。。

**Comment by LockVer** [comment]
@wangyu- 大佬对openvpn有研究吗？怎样能做到国内的走普通的，国外的走openvpn呢，就和s**s的PAC模式一样。。

**Comment by wangyu-** [comment]
@LockVer  

用`ip route`。去网上查一下，资料很多。如果是复杂的功能可能还需要用`ip rule`和`iptables`

**Comment by LockVer** [comment]
@wangyu- 好的。

**Comment by LockVer** [comment]
@wangyu- 昨天试了下，udp2raw+v1 就不能玩吃鸡，可能就是mtu的原因，v2就无压力。
