### ISSUE TITLE
rst==1 的问题

### ISSUE THREAD

**Issue by trivita** [wangyu-/udp2raw-tunnel#96]
班瓦工ubuntu server + 最新版的udp2raw和kcptun
用https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/kcptun_step_by_step.md的办法可以重现
client端在vmware debian虚机里面，kcptun也在同一个虚拟机里面，测试也是在同一个虚机里面完成（所以不是bridge的问题）

faketcp的时候几乎建立不起来ssh，很不稳定
udp的时候迅速建立，没有任何问题

服务端log里面隔三差五的就是[][ERROR][xxx,yyy]rst==1的日志

![image](https://user-images.githubusercontent.com/1425147/33115067-7cab104c-cf9a-11e7-81fb-40f189823f2c.png)

**Comment by trivita** [comment]
![image](https://user-images.githubusercontent.com/1425147/33115053-75e7ce44-cf9a-11e7-9f3b-0fdcefa5f95f.png)

**Comment by wangyu-** [comment]
虚拟机是不是桥接？本地ISP是什么，长城宽带？

看一下这个，先自我排查，然后补齐信息：

https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看

**Comment by trivita** [comment]
混github很久了，还是有礼节的。iptable确定不是问题
下面的架构，虚拟机不是bridged不影响吧。。。而且链接是极不稳定，但还是成功过的
      
        VMWare Debian                                  Bandwagonhost
[ ssh -> kcptun -> udp2raw] ----ISP----> [ udp2raw -> kcptun]

本地isp北京联通专线

**Comment by wangyu-** [comment]
如果是VMware的nat模式，肯定不能使用。

**Comment by wangyu-** [comment]
>client端在vmware debian虚机里面，kcptun也在同一个虚拟机里面，测试也是在同一个虚机里面完成（所以不是bridge的问题）

跟kcptun是否在同一个虚拟机里是无关的。 vmware的特殊7层nat模式会破坏udp2raw的工作。

**Comment by trivita** [comment]
got it. switching to bridged mode. and get bavk to you later

**Comment by trivita** [comment]
it should be the bridged mode issue. closed for now. thanks.
