### ISSUE TITLE
关于udp2raw在路由器修改路由器wan端口mtu至1250的情况下无法建立连接的问题

### ISSUE THREAD

**Issue by DimGG** [wangyu-/udp2raw-tunnel#97]
无论在路由器的WAN或者服务器的网卡上更改MTU，UDP连接就无法再建立，日志如下
![image](https://user-images.githubusercontent.com/17081057/33121218-1807cddc-cfaf-11e7-9c5d-e0d19dee3776.png)

一旦把MTU改回1500立刻可以恢复连接。

**Comment by keeno1982** [comment]
记得调MTU是kcptun或者speeder里面调的，不是网卡或路由
